<template>
	<div class="Cap1">
		<p>Segundo a OMS (Organização Mundial da Saúde), mais de 1,2 milhão de pessoas morrem por ano em todo o mundo devido a acidentes de trânsito - uma morte a cada 25 segundos -, sendo que esta é a causa de morte mais frequente entre pessoas com idade de 15 e 29 anos e a nona mais comum na população geral<a title=" Informações do GLOBAL STATUS REPORT ON ROAD SAFETY, 2015" href='http://www.who.int/violence_injury_prevention/road_safety_status/2015/en/' style='cursor: help;' target="_blank"><sup>1</sup></a>..</p>
		<p>A distribuição dos acidentes de trânsito no planeta não é homogênea. Embora sejam responsáveis por 54% dos veículos registrados do mundo - e 82% da população total -, os países de baixa e média renda respondem por 90% dessas mortes.</p>
		<p>Por conta disso, a ONU (Organização das Nações Unidas) instituiu a Década de Ação para Segurança no Trânsito (2011-2020), coordenada pela OMS, com o objetivo de "estabilizar e reduzir os níveis globais previstos de mortes no trânsito por meio de atividades em escala nacional, regional e global". Já os Objetivos de Desenvolvimento Sustentável são um "plano de ação" focado em 17 objetivos e 169 metas, sendo duas delas diretamente relacionadas à segurança no trânsito:</p>
		<p>Meta 3.6 [Saúde e Bem Estar]: Até 2020, reduzir pela metade as mortes e os ferimentos globais por acidentes em estradas.<a title="http://www.itamaraty.gov.br/images/ed_desenvsust/ODSportugues12fev2016.pdf" href='http://www.itamaraty.gov.br/images/ed_desenvsust/ODSportugues12fev2016.pdf' style='cursor: help;' target="_blank"><sup>2</sup></a></p>
		<p>Meta 11.2 [Cidades e Comunidades Sustentáveis]: Até 2030, proporcionar o acesso a sistemas de transporte seguros, acessíveis, sustentáveis e a preço acessível para todos, melhorando a segurança rodoviária por meio da expansão dos transportes públicos, com especial atenção para as necessidades das pessoas em situação de vulnerabilidade, mulheres, crianças, pessoas com deficiência e idosos.</p>
		<p>No Brasil, foram atestados 38.265 óbitos na categoria Acidentes de Transporte em 2016, segundo dados do Departamento de Informática do Sistema Único de Saúde (DATASUS), o que resulta em 18,4 óbitos a cada 100 mil habitantes.</p>
		<p>No mundo, assim como no Brasil, as mortes no trânsito foram a oitava principal causa de morte no ano de 2016, conforme recente relatório da OMS<a title="http://www.who.int/news-room/fact-sheets/detail/the-top-10-causes-of-death" href='http://www.who.int/news-room/fact-sheets/detail/the-top-10-causes-of-death' style='cursor: help;' target="_blank"><sup>3</sup></a>. Os acidentes de trânsito são também os principais causadores de mortes de jovens entre 15 e 24 anos no mundo e a segunda principal causa no Brasil. Independentemente da faixa etária, as mortes no trânsito representam a terceira causa de mortes prematuras no Brasil em 2016, ficando atrás apenas de doenças isquêmicas do coração e violência interpessoal<a title="http://www.healthdata.org/brazil" href='http://www.healthdata.org/brazil' style='cursor: help;' target="_blank"><sup>4</sup></a>..</p>
		<p>Dessa forma, a promoção de segurança no trânsito se mostra como um imperativo de saúde pública, capaz de limitar e conter as altas taxas de mortalidade observadas no Brasil e no mundo.</p>
		<p>Criado na Suécia em 1997, o Visão Zero é uma forma específica de entender e desenvolver um sistema seguro de mobilidade, buscando reduzir as mortes e lesões graves no trânsito a zero. Uma das principais ações consistiu em desenhar ou reconfigurar vias priorizando os deslocamentos e a segurança de pedestres e ciclistas ao invés de dedicar todos os recursos aos automóveis. Na Suécia, a estratégia funcionou e a taxa de mortalidade no trânsito do país caiu 55% entre 1994 e 2015. Diversos outros países, como Noruega e Holanda, adotaram abordagens semelhantes e apresentam as taxas mais baixas de mortalidade no trânsito e as maiores reduções no número de mortes ao longo dos últimos 20 anos.</p>
		<p>A abordagem do Sistema Seguro consiste em reorientar a forma como a segurança viária é vista e gerenciada, reconhecendo que os seres humanos cometem erros quando usam as ruas e sistemas de transporte, assim como em qualquer outra circunstância cotidiana. Na medida em que os seres humanos não são infalíveis, os projetistas da infraestrutura viária devem criar sistemas de transporte nos quais as consequências do erro humano sejam minimizadas. Um sistema viário que ajuda a perdoar erros dos diferentes usuários reduz o número de falhas graves que podem resultar em mortes ou lesões graves.</p>
		<p class="quotation" title="'It's not just about why someone crashed, it asks why they were so badly injured, how could the crash force have been reduced. In a safe system, a serious crash isn't someone's fault, it's a system failure. It's not about blaming drivers for the devastation of a crash, it's about asking what could we have done differently to reduce their devastation. What components could we improve to make the system more forgiving so that mistakes don't cost lives or limbs. It's not about being reactive, it's about being proactive and asking how we can reduce risk'. Disponível em https://www.youtube.com/watch?v=mFcLUCtUAzc. Acesso em 02/10/2018.">
			“Não se trata apenas do porquê alguém se envolveu em uma ocorrência de trânsito, mas o porquê ela se lesionou e como o impacto poderia ter sido reduzido. Em um sistema seguro, uma ocorrência grave não ocorre por culpa de alguém, mas é uma falha do sistema. Não se trata de culpar motoristas, mas se perguntar o que de diferente poderia ter sido feito para reduzir os danos. Quais componentes podemos melhorar para tornar o sistema mais perdoável para que os erros não custem a vida. É não agir reativamente, mas ser proativo e perguntar como podemos reduzir riscos.” [tradução nossa]<a title="https://www.youtube.com/watch?v=mFcLUCtUAzc" href='https://www.youtube.com/watch?v=mFcLUCtUAzc' style='cursor: help;' target="_blank"><sup>5</sup></a>
		</p>
		<p>Dentre os diversos impactos negativos dos acidentes de trânsito na sociedade, além da perda de qualidade de vida, dor e sofrimento a qual estão sujeitas as vítimas, seus familiares e a sociedade, há que se elencar os custos econômicos elevados para as cidades, sejam eles diretos ou indiretos.</p>
		<p>Em recente relatório, publicado em conjunto pelo Banco Mundial e a Bloomberg Philanthropies, estima-se que o impacto macroeconômico dos acidentes de trânsito em países em desenvolvimento é substancial. Ao analisar casos de países como China, Tanzânia, Filipinas, Índia e Tailândia, conseguiu-se demonstrar que uma redução sustentável de morbidade e mortalidade no trânsito da ordem de 50%, ao longo de 24 anos, poderia gerar um impacto positivo de 7 a 22 % no PIB desses países<a title="Disponível em https://openknowledge.worldbank.org/bitstream/handle/10986/29129/HighTollofTrafficInjuries.pdf?sequence=5&isAllowed=y. Acesso em 12/10/2018" href='https://openknowledge.worldbank.org/bitstream/handle/10986/29129/HighTollofTrafficInjuries.pdf?sequence=5&isAllowed=y' style='cursor: help;' target="_blank"><sup>6</sup></a>. Igualmente, diversos estudos<a title="  Disponível em https://library.swov.nl/action/front/fulltext?id=342686. Acesso em 12/10/2018." href='https://library.swov.nl/action/front/fulltext?id=342686' style='cursor: help;' target="_blank"><sup>7</sup></a> apontam que o custo anual dos acidentes para países de renda baixa e média, como o Brasil, é da ordem de 1 a 3% dos respectivos PIBs.</p>
		<p>O Instituto de Pesquisas Econômicas Aplicadas (IPEA) realizou uma pesquisa para estimar esses custos em cidades brasileiras no documento “Impactos Sociais e Econômicos dos Acidentes de Trânsito nas Aglomerações Urbanas Brasileiras”. Utilizando-se o método proposto por esse documento, com os valores atualizados para o ano de 2017 com base no Índice de Preços ao Consumidor Amplo (IPCA), levando em conta que, em 2017, foram registrados em São Paulo 12.271 acidentes com vítimas feridas e 762 com vítimas fatais (não são registrados acidentes sem vítimas), os custos estimados dos acidentes de trânsito para a cidade de São Paulo em 2017 foram R$ 763.830.716.</p>
	</div>
</template>

<script>
export default {
	name: 'Cap1'
}
</script>
