<template>
	<div class="Cap2B">
		<p>A visão tradicional sobre a segurança viária tende a focar o comportamento dos indivíduos, de modo a responsabilizar excessivamente as mortes e lesões no trânsito sobre as atitudes individuais. Contudo, os princípios da Visão Zero e Sistemas Seguros partem da premissa de que a responsabilidade sobre a segurança viária é compartilhada entre o poder público e os usuários da via, sendo a cultura e o comportamento no trânsito fruto de um amplo conjunto de variáveis, que não só a educação individual do cidadão, tais como o desenho das ruas, a efetividade das ações de fiscalização e campanhas educacionais.</P>
		<p>A abordagem baseada no foco excessivo sobre o indivíduo, ignorando que o comportamento individual é fruto de um conjunto de determinantes que criam estímulos e desestímulos aos comportamentos, não é condizente com os princípios deste plano. Nesse sentido, é preciso fortalecer o olhar para a segurança viária e abordar o tema sem que a vítima seja culpabilizada. Ademais, deve-se buscar transformar o atual comportamento dos condutores à luz dos conceitos da Política Nacional de Mobilidade Urbana, que estabelece a ordem de priorização dos usuários da via – dos mais vulneráveis para os menos vulneráveis. Adicionalmente, a cultura da segurança viária ainda não está institucionalizada na cultura organizacional do poder público como tema transversal de valor primordial, o que requer o fortalecimento do olhar à segurança pelos órgãos públicos.</p>
		<p>Para traçar um diagnóstico dos comportamentos relativos à segurança viária em São Paulo, escolheu-se o enfoque nos quatro fatores de risco estabelecidos pela Organização Mundial da Saúde: condução de veículos sob o efeito de álcool, uso de dispositivos de retenção em veículos, velocidade e uso de capacete por motociclistas.</p>
		<p>A frequência de adultos que admitem conduzir veículos motorizados após terem ingerido qualquer tipo de bebida alcoólica aumentou 16% em todo o país segundo pesquisa do Ministério da Saúde (Vigitel, 2017). De acordo com o CPTran, em 2017, do total de 170.877 pessoas demandadas à realização do teste de etilômetro, 16.813 se recusaram a fazer o teste e 3.488 foram reprovados. O total de recusas e reprovamentos representam 11,88% do total.</p>
		<p>Outro comportamento de risco é a não utilização do cinto de segurança. Pesquisa da CET de 2017 revelou que a taxa de utilização do cinto pelos motoristas foi de 97,5%, enquanto que pelos passageiros do banco dianteiro foi de, de 74,6%. No entanto, a taxa de uso de cinto por adultos cai para 30,2% no banco traseiro<a title="  O valor 30,2% é para o uso de cinto de segurança apenas por adultos. Ao se considerar adultos e crianças, o índice de 32,72%." style='cursor: help;'><sup>21</sup></a>.</p>
		<p>Já de acordo com o Relatório de Dados Técnicos realizado no segundo semestre de 2018 pela Johns Hopkins International Injury Research Unit (JH-IIRU) e Universidade de São Paulo (USP), 97% dos motoristas utilizam o cinto de segurança, enquanto que 93% dos passageiros do banco dianteiro o fazem. Por sua vez, apenas 22% dos adultos do banco traseiro utilizam cinto.</p>
		<p>O menor uso de cinto de segurança no banco traseiro pode ser atribuída à cultura de deixar as fivelas do cinto de segurança embaixo do banco e à falta de compreensão de que o passageiro no banco de trás corre o mesmo risco que o passageiro no banco da frente. Em uma colisão, o passageiro do banco traseiro pode ser arremessado para frente ocasionando lesões em si e em quem está sentado no banco frontal.</p>
		<p>Em relação ao uso de dispositivos de retenção para crianças (as chamadas “cadeirinhas”), de acordo com a JH-IIRU e USP (2018) , apenas 47% das crianças menores de 5 anos fizeram uso do equipamento. Essa taxa é maior para crianças maiores de 5 e menores de 11 anos (53%).</p>
		<p>Já quanto ao excesso de velocidade, verificou-se tendência de aumento de veículos trafegando acima da velocidade máxima permitida, atingindo 14% no primeiro semestre de 2018. Dentre os tipos de veículo analisados, destaca-se o percentual ainda mais alto de motociclistas trafegando acima da velocidade, que foi de 43% no segundo semestre de 2018 (JH-IIRU e USP, 2018).</p>
		<slot name='t8'></slot>
		<p>Em relação ao capacete, quase 100% dos motociclistas o utilizam corretamente. Esse comportamento adequado mantém-se estável desde 2015 (JH-IIRU e USP, 2018).</p>
		<p>Por fim, vale mencionar pesquisa publicada na Revista Médica de Minas Gerais em 2017 sobre o uso de drogas por caminhoneiros, tendo em vista a alta letalidade dos acidentes envolvendo caminhões. De acordo com a pesquisa, 32,9% dos caminhoneiros entrevistados admitiram terem feito uso de anfetaminas (rebite) nos últimos três meses.</p>
	</div>
</template>

<script>
export default {
	name: 'Cap2B'
}
</script>
