<template>
	<div class="Cap2CEixoIV">
<h5>1.	Introdução</h5>
<p class="quotation">"As leis sobre segurança viária melhoram o comportamento dos usuários e reduzem as colisões, as lesões e as mortes no trânsito (...). (...) As mudanças mais positivas no comportamento dos usuários das vias ocorrem quando a legislação é associada a uma aplicação rigorosa e continuada da lei e pela sensibilização do público." (OMS, 2015, p. 5)</p>
<p>A existência de legislação adequada, ordenando o comportamento dos atores no trânsito, e a respectiva fiscalização são partes essenciais dos sistema seguros, viabilizando os incentivos adequados à mudança comportamental e prevenindo comportamentos e situações de risco que podem resultar em acidentes, lesões e mortes no trânsito. Não por outra razão, o fortalecimento da legislação e da fiscalização foi parte central da "Declaração de Brasília".</p>
<p>"O documento [a “Declaração de Brasília”] é um dos resultados da 2ª Conferência Global de Alto Nível sobre Segurança no Trânsito, realizada na capital federal nos dias 18 e 19 de novembro de 2015. O evento foi realizado dentro do escopo da Década de Ação pela Segurança no Trânsito 2011-2020. Ao fim do evento, os delegados dos Estados membros participantes aprovaram a Declaração. Trata-se de um marco importante em relação ao item 3.6 dos Objetivos de Desenvolvimento Sustentável (ODS)”.</p>
<p>Entre as ações recomendadas para fortalecer o gerenciamento da segurança no trânsito e aprimorar a legislação e fiscalização estão:</p>
<ul>
	<li>Encorajar os Estados que ainda não o tenham feito a designar e/ou fortalecer agências coordenadoras e mecanismos de coordenação, com financiamento próprio, em nível nacional ou subnacional, assim como fortalecer a colaboração nessa área entre governos, incluindo entre parlamentos, sociedade civil, instituições acadêmicas, setor privado e fundações filantrópicas;</li>
	<li>Incentivar a sociedade civil, as instituições acadêmicas, o setor privado e as fundações filantrópicas a fortalecer seus compromissos para acelerar a implementação do Plano Global para a Década de Ação para a Segurança no Trânsito 2011-2020;</li>
	<li>Convidar os Estados que ainda não o tenham feito a redobrar esforços para desenvolver e implementar planos nacionais sobre segurança no trânsito e a aplicar legislação abrangente, em consonância com o Plano Global para a Década de Ação para a Segurança no Trânsito 2011-2020, com vistas a atingir a meta de aumentar a porcentagem de países com legislação abrangente sobre os principais fatores de risco, incluindo o não-uso de cintos de segurança, de dispositivos de retenção para o transporte de crianças e de capacetes; direção sob a influência de álcool; e o excesso de velocidade; de 15% para, pelo menos, 50% até 2020, tal como acordado na resolução da Assembleia Geral das Nações Unidas 64/255 de 2010;</li>
	<li>Identificar outros fatores de risco que levem à distração ou à diminuição da capacidade do condutor, tais como: condições médicas e medicamentos que afetem a direção segura; fadiga; uso de drogas narcóticas, psicotrópicas e substâncias psicoativas; distrações visuais nas vias; celulares e outros dispositivos eletrônicos e de mensagens de texto; e adotar, caso seja apropriado, legislação efetiva e baseada em evidências;</li>
	<li>Reforçar estratégias de policiamento nas vias e medidas de fiscalização de trânsito, com foco na redução de acidentes, inclusive por meio da promoção de integração entre agências de policiamento e inspeção de trânsito, assim como a coleta de dados sobre infraestrutura viária e ocorrências no trânsito;</li>
	<li>Incentivar pesquisas e o compartilhamento de seus resultados para apoiar abordagens baseadas em evidências para prevenir mortes e lesões no trânsito e mitigar suas consequências;</li>
	<li>Incentivar os Estados a introduzirem novas tecnologias de gestão do trânsito e de sistemas de transporte inteligentes para mitigar os riscos de lesões e mortes no trânsito e maximizar a eficiência nas respostas." (OPAS, 2015)</li>
</ul>
<p>Como se verá ao longo deste tópico, de forma geral, as recomendações constantes da Declaração de Brasília coincidem com as necessidades apontadas no diagnóstico para a cidade de São Paulo. Há, por conta de competências legislativas, limitações nas possibilidades de solução de determinados problemas pela municipalidade e, de outro lado, questões já endereçadas pela cidade que, ao longo das últimas décadas, sempre esteve na vanguarda das ações de fiscalização para promoção da segurança viária no Brasil.</p>

<h5>2.	Competências Legislativas</h5>
<p>No Brasil, a competência legislativa sobre trânsito e transporte, de acordo com o artigo 22, XI, da Constituição Federal, é privativa da União. Essa competência legislativa encontra-se concretizada em diversas leis esparsas e no Código de Trânsito Brasileiro (CTB), Lei Federal nº. 9.503/1997. A competência regulatória decorrente do regramento exposto no código é reservada ao CONTRAN, conforme explicitado nos artigos 10 e 12 do CTB.</p>
<p>Isso, contudo, não importa dizer que outras esferas federativas não tenham competência legislativa sobre a matéria de trânsito e transporte. Mediante lei complementar, os Estados e o Distrito Federal podem suplementar a competência da União naquilo que for especificamente detalhado.</p>
<p>Já os Municípios possuem competência originária na Constituição Federal para tratar do tema quando envolver questões de interesse local e em consonância com a legislação federal. O que os permite, por exemplo, especificar a velocidade de determinadas vias abaixo do limite máximo estabelecido no CTB, ordenar o sentido do tráfego, disciplinar o estacionamento, entre outras definições de interesse eminentemente local.</p>
<p>No que diz respeito à execução da fiscalização, a divisão de competências prevista no CTB é a que segue:</p>
<ul>
	<li>Compete aos Órgãos Executivos de Trânsito dos Municípios fiscalizar e autuar as infrações relacionadas nos incisos VI e VII do Art. 24 do CTB, mormente, estacionamento, parada, circulação, excesso de peso, dimensão e lotação dos veículos.</li>
	<li>Aos Órgãos Executivos de Trânsito dos Estados, compete fiscalizar e autuar as demais infrações de trânsito, exceto aquelas relacionadas no incisos VI e VII do Art. 24 do CTB. Isso implica em uma competência sobretudo voltada à regularidade dos veículos e dos condutores, além de outras infrações.</li>
</ul>
<p>Às Polícias Militares Estaduais compete executar a fiscalização de trânsito, quando e conforme convênio firmado com os Órgãos Executivos de Trânsito dos Estados e Municípios, conforme Art. 23 do CTB.</p>
<p>Portanto, quando existente convênio com o Estado em que está situada e com o município, a competência fiscalizatória da Polícia Militar é plena, abrangendo todas as infrações previstas no CTB.</p>
<p>Esse é o caso do Município de São Paulo, onde a Polícia Militar possui convênios com as autoridades municipais detalhando sua competência para fiscalizar a totalidade das infrações previstas na legislação, sem derrogar, contudo a competência originária do Município de fiscalizar, concorrentemente e por órgãos e entidades próprios, as infrações que lhe foram atribuídas pelo CTB.</p>

<h5>3.	Legislação e Fiscalização dos fatores de risco</h5>
<p>Há uma forte correlação entre condutas de risco e resultados danosos em termos de mortalidade e morbidade (Dunlop, 2013). Dessa forma, ao se coibir o cometimento de infrações, incentivando comportamentos seguros, alcança-se significativa redução de mortos e feridos.</p>
<p>No entanto, existem diversas infrações previstas na legislação nacional de trânsito que podem de algum modo influenciar a segurança viária. Como forma de pautar a prioridade e a eficiência fiscalizatórias de seus países membros, a OMS busca destacar aqueles comportamentos inadequados mais propensos a causar lesões e mortes no trânsito, denominados fatores de risco.</p>
<p>“Fator de risco”, segundo a OMS, é qualquer atributo, característica ou exposição de um indivíduo que aumente sua probabilidade de desenvolver alguma doença ou de sofrer alguma lesão.</p>
<p>O risco de se lesionar no trânsito é composto por múltiplos fatores que passam por questões socioeconômicas e culturais da população, pela forma de uso e ocupação da cidade e pela estrutura do sistema de transporte, chegando a atitudes comportamentais agressivas e/ou imprudentes dos usuários da rede viária.</p>
<p>Em seus principais e mais recentes relatórios (OMS, 2006, 2015), a OMS define os quatro principais fatores de risco, responsáveis pela maioria das mortes e lesões no trânsito:</p>
<ul>
	<li>(i) Não uso do capacete ou uso inadequado do capacete;</li>
	<li>(ii) Não uso do cinto de segurança ou não uso de proteção para crianças;</li>
	<li>(iii) Exceder velocidade e</li>
	<li>(iv) Beber e dirigir.</li>
</ul>
<p>Em alguns documentos da Organização, também se começa a chamar a atenção para a "direção distraída" associada ao uso do celular como um fator de risco emergente.</p>
<p>Em seu principal mapeamento do estado da arte da segurança viária no mundo, o “Global Status Report on Road Safety” (OMS, 2015), a OMS estabelece os critérios para avaliar se um país conta com legislação adequada de segurança no trânsito nesses fatores de risco.</p>
<h6>a.	Capacete</h6>
<p>No uso de capacete, a OMS aponta como adequada a previsão de obrigatoriedade para todos usuários que podem trafegar em uma motocicleta, bem como o estabelecimento de padrões de capacete a serem considerados como aptos à promoção da segurança.</p>
<p>O CTB disciplina o tema, trazendo a obrigatoriedade de tal uso para condutores de motocicletas e passageiros, em seus artigos 54 e 55. Já o artigo 244 estabelece a infração gravíssima para o descuprimento daqueles. Estes dispositivos foram regulamentados pela Resolução nº 453 de 2013 do CONTRAN que, entre outros aspectos, estabelece os padrões de capacete aceitos em território nacional.</p>

<h6>b.	Velocidades urbanas</h6>
<p>Quanto às velocidades, a recomendação para as legislações nacionais é de que prevejam velocidades em vias urbanas iguais ou menores que 50 km/h. Como se verá abaixo, este é o único critério em que o Brasil não recebeu nota máxima na avaliação de legislação, tendo em vista que o CTB, em seu artigo 61, estabelece velocidades máximas de até 80 km/h com possibilidade de aumento ou diminuição por meio de ato do órgão de trânsito local.</p>
<h6>c.	Beber e dirigir</h6>
<p>No que diz respeito ao uso do álcool e direção, a entidade orienta que o mais adequado é ter legislações que proíbem a direção sob uso do álcool em patamares iguais ou maiores que 0,05 g/dL para motoristas experientes (mais de dois anos de habilitação) e 0,02g/dL para motoristas inexperientes e/ou jovens.</p>
<p>A legislação brasileira não estabelece a diferenciação de patamares como aceito pela OMS, sendo ainda mais rigorosa que tal recomendação, conforme descrito no artigo 276 do CTB. Recentemente, em 2016, foi acrescido ao CTB o artigo 165-A que, complementando o já previsto no artigo 165, aplica as mesmas sanções administrativas previstas aos condutores flagrados sob a influência do álcool àqueles que se recusarem a prestar o teste clínico.</p>
<p>Para além das sanções administrativas, em determinadas circunstâncias, previstas nos artigos 291, 302, 303 e 306 do Código, haverá consequências criminais para a associação de direção e uso de álcool e demais substâncias entorpecentes.</p>

<h6>d.	Dispositivos de retenção: cinto de segurança e "cadeirinha"</h6>
<p>Por fim, a existência de leis que estabelecem o uso obrigatório de cinto de segurança em todos os assentos é o parâmetro para esse fator de risco. Já no que diz respeito aos dispositivos de retenção de bebês e crianças, recomenda-se a proibição de crianças no assento dianteiro e a existência de diferenciação de tipos de dispositivos de proteção a depender do tamanho e idade das crianças e bebês.</p>
<p>A legislação brasileira, especificamente os artigos 64, 65, 105,167 e 168 do CTB, trazem as obrigações e as respectivas infrações relacionadas a esse fator de risco. Adicionalmente, a Resolução nº 277 de 2008 do Contran detalha os parâmetros a serem observados no transporte de crianças menores de 10 (dez) anos, diferenciando os requisitos de segurança por faixa etária da criança, alinhada à recomendação internacional.</p>
<p>Dentre os dez países mais populosos do mundo, o Brasil se destaca como o mais aderente às melhores práticas de legislação no trânsito internacionais, cobrindo quatro dos cinco fatores de risco (OMS, 2015). A única exceção, como mencionado acima, se refere à legislação sobre velocidade (quadro abaixo).</p>
<slot name='t18'></slot>
<h5>4.	Velocidades máximas no município de São Paulo</h5>
<p>O excesso de velocidade é uma das principais causas de acidentes e mortes no trânsito, sendo um problema de abrangência mundial. Pesquisa realizada em 2008 pela Autostrade per I’Ilália, concessionária responsável pela administração de maior parte das rodovias italianas, mostrou que mais de 60% das mortes nas estradas da Itália ocorrem devido ao excesso de velocidade.</p>
<p>Em relação a atropelamentos, de acordo com a WRI Brasil, uma redução de 5% na velocidade média pode resultar em 30% menos ocorrências fatais.<a title="  Disponível em: http://wricidades.org/research/publication/impactos-da-redu%C3%A7%C3%A3o-dos-limites-de-velocidade-em-%C3%A1reas-urbanas. Acesso em 09/10/2018." href='http://wricidades.org/research/publication/impactos-da-redu%C3%A7%C3%A3o-dos-limites-de-velocidade-em-%C3%A1reas-urbanas' style='cursor: help;' target="_blank"><sup>43</sup></a></p>
<slot name='t19'></slot>
<p>A relação entre o número e a gravidade dos atropelamentos com a velocidade se evidencia na medida em que o aumento da velocidade proporciona maior dificuldade para controlar o veículo, demanda mais espaço disponível e menor tempo de reação para realizar manobras de desvio ou de frenagem do carro. Além disso, quanto mais rápido se dirige, menor o campo de visão, o que diminui a percepção espacial e dificulta a avaliação do risco e a tomada de decisão. Caso o acidente seja inevitável, seu impacto é maior, agravando as suas consequências. Assim, o monitoramento da velocidade é fundamental para mantê-la em patamares compatíveis com as condições do ambiente e do tráfego, e reduzir os riscos.</p>
<p>O CTB sugere valores de velocidade máxima permitida conforme o tipo de via. Porém, esta sugestão baseia-se na grande diversidade de situações existentes no país; assim, o CTB permite que o órgão com jurisdição sobre a via adote valores de velocidade máxima permitida diferentes dos sugeridos no Artigo 61, § 2º:</p>
<p class="quotation">
	Art. 61. A velocidade máxima permitida para a via será indicada por meio de sinalização, obedecidas suas características técnicas e as condições de trânsito.<br />
	§ 1º Onde não existir sinalização regulamentadora, a velocidade máxima será de:<br />
	I - nas vias urbanas:<br />
	a) oitenta quilômetros por hora, nas vias de trânsito rápido:<br />
	b) sessenta quilômetros por hora, nas vias arteriais;<br />
	c) quarenta quilômetros por hora, nas vias coletoras;<br />
	d) trinta quilômetros por hora, nas vias locais;<br />
	II - nas vias rurais:<br />
	a) nas rodovias:<br />
	1) cento e dez quilômetros por hora para automóveis e camionetas;<br />
	2) noventa quilômetros por hora, para ônibus e microônibus;<br />
	3) oitenta quilômetros por hora, para os demais veículos;<br />
	b) nas estradas, sessenta quilômetros por hora.<br />
	§ 2º O órgão ou entidade de trânsito ou rodoviário com circunscrição sobre a via poderá regulamentar, por meio de sinalização, velocidades superiores ou inferiores àquelas estabelecidas no parágrafo anterior.
</p>
<p>A determinação da velocidade máxima permitida em uma via leva em consideração a geometria viária, ligações estabelecidas e o uso e ocupação do solo, o que determina a sua classificação viária. Em São Paulo, a classificação é definida na Portaria DSV 021/02, na qual as vias do município são classificadas em: (i) vias de trânsito rápido; (ii) vias arteriais I, II e III; (iii) vias coletoras I e II; e (iv) vias locais. A classificação segue os seguintes parâmetros:</p>
<slot name='tabela20'></slot>
<p>Os valores típicos de velocidade máxima permitida apresentam variações e restrições pontuais para valores menores perante a existência de áreas escolares, curvas acentuadas, concentração de comércio e serviços, etc.</p>
<p>Em consonância com o Código de Trânsito Brasileiro de 1997 e a Portaria DSV 021/02, a CET adotou os seguintes valores de velocidade máxima permitida em 2002:</p>
<ul>
	<li>Vias de trânsito rápido: 90 km/h;</li>
	<li>Vias arteriais tipo I (com canteiro central): 70 km/h;</li>
	<li>Vias arteriais tipo II (sem canteiro central): 60 km/h;</li>
	<li>Vias arteriais tipo III (pista simples): 60 km/h;</li>
	<li>Vias coletoras I e II: 40 km/h;</li>
	<li>Vias locais: 30 km/h.</li>
</ul>
<p>A partir de 2010, em consonância com os limites de velocidades propostos pela Organização Mundial da Saúde, passou-se a proceder à redução da velocidade máxima permitida nas vias arteriais para o valor de 50 km/h, visando a redução significativa dos conflitos de deslocamento dos veículos, cuja segurança está relacionada diretamente com os tempos de percepção e reação dos motoristas, tempos estes relacionados à frenagem e à aceleração dos veículos.</p>
<p>A diminuição da velocidade proporciona tempos melhores de percepção e reação, e exige distâncias menores para essas manobras, o que diminui a probabilidade de impacto, a formação de “ondas” no tráfego e a intensidade e a frequência dos conflitos de troca de faixas e de acessos, provocando a harmonizando do tráfego, inclusive nas ligações entre vias.</p>
<p>O sistema arterial possui hoje um valor padronizado em 50 km/h. Valores superiores são encontrados somente em vias de trânsito rápido, e valores menores em vias coletoras e locais. Desta forma, reduz-se a frequência e intensidade dos conflitos veiculares de deslocamento, proporcionando uma melhor correlação entre a função da via e o uso e ocupação do solo.</p>
<p>Ademais, conforme já explicitado no Eixo III, destacam-se as áreas de velocidade reduzida implantadas na cidade, composta por um conjunto viário sinalizado de maneira a deixar clara e destacada a regulamentação da velocidade em no máximo 40 km/h ou 30 km/h conforme o caso.</p>

<h5>5.	Fiscalização da velocidade pela média do trecho</h5>
<h6>a.	Contextualização</h6>
<p>O método adotado atualmente no Brasil para fiscalização de velocidade utiliza a monitoração da velocidade instantânea praticada no ponto da via onde o equipamento está instalado. Aos motoristas observadores da lei e normas de trânsito, este método possui efeito educativo e de reforço de atitudes saudáveis e seguras no trânsito. Mas, por outro lado, os infratores contumazes apenas diminuem a velocidade na aproximação do local fiscalizado e, ao ultrapassá-lo, voltam a desenvolver altas velocidades na via.</p>
<p>Este tipo de reação pode provocar situações inseguras próximas ao ponto de fiscalização. Estas constatações levaram à criação de outro método de fiscalização eletrônica de velocidade: o monitoramento da velocidade dos veículos pela média desenvolvida em um trecho. Esta técnica força os motoristas mais apressados a manterem uma velocidade abaixo ou dentro dos limites máximos estabelecidos.</p>
<p>Na União Europeia, por exemplo, o método adotado por todos os países membros em 2018 consta de dois ou mais pontos com leitores de OCR (Optical Character Recognition) ou LAP (Leitor Automático de Placas, que reconhece os caracteres das placas) posicionados no trecho fiscalizado, conforme mostra a figura abaixo:</p>
<slot name='f22'></slot>
<p>O funcionamento do sistema é bastante simples, pois basta que seja efetuada a leitura da placa do veículo em dois pontos distintos, dos quais se conhece a distância exata entre eles. O equipamento mede o tempo de percurso do referido veículo no trecho em questão e compara com o tempo previsto, se o veículo mantivesse, no máximo, a velocidade regulamentada do trecho. Caso o tempo medido seja menor que o tempo previsto, constata-se o cometimento da infração no trecho fiscalizado, o que acarreta o consequente registro de sua imagem para fins de penalização.</p>
<p>Este método de fiscalização pela média também pode coexistir com pontos de fiscalização por velocidade instantânea, fixos, estáticos ou móveis; aprimorando a eficiência do sistema e tornando-o uma ferramenta adicional de fiscalização.</p>
<p>Portugal regulamentou a fiscalização de velocidade pela média de forma clara e objetiva, no Artigo 27° - Limites Gerais de Velocidade, 4º parágrafo, do Código da Estrada:</p>
<p class="quotation">
	“4º - Para os efeitos do disposto nos números anteriores, considera-se que viola os limites máximos de velocidade instantânea o condutor que percorrer uma determinada distância a uma velocidade média incompatível com a observância daqueles limites, entendendo-se que a contra-ordenação é praticada no local em que terminar o percurso controlado.”<a title="   Código da Estrada. Disponível em http://www.ansr.pt/SegurancaRodoviaria/CodigoDaEstrada/Documents/Codigo_Estrada_2014_versaoWEB.pdf. Acesso em 19/06/2018" href='http://www.ansr.pt/SegurancaRodoviaria/CodigoDaEstrada/Documents/Codigo_Estrada_2014_versaoWEB.pdf' style='cursor: help;' target="_blank"><sup>44</sup></a>
</p>
<p>Os critérios portugueses para a escolha dos trechos fiscalizados pelo sistema, pela ordem de importância, são: (i) índice de sinistralidade; (ii) tipos de sinistralidade e distribuição de velocidades e (iii) potencial de gravidade dos acidentes.</p>
<p>No Brasil, a implantação da fiscalização pela velocidade média por trecho exige ainda uma regulamentação específica, visto que o motorista será autuado não pelo excesso pontual (local), mas pelo ocorrido em um ou mais segmentos da via não identificados diretamente pelos equipamentos.</p>
<p>É importante ressaltar que a fiscalização por velocidade média em um trecho não implica em anular a fiscalização pontual. Pelo contrário: a utilização conjunta reforça ao condutor a necessidade de seguir a lei. Sua utilização também não retira a necessidade da fiscalização pontual antes de elementos perigosos na via como, por exemplo, curvas acentuadas, travessias de pedestres, cruzamentos em nível, etc.</p>
<div style="border: 1px solid black; padding: 1em;">
	<strong>O exemplo de Viena</strong>
	<p>Um exemplo bastante elucidativo sobre o salto de eficiência da fiscalização e redução de acidentes proporcionado pelo sistema é o que ocorreu no túnel Kaisermuhlen, em Viena, Áustria. O túnel é uma ligação urbana com seções separadas para cada direção de tráfego, com 3 a 4 faixas de rolamento em cada sentido, e rampas de acesso e saída dentro dos túneis.</p>
	<p>O túnel possui limites de velocidades distintos: 80 km/h para veículos de passeio e leves, motocicletas e ônibus, e 60 km/h para veículos pesados (acima de 7,5 toneladas). No primeiro ano de operação foi registrada uma redução na velocidade média em mais de 10 km/h. A mobilidade tradicional e a vigilância de velocidade estática (em uso antes da operação do controle de trecho) mostraram a velocidade média de todos os veículos em 85 km/h; este valor diminuiu para 70 km/h rapidamente após a introdução do sistema. Nova medição após um período de 6 meses revelou que a velocidade média nesta seção da rodovia tem se estabilizado em 75 km/h para os veículos leves, e 55 km/h para os pesados (HGV).</p>
	<slot name='g30'></slot>
	<p>Já nos primeiros 2 anos de operação o impacto positivo do Controle de Trecho relativo aos acidentes foi observado. Os impactos na redução de acidentes, segundo o Vienna Municipal Department, foram de -33,3% para acidentes com vítimas; -48,8% nos com vítimas graves e fatais e -32,2%  para os com vítimas leves.</p>
</div>
<h6>b.	A fiscalização pela velocidade média em São Paulo</h6>
<p>Os contratos de fiscalização eletrônica efetuados pela CET desde 2014 já contemplam a modalidade de fiscalização de velocidade pela média no trecho. Todos os equipamentos implantados estão habilitados para esta modalidade, visto que possuem Leitor Automático de Placas (LAP), e enviam os dados on-line para as centrais de controle. O sistema de controle e  gerenciamento dos dados possui as funções necessárias em sua programação, bastando se determinar os parâmetros básicos para iniciar esta fiscalização: equipamentos envolvidos, distâncias exatas, sincronismo de relógios apurado, etc.</p>
<p>Em 1º de novembro de 2017, a CET iniciou a fiscalização pela velocidade média em quatro trechos. Na primeira semana de operação, o sistema flagrou mais de 53 mil motoristas (média de 9 mil por dia) que excederam a velocidade média nos trechos monitorados, sem exceder a velocidade pontual nos pontos de fiscalização.</p>

<h5>6.	Fiscalização ostensiva: panorama geral</h5>
<p>A fiscalização de trânsito é um dos elementos primordiais à segurança viária. No município de São Paulo, ela é realizada pelos agentes da polícia Militar  e da  GCM por meio de convênio  e pelos agentes SPTrans, e CET além dos equipamentos de fiscalização eletrônicos existentes na cidade. Conforme se verifica no gráfico abaixo, a maioria das autuações é efetuada por equipamentos de fiscalização eletrônica.</p>
<p>A fiscalização de trânsito ostensiva é um dos elementos primordiais à segurança viária. No município de São Paulo, ela é realizada pelos agentes do CPTran, CET/DSV, GCM e SPTrans, para além dos equipamentos de fiscalização existentes na cidade. Conforme se verifica no gráfico abaixo, a maioria das autuações é efetivada por equipamentos de fiscalização.</p>
<slot name='g31'></slot>
<p>Pelas características do município de São Paulo, a maior metrópole do Brasil e que conta com mais de 17.000 km de vias e frota de mais de 8 milhões de veículos, o exercício da fiscalização ostensiva é desafiador. Uma pesquisa realizada pela CET em 2015 estimou que apenas 1 a cada 4.416 infrações conseguem ser fiscalizadas, o que revela a necessidade de fortalecimento da capacidade operacional fiscalizatória, associada a campanhas voltadas à mudança de comportamento. </p>
<p>Nos últimos anos, o número de autuações lavradas têm diminuído, tanto aquela realizada por agentes, quanto a por equipamentos de fiscalização.</p>
<slot name='g32'></slot>
<slot name='g33'></slot>
<p>Muitos são os motivos que podem estar reduzindo o número de autuações, tais como o acalmamento de tráfego que tem sido realizado nos últimos anos pela Prefeitura, que reduz os tempos de reação e alteram o comportamento dos condutores, o fortalecimento de sinalização próximo a equipamentos com maiores números de autuações, o reconhecimento pelos condutores dos pontos de fiscalização, entre outros. </p>
<p>Porém, apesar das múltiplas causas, pode-se verificar como elemento prioritário o aumento do rigor das penalizações previstas no CTB a partir de 01 novembro de 2016. Entre outras alterações, destacam-se:</p>
<ul>
	<li>As multas gravíssimas passaram de R$191,54 para R$293,47 (aumento de 53%); </li>
	<li>As graves, de R$127,69 para R$195,23 (aumento de 52,8%);</li>
	<li>As médias, de R$85,13 para R$130,16 (aumento de 52,8%);</li>
	<li>As leves, de R$53,20 para R$88,38 (aumento de 66%);</li>
	<li>Estacionar o veículo nas vagas reservadas às pessoas com deficiência ou idosos, sem credencial que comprove tal condição, passou de leve para gravíssima;</li>
	<li>Dirigir o veículo segurando ou manuseando o celular passou de média para gravíssima.</li>
	<li>O período de suspensão mínima passou de 1 para 6 meses.</li>
</ul>
<p>As 20 principais autuações lavradas no município de São Paulo em 2017 correspondem a mais de 90% das aproximadamente 13,5 milhões de autuações. São elas:</p>
<slot name='t21'></slot>
<p>Importante destacar que, em 2017, do total de 8,6 milhões de veículos que compõem a frota de São Paulo, 69,69% não receberam nenhuma autuação, enquanto que apenas 30,31% foram autuados. Entre estes, 39,78% receberam uma multa; 21,72%, duas; 12,58%, três e 25,92% mais de três.</p>
<p>Abaixo, segue o panorama da fiscalização por autoridade fiscalizatória.</p>
<h6>a.	Comando de Policiamento de Trânsito (CPTran)</h6>
<p>O Comando de Policiamento de Trânsito (CPTran) foi recriado em 27 de abril de 2010, com a atribuição de executar o policiamento de trânsito urbano e atuação complementar e de apoio às atividades de polícia ostensiva e de preservação da ordem pública na capital e pela fixação e difusão de doutrina nas questões afetas ao trânsito urbano, bem como, supletivamente, no território estadual.</p>
<p>Ao Comando de Policiamento de Trânsito (CPTran), subordinam-se as seguintes Unidades de Policiamento de Trânsito, sediadas na capital, que atuam em suas respectivas áreas territoriais, a seguir especificadas:</p>
<p>1° Batalhão de Polícia de Trânsito (1° BPTran): Zonas Centro, Sul, Sudoeste e Oeste da Capital, excetuando-se as Marginais Tietê e Pinheiros; e</p>
<p>2° Batalhão de Polícia de Trânsito (2° BPTran): Zonas Norte, Leste e Sudeste da Capital e nas Marginais Tietê e Pinheiros.</p>
<p>A atuação se dá por meio de diferentes operações:</p>
<p>Operação Visibilidade: intensificação do policiamento ostensivo de trânsito, por meio do estacionamento de viaturas nos horários de “rush”, nos principais cruzamentos da cidade de São Paulo, selecionados estrategicamente com base em indicadores criminais e de acidentalidade, com o objetivo de coibir atos relacionados com a segurança pública e garantir o cumprimento das normas relacionadas à segurança no trânsito, a fim de garantir a livre circulação e evitar acidentes,  aumentando a sensação de segurança dos usuários das vias, auxiliando a travessia de pedestres e o controle do tempo semafórico, quando necessário.</p>
<p>Operação Direção Segura (ODS): operação de fiscalização desenvolvida por meio de bloqueios de trânsito com vistoria seletiva de veículos, voltada à atividade de fiscalização de trânsito, com ênfase na identificação de condutores suspeitos de dirigir sob a influência de álcool ou substância psicoativa que determine dependência, com uso de equipamento específico de teste de ar alveolar “etilômetro”, bem como outras ações básicas do policiamento ostensivo.</p>
<p>Operação Direção Segura Integrada (ODSI): ação integrada entre diversos Órgãos do Estado (Polícia Militar, Polícia Civil, Polícia Técnico-científica, DETRAN/SP, Secretarias da Saúde, Educação e Comunicação Social) com o objetivo de realizar o ciclo completo de fiscalização a motoristas que dirigem sob influência de álcool, visando proporcionar maior segurança aos usuários do sistema viário e promovendo o cumprimento da lei.</p>
<p>Operação de Fiscalização de Motocicletas - Cavalo de aço: tem o objetivo de intensificar a fiscalização de motocicletas e dos seus ocupantes nas principais vias da capital, por meio de bloqueios de trânsito (direto e indireto) ou cerco e retirada (“pinçamento”), de forma a garantir o cumprimento das normas relacionadas à segurança no trânsito, prevenir acidentes e inibir o cometimento de ilícitos penais, aumentando com isso a  sensação de segurança dos usuários da via e a consequente redução dos índices criminais, retirando das vias veículos irregulares, utilizando, para tanto, da legislação específica e das técnicas de policiamento de trânsito. Em 2017, foram efetuadas 3.727 operações, que fiscalizaram 106.672 motocicletas, entre as quais 14.289 foram removidas.</p>
<p>Operação de Fiscalização de Veículos de Transporte de Carga: operação que tem o objetivo de intensificar a fiscalização dos veículos utilizados no transporte rodoviário de cargas, a fim de coibir atos relacionados com a segurança pública, em especial o roubo de carga, e garantir o cumprimento das normas relacionadas à segurança no trânsito e evitar acidentes.      </p>
<p>Operação de Fiscalização do Transporte Rodoviários de Produtos Perigosos: tem o objetivo de intensificar a fiscalização dos veículos utilizados no transporte rodoviário de produto perigosos, contemplando tanto as atribuições previstas pelo Decreto Federal n° 96.044/88 (Regulamento para o Transporte de Produtos Perigosos), como o preceituado na legislação e regulamentação municipais, podendo ser realizada de forma conjunta, planejada e programada com o órgão executivo de trânsito do município.</p>
<p>Operação de Fiscalização do Transporte Individual e Coletivo de Passageiros: tem por objetivo auxiliar os fiscais das Empresas de Transportes - Empresa Metropolitana de Transportes Urbanos (EMTU), São Paulo Transportes (SPTrans) e Agência Nacional de Transportes Terrestres (ANTT) - a fiscalizar a exploração da malha viária pelos veículos de transporte individual e coletivo de passageiros da Grande São Paulo e da capital, coibindo o exercício clandestino da atividade. A atuação dos policiais militares nessa operação limita-se à abordagem dos veículos, realização de busca pessoal, vistoria no interior do veículo, quando houver fundada suspeita, e verificação do cumprimento às normas relacionadas à legislação de trânsito.</p>
<p>Operação de Fiscalização do Transporte de Escolares: operação que tem o objetivo de intensificar a fiscalização dos veículos utilizados no transporte de escolares, sobretudo, nos horários de entrada e saída de alunos nos estabelecimentos de ensino, por meio de bloqueios de trânsito (direto e indireto) ou cerco e retirada (“pinçamento”). A fiscalização consiste na verificação da documentação de porte obrigatório dos veículos e dos seus condutores, dos equipamentos obrigatórios e da verificação do estado de conservação dos veículos, com o objetivo de proporcionar mais segurança aos alunos que utilizam este serviço.</p>
<p>Operação Volta às Aulas: tem o objetivo de intensificar o policiamento ostensivo de trânsito nas imediações das escolas públicas, ao término do período das férias escolares, a fim de mitigar eventuais impactos à segurança e fluidez do trânsito, orientando a travessia de pedestres, disciplinando o embarque e o desembarque de alunos, garantindo e facilitando o acesso às escolas, além de coibir a formação de filas duplas e o estacionamento irregular.</p>
<p>Operação Mau Estado de Conservação e Segurança (MECS): operação desenvolvida por meio de bloqueios de trânsito com vistoria seletiva de veículos, voltada à atividade de fiscalização de trânsito com o objetivo de retirar de circulação aqueles veículos que são flagrados em mau estado de conservação, comprometendo a segurança.</p>
<h6>b.	DSV/CET</h6>
<p>A autoridade municipal de trânsito no Município de São Paulo é Diretor do Departamento do Sistema Viário a sua execução. Este Departamento, à sua vez, por meio da Secretaria, celebra contrato com a Companhia de Engenharia de Tráfego (CET), empresa municipal competente para gerir o trânsito na cidade, para que esta implemente as ações necessárias à operação, educação e fiscalização do trânsito na capital paulista.</p>
<p>As infrações de trânsito são constatadas por meio de duas principais formas de fiscalização realizadas pela CET: por agentes de trânsito em campo e por equipamentos de fiscalização eletrônica.</p>
<p>A primeira se dá por meio das operações da empresa. Já a segunda ocorre com auxílio de aproximadamente 890 equipamentos de fiscalização eletrônica instalados na capital.</p>
<p>A fiscalização realizada pelos agentes de trânsito ocorre como atividade adicional ao seu papel de operação do trânsito. Ou seja, os agentes municipais de trânsito são encarregados de ordenar os fluxos, ajustando dispositivos semafóricos, orientando travessias, entre outras atividades, adicionalmente às quais fiscalizam o comportamento dos condutores no trânsito e, no caso de cometimento de infrações, realizam autuações.</p>
<p>Atualmente, a CET conta com aproximadamente 1.600 agentes de trânsito que trabalham em 4 turnos de 6h40min, sendo que a operação é contínua (24 horas) e com efetivo reduzido em horários de menor tráfego. Suas principais ações de rotina são: </p>
<p><strong>Rotas operacionais:</strong> tem por finalidade o monitoramento do sistema viário principal, assegurando o melhor desempenho possível quanto às condições de fluidez e segurança das vias operadas, remoção de interferências, fiscalização, interação com a população e atuação em situações emergenciais.</p>
<p><strong>POI - Ponto Operacional Interativo:</strong> tem por finalidade a interação com os usuários da via, tanto pedestres quanto condutores, para assegurar condições de segurança e fluidez, fiscalizar e inibir com sua presença o cometimento de infrações de trânsito, identificar problemas e intervir de imediato para a sua resolução.</p>
<p><strong>POS – Ponto Operacional de Segurança:</strong> plano de fiscalização com enfoque voltado para a segurança dos usuários. Os locais são definidos a partir de dados estatísticos de acidentes com vítimas fatais decorrentes de colisões ou atropelamentos.</p>
<p><strong>Operação em eventos:</strong> tem por finalidade planejar e executar operação de trânsito nas demandas não rotineiras, decorrentes de eventos que geram impacto sobre a via pública, podendo ser um evento programado ou não programado.Nesta atividade, estão incluídos tanto eventos de pequeno porte, que demandam intervenções simples, quanto operações que mobilizam todo o corpo técnico-operacional.</p>
<p><strong>Operação em escolas:</strong> Tem por finalidade o monitoramento do trânsito nas áreas próximas às escolas nos horários de entrada e saída de alunos, agindo sempre de forma proativa para garantir a segurança dos alunos nas travessias, bem como o auxílio no embarque/ desembarque. Os agentes de trânsito atuam também na orientação aos pais para não estacionarem em fila dupla, garantindo assim a fluidez dos veículos.</p>
<p><strong>Operação em transporte de cargas especiais:</strong> tem por finalidade o planejamento e o acompanhamento dos deslocamentos dos veículos que transportam cargas superdimensionadas ou produtos perigosos na Cidade de São Paulo. A CET possui uma equipe especializada para desenvolver estudos, analisar viabilidades e, sendo possível, acompanhar o deslocamento, tomando todas as providências para que não ocorram danos à via nem ao mobiliário urbano.</p>
<p><strong>Operação Greve nos transportes públicos:</strong> tem por finalidade o planejamento de um conjunto de ações para adequar e intensificar as atividades de operação de campo nos principais corredores, cruzamentos, terminais, estações e pontos de embarque em caso de paralisação parcial ou total do sistema público de transportes (ônibus, metrô e/ou trens).</p>
<p><strong>Operação enchente:</strong> tem por finalidade o planejamento e a operação do sistema viário nas áreas afetadas por vias alagadas, estabelecendo rotas e caminhos alternativos para assegurar a mobilidade de bens e pessoas com segurança.</p>
<p><strong>Operação de fiscalização:</strong> tem por finalidade assegurar o cumprimento das normas de trânsito através de operações dedicadas. Dentre elas podemos citar:</p>
<p><strong>Fiscalização Zona Azul:</strong> executa a fiscalização nas vagas de estacionamento rotativo, coibindo dessa forma o estacionamento irregular nas vagas.</p>
<p><strong>Fiscalização de obras:</strong> executa a fiscalização de ocupações por obras e serviços na via pública, sejam elas autorizadas através de documento específico, emergenciais ou não autorizadas, visando sempre garantir o atendimento à segurança e à mobilidade viária.</p>
<p>As 40 principais autuações lavradas em 2017 concentram 95% do total. São elas:</p>
<slot name='t22'></slot>
<p>O número de autuações de cada tipo depende consideravelmente das condições de verificação e comprovação do cometimento de cada tipo de infração. Existem basicamente duas variáveis que influenciam na verificação e comprovação do cometimento das infrações: </p>
<ul>
	<li>as cometidas com o veículo em movimento e </li>
	<li>as cometidas com o veículo estacionado. </li>
</ul>
<p>Ao comparar as duas situações, percebe-se que as autuações feitas em veículos estacionados tendem a ter uma fiscalização mais efetiva, uma vez que o Agente de Trânsito se depara com a ausência do condutor para sanar a irregularidade.</p>
<p>Já em relação às infrações em movimento, observa-se comumente duas situações:</p>
<ul>
	<li>a que o Agente não está presente, e nesse caso não existe a fiscalização; e</li>
	<li>a que o Agente está presente e inibe o cometimento da infração. </li>
</ul>
<p>Somente quando o infrator não respeita a presença do Agente é que ocorre a atuação. Uma fiscalização de respeito à travessia de pedestre, por exemplo, que está relacionada com muitas infrações com o veículo em movimento, é mais dificilmente verificável, pelas razões expostas anteriomente. Diante desses obstáculos, este plano propõe como ação a busca de tecnologia de fiscalização com prioridade ao pedestre, bem como mecanismo de fiscalização remota.</p>
<p>Ao mesmo tempo, desde 2011 a CET desenvolve projetos e ações específicas nas quais os agentes de trânsito dedicam-se exclusivamente à fiscalização de infrações de usuários vulneráveis, voltando-se à promoção dedicada da segurança no trânsito. Um importante exemplo dessas ações é o POS (Programa Operacional de Segurança). O programa redireciona os recursos humanos a corredores de transporte com alto volume de atropelamentos, baseando-se nos dados de acidentes do período imediatamente anterior.</p>
<p>O POS trabalha com 23 enquadramentos prioritários, divididos em enquadramento relacionados direta ou indiretamente com a segurança dos usuários da via:</p>
<strong>GRUPO PRINCIPAL:</strong>
<ul>
<li>545-21 Estacionar no passeio/calçada;</li>
<li>545-22 Estacionar sobre faixa destinada a pedestre;</li>
<li>562-21 Parar no passeio/calçada;</li>
<li>562-22 Parar sobre faixa destinada a pedestres;</li>
<li>521-51 Dirigir ameaçando os pedestres que estejam atravessando a via pública;</li>
<li>567-31 Parar sobre faixa de pedestre na mudança de sinal luminoso;</li>
<li>581-91 Transitar em calçadas, passeios;</li>
<li>612-20 Deixar de dar preferência a pedestre/veículo não motorizado na faixa a ele destinada;</li>
<li>613-00 Deixar de dar preferência a pedestre/veículo não motorizado que haja concluído a travessia;</li>
<li>616-50 Deixar de dar preferência a pedestre/veículo não motorizado atravessando a via transversal.</li>
</ul>
<strong>SEGUNDO GRUPO:</strong>
<ul>
<li>584-33 Deixar de indicar com antecedência, mediante gesto de braço/luz indicadora, mudança direção;</li>
<li>593-20 Ultrapassar pela contramão nas faixas de pedestres;</li>
<li>601-75 Executar operação de retorno passando por cima de faixa de pedestres;</li>
<li>605-01 Avançar o sinal vermelho do semáforo;</li>
<li>614-90 Deixar de dar preferência a pedestre portador de deficiência física/ crianças, idoso e gestante;</li>
<li>615-70 Deixar de dar preferência a pedestre/ veículos não motorizados quando iniciada travessia sem sinalização;</li>
<li>626-20 Deixar de reduzir a velocidade quando se aproximar de passeata/ aglomeração/ desfile, etc;</li>
<li>639-41 Deixar de reduzir a velocidade nas aproximações de escolas;</li>
<li>639-43 Deixar de reduzir a velocidade nas aproximações de estações embarque/ desembarque;</li>
<li>639-44 Deixar de reduzir veloc onde haja intensa movimentação de pedestres;</li>
<li>736-62 Dirigir veículo utilizando-se de telefone celular;</li>
<li>763-31 Dirigir veículo segurando telefone celular;</li>
<li>763-32 Dirigir veículo manuseando telefone celular;</li>
</ul>
<p>Foi criada por Ato do Presidente da CET a Comissão Permanente de Fiscalização de Trânsito, responsável pela elaboração de Procedimentos de Fiscalização. A comissão reúne técnicos das áreas que realizam Fiscalização, Central, Treinamento, Chefia de Gabinete da Presidência e Diretoria de Operações. Para fortalecimento da proteção ao pedestre, a comissão já elaborou procedimentos de fiscalização para os 23 enquadramentos prioritários.</p>
<p>Outra fiscalização prioritária é sobre o uso de vagas reservadas para idosos e pessoas com deficiência, decorrente da alteração das regras do CTB, que passou a impor multa, com alteração da tipologia de infração para gravíssima, a veículos não credenciados com o Cartão Defis e/ou Cartão Idoso estacionados em vagas reservadas para pessoas com deficiência e idosos em locais privados, mas de uso coletivo, como shoppings, mercados, igrejas, casas de espetáculos e estabelecimentos comerciais em geral.</p>
<p>O trabalho de fiscalização por meio de agentes de trânsito, embora altamente eficiente, não é capaz de ordenar e cobrir toda a demanda existente em uma cidade com mais 17.000km de vias e mais de 8.000.000 de veículos circulantes. Por essa razão, em 2017, apenas aproximadamente 25% das infrações decorreram de autuações manuais, enquanto 75% advieram de mecanismos automatizados de fiscalização.</p>
<p>A fiscalização fotográfica eletrônica é um dos mais importantes instrumentos da gestão da segurança viária. Entre 1997, quando foram implantados os primeiros equipamentos, e 1998, o número de óbitos em ocorrências de trânsito caiu de 2.042 para 1.558, uma redução de 24% em apenas um ano.</p>
<p>A fiscalização no Município de São Paulo por meio de dispositivos é efetuada atualmente por meio de 890 equipamentos. Esses dispositivos diferem em tipo, forma e infrações que estão aptos a constatar, mas, em geral, sua utilização é destinada a fiscalizar desrespeitos aos limites de velocidade, o rodízio e outras restrições de circulação, a desobediência ao semáforo vermelho e cruzamentos, bem como conversões proibidas e outras infrações autorizadas pelo DSV.</p>
<p>Adicionalmente aos dispositivos instalados em pontos da cidade, a CET possui 7 equipamentos portáteis que são prioritariamente utilizados para fiscalização de velocidade de motocicletas em locais estratégicos relativos à segurança viária.</p>
<p>A definição dos locais de instalação desses equipamentos leva em conta a necessidade de ordenar o tráfego e melhorar a segurança dos usuários da via nos pontos críticos da cidade, por isso, através de estudos detalhados e de acordo com as leis e normas vigentes eles são alocados em corredores e cruzamentos importantes da capital. A implantação de equipamentos que fiscalizam a velocidade, por exemplo, devem obedecer aos requisitos previstos na Resolução 396/2011 do CONTRAN e seus parâmetros de confiabilidade devem estar atestados conforme determina a Portaria 544 do INMETRO.</p>

<h6>c.	GCM</h6>
<p>A competência das Guardas Municipais na fiscalização do trânsito foi estabelecida pela Lei nº 13.022/2014 (estatuto das Guardas Municipais), com atuação nas vias e logradouros municipais, ou de forma concorrente mediante convênio celebrado com órgão de trânsito estadual ou municipal, respaldado nos termos do artigo 25 do CTB.</p>
<p>Com a celebração de convênio entre a Secretaria Municipal de Segurança Urbana e a Secretaria de Mobilidade e Transportes, em 27 de outubro de 2014, a GCM passou a exercer as atividades de fiscalização de trânsito contidas no artigo 24, incisos VI, VIII e XVII do CTB, de forma concomitante com os agentes de trânsito do município.</p>
<p>A Divisão de Trânsito (DITRAN) da GCM, criada pelo Decreto Municipal nº 58.199/2018, em coordenação com a Autoridade Municipal de Trânsito, tem as seguintes atribuições:</p>
<p class="quotation">
I- Coordenar o exercício regular de poder de polícia de trânsito pelos membros da Guarda Civil Metropolitana;
<br />
II- Monitorar e avaliar as ações de orientação e fiscalização de trânsito;
<br />
III- Sistematizar e encaminhar para a autoridade municipal de trânsito as autuações por infração de trânsito oficiadas por membros da Guarda Civil Metropolitana.
</p>
<p>Dessa forma, a GCM, concomitante à CET e ao CPTRAN, também é competente para fiscalizar e realizar autuações de trânsito na capital em concomitância com suas atribuições de segurança pública. Em consonância com o advento da DITRAN, poderá ser expandida sua atuação com foco nas áreas periféricas, além de celebração de parcerias para operações no sistema viário, em grandes eventos, e apoio ao DTP, realizando a fiscalização de velocidade de motocicletas juntamente à CET.</p>

<h6>d.	SPTrans e DTP</h6>
<p>A fiscalização da SPTrans sobre o sistema de ônibus municipais se dá pelo Centro de Operações (COP) e por agentes em campo. A COP monitora a operação através Sistema de Monitoramento Integrado (SIM), que permite o monitoramento remoto dos ônibus, que possuem GPS e dispositivo que se comunica com a central. Assim, qualquer intercorrência, como acidente ou excesso de velocidade, passa a ser de conhecimento da COP, que aciona os técnicos em campo para exercício da fiscalização.</p>
<p>Os técnicos de transporte da SPTrans fiscalizam os ônibus em campo, realizando diferentes tipos de verificação, como cumprimento de horário de partida ou tráfego de veículo com portas abertas. Além disso, estes servidores possuem também competência para autuar infrações de trânsito relacionadas aos corredores de ônibus, como o tráfego irregular de veículos particulares nas faixas reservadas aos ônibus.</p>
<p>No que se refere à fiscalização dos transportes diferenciados - táxis, motofrete, carga a frete, fretamento e transporte escolar - o Departamento de Transportes Públicos (DTP) possui, de acordo com o Decreto nº 57.867/2017, as atribuições legais de gestão, regulamentação, cadastro, vistoria e fiscalização desses serviços no município de São Paulo. Além disso, é atribuição desse departamento a gestão do contrato de prestação de serviços firmado entre a SMT e a SPTrans. Por meio desse contrato administrativo, a SMT transfere boa parte da execução dessas atribuições à SPTrans. Com isso, a SPTrans é responsável também pelo planejamento e logística da fiscalização sobre os serviços de táxi, transporte escolar, fretamento, motofrete, carga-frete, moto-frete. A empresa realiza a verificação da conformidade dos serviços prestados pelos autorizados, aplicando as penalidades decorrentes de irregularidades constatadas, bem como apreendendo os veículos clandestinos. Com foco na segurança e qualidade da prestação do serviço, é fiscalizada uma frota cadastrada total de 73.894 veículos (maio/2018) e 103.926 condutores ativos. Porém, diferente da fiscalização exercida sobre os ônibus municipais, as demais modalidades não possuem fiscalização remota e os veículos não são equipados com tecnologia AVL.</p>

<h5>7.	Pontos de atenção</h5>
<p>A expansão na fiscalização eletrônica na capital, quase dobrando sua cobertura em poucos anos, como visto no tópico referente à gestão das velocidades, foi um fator determinante na redução de mortes e lesões no trânsito na capital paulista. Porém, é possível verificar certo efeito dissuasivo da autuação por conta do longo lapso temporal entre o cometimento da infração e o recebimento da notificação (que varia entre 12 e 30 dias), assim como a possibilidade de redirecionamento de pontuação para outras CNHs, entre outras falhas no sistema processual.</p>
<p>Esse cenário aponta para a necessidade de reforço e ampliação da prevenção geral e específica por meio de fiscalização ativa, por meio de estratégias de alta visibilidade e abordagem dos infratores. Ele também chama a atenção para a necessidade de aprimoramentos no processo sancionatório decorrente das autuações, recolhimento de veículos, julgamento de recursos, entre outros aspectos que garantam a efetividade da fiscalização.</p>
<p>Entre os pontos de atenção na atividade fiscalizatória, diversos deles encontram-se na efetividade do processo sancionador, tais como a ampliação dos espaços para veículos apreendidos nos pátios públicos, bem como a otimização do processo de leilão dos veículos.</p>
<p>Esse processo já foi em muito auxiliado pela inclusão do §9o ao artigo 328, desvinculando do veículo colocado em hasta pública as dívidas decorrentes de infrações, independentemente de manter ao Poder Público a possibilidade de cobrá-las do infrator pessoalmente. Essa alteração dá mais segurança ao comprador de um veículo em leilões públicos, mas ainda há a necessidade de maior celeridade na realização desses procedimentos.</p>
<p>Destaca-se ainda o processo sancionador excessivamente moroso. Em virtude do grande número de recursos, as instâncias decisórias acabam por tomar muito tempo para chegar a uma decisão administrativa definitiva sobre disputas sobre autuações. Nesse caso, a efetividade dissuasiva é diminuída uma vez que o tempo entre a infração e a aplicação da sanção é muito longo. Um dos exemplos é a existência de inúmeros recursos desnecessários, como de veículos públicos ou privados dispensados do rodízio por razões de interesse público, mas que por falta de implantação de tecnologia adequada, demandam a notificação, o pedido de desconsideração e só então sua liberação da autuação.</p>
<p>Essa e outras melhorias no fluxo processual da atividade fiscalizatória podem ser alcançadas com mecanismos tecnológicos mais coerentes e eficientes, cujos testes e estudos já estão em curso.</p>
<p>Verifica-se também a existência de condutores sem CNH e com CNH cassada, o que aponta à necessidade das práticas fiscalizatórias se adequarem a este cenário. Há uma crescente preocupação com o número de motociclistas jovens (menores de 18 anos) trafegando de motocicleta nos bairros de residência, bem como com o risco adicional a que estão sujeitos os motociclistas com habilitação recém-adquirida (menos de dois anos de experiência). Os dados, ao mostrar condutores de motocicleta menores de 18 anos envolvidos em acidentes, bem como uma significativa concentração de acidentes envolvendo condutores de até 19 anos, reforçam a preocupação e trazem desafios à fiscalização ostensiva, bem como às áreas de educação e comunicação.</p>
<p>Outro tópico é a existência de aplicativos que indicam os locais de fiscalização ostensiva ou eletrônica, muito embora a tecnologia possa ter propiciado melhorias na gestão de tráfego e na qualidade de transportes nos grandes centros urbanos, ela também tem sido utilizada como mecanismo difusor de informações capazes de reduzir o efeito dissuasivo da fiscalização. Ao saber o local e hora exatos da fiscalização estatal, o condutor não se sente compelido a se comportar adequadamente a todo momento, mas apenas naqueles pontos de fiscalização ou mesmo a evitar tais locais.</p>
<p>Essa possibilidade de evadir a fiscalização traz desafios à atividade que visa a prevenir comportamentos inadequados no trânsito, gerando maior necessidade de se utilizar mecanismos inteligentes de alteração de locais, fiscalização preditiva, verificação de velocidade de ponto a ponto, além da premente necessidade de reforço das atividades de comunicação, conscientização e educação no trânsito.</p>
<p>Por fim, há também crescente preocupação com a efetividade das ações fiscalizatórias face aos condutores de automóveis, especialmente aqueles sujeitos à suspensão da habilitação em virtude de condução sob o efeito do álcool. Acredita-se que, por ser desafiador planejar operações que possam abordar automóveis aleatoriamente para verificar a regularidade do veículo e do condutor (como é eficientemente feito com as motocicletas na operação cavalo de aço), condutores com o direito de dirigir suspenso estejam circulando durante o dia (já que à noite estariam mais sujeitos à fiscalização policial nas ODS e ODS-I) de forma irregular, reduzindo drasticamente os efeitos dissuasórios da sanção legal.  </p>

<h5>8.	O controle das velocidades dos ônibus municipais pela SPTrans</h5>
<p>No que se refere à gestão das velocidades dos ônibus municipais, dois pontos merecem destaque. O primeiro é o limite máximo de 50km/h para tráfego dos ônibus e a existência, em 100% da frota, de dispositivo que corta a aceleração do veículo quando este atinge os 50km/h.</p>
<p>O segundo é o controle que a SPTrans faz sobre as velocidades praticadas por meio do Sistema Integrado de Monitoramento (SIM). Sempre que algum ônibus opera em alta velocidade, o sistema gera um alerta à central de operações da SPTrans para que, posteriormente, seja solicitado o tacógrafo do veículo para auditoria das velocidades exercidas. Caso o dispositivo acuse o excesso de velocidade, a empresa operadora é autuada. Ainda sobre os tacógrafos, merece destaque a atual obrigação de que todos os ônibus possuam cronotacógrafo, também chamados tacógrafos digitais</p>
	</div>
</template>

<script>
export default {
	name: 'Cap2CEixoIV'
}
</script>
