<template>
	<div class="Cap2CEixoXI">
<h5>1.	Panorama</h5>
<p>A promoção de uma política de captura e processamento de dados que garanta a sua qualidade para análise das condições de segurança viária é um aspecto crítico para a promoção da segurança viária. A partir dela é possível obter informações valiosas sobre quem são os usuários mais vulneráveis, quais os locais críticos e quando ocorrem os períodos de maior risco de acidentes de trânsito. As melhores práticas para sistemas de dados de segurança viárias incluem:</p>
<ul>
	<li>(i) identificar todas as mortes e a maior parte dos ferimentos causados por acidentes de trânsito;</li>
	<li>(ii) fornecer detalhes sobre o veículo, usuário da via, e o ambiente viário, que permitam identificar causas e fatores contribuintes e desenhar contramedidas;</li>
	<li>(iii) produzir informações de localização precisas e</li>
	<li>(iv) fornecer informações em tempo hábil para subsidiar políticas públicas baseadas em evidência.</li>
</ul>
<p>São Paulo, como grande parte do Brasil, tem uma estrutura complexa de atores policiais e de gestão do tráfego, com diversas autoridades envolvidas no processo de resposta e registro de acidentes de trânsito. Diante dessa complexidade, a CET se concentra em monitorar os acidentes com vítimas feridas e fatais.</p>
<p>A qualidade dos registros de mortalidade em São Paulo é acima da média brasileira, que recebeu uma avaliação “alta” em uma avaliação de sistemas nacionais de estatísticas vitais (MIKKELSEN, L; 2015).</p>

<h5>2.	Principais bases de dados de acidentes de trânsito</h5>
<h6>a.	CET</h6>
<p>A CET mantém três bases de dados específicas a respeito da segurança viária, de acidentes, vítimas e veículos, que juntas formam o Sistema de Acidentes de Trânsito (SAT). As bases tratam tanto de acidentes fatais como não fatais. São duas as fontes dos dados. A primeira é o sistema Infocrim, gerido pela Polícia Civil, do qual a CET extrai informações a partir de arquivos HTML encaminhados mensalmente. A outra são informações coletadas junto ao Instituto Médico Legal (IML).</p>
<p>Estas bases reúnem muitas das recomendações internacionais a respeito dos dados sobre segurança viária, tais como informações sobre o tipo de acidente, tipos de veículos envolvidos, tipo de via, dia, horário e informações sobre as pessoas envolvidas, como gênero e idade. Em relação à metodologia, o processo da CET segue os padrões internacionais sugeridos pela ONU desde 2016, que consideram que o óbito foi decorrente da acidente de trânsito se tiver acontecido em até 30 dias.</p>
<p>Por outro lado, são ausentes informações sobre fatores de risco como uso do álcool, cinto de segurança, celular e capacete (neste último caso, para motociclistas). Ademais, as informações constantes do Infocrim não são registradas em formato apropriado e as coordenadas geográficas não estão disponíveis ao uso da empresa, que precisa realizar seu próprio georreferenciamento. A base do Infocrim não alcança as ocorrências que não prosseguem até a etapa de investigação criminal. Uma coleta mais completa dos dados requereria acesso a dados das múltiplas fontes de informação que alimentam o Infocrim.</p>
<p>Quanto à base de fatalidades, a companhia possui uma equipe que vai ao Instituto Médico Legal (IML) mensalmente para coletar dados a respeito das mortes decorrentes do trânsito, bem como os números dos boletins de ocorrência relacionados (BOs)  - cerca de 800 por mês. Eles relacionam o número do BO reportado pelo IML com as informações extraídas do Infocrim para identificar as mortes que foram decorrentes do trânsito e complementar suas informações. Este é um processo custoso e demorado, já que em média as equipes trabalham com aproximadamente 5.000 BOs por mês para serem cruzados com aproximadamente 2.000 registros de acidentes de trânsito. Informações sobre uso do álcool constam de outra base de dados gerida pelo IML, a qual não é disponibilizada à CET.</p>
<p>Em resumo, a situação atual relativa aos dados geridos pela CET tem como pontos fortes o estabelecimento de rotinas de coleta de dados e a larga quantidade de dados de boa qualidade e confiabilidade. Por outro lado, os sistemas de informação utilizados necessitam de atualização tecnológica e existe ainda uma defasagem temporal entre a ocorrência de trânsito e a consolidação da informação disponibilizada de 3 meses. Além disso, pelas fontes de informação serem múltiplas, não integradas entre si e subordinadas à instância estadual, gera-se grande quantidade de trabalho para consolidar os dados e dificuldades de promover a inclusão de outras informações relevantes, tais como o uso ou não de cinto de segurança ou a direção por condutor embriagado.</p>

<h6>b.	RIFs e IATs</h6>
<p>As Investigações de Acidente de Trânsito (IAT) e os Relatórios de Investigação de fatais (RIFs) são outras duas fontes adicionais de dados sobre segurança viária. Os RIFs provêm da avaliação em campo dos acidentes graves e fatais pela equipe de segurança da CET. O trabalho é realizado por uma equipe de colaboradores formados no curso de perícia de acidentes da Polícia Militar, acionada pela Central de Comunicações da CET para comparecer ao local onde houve um acidente grave ou fatal a fim de identificar o fator determinante da ocorrência. O exame das evidências no local e as alegações das testemunhas ou do policial que atendeu à ocorrência permitem visualizar a dinâmica do acidente de trânsito e identificar qual ação a ocasionou.</p>
<p>Apesar de ainda não haver integração entre essas informações e o SAT, o banco de dados formado por estas “perícias” subsidia a formulação de programas de combate à violência do trânsito assim como a identificação de defeitos da sinalização ou das pistas que levam à desestabilização da trajetória dos veículos e que precisam de correção. Verifica-se a necessidade de desenvolvido tecnológico para a coleta dos dados seja digital, simplificando a emissão das avaliações de fatores determinantes.</p>
<p>Já os IATs são formulários preenchidos pelo agente de trânsito da CET quando do atendimento de um acidente de trânsito, seja ela com ou sem vítima. Apesar de, assim como os RIFs, os IATs não estarem integrados ao SAT, diversas informações são coletadas através de observações e com os envolvidos, além de croqui do local e da ocorrência. Está em fase de desenvolvimento o IAT eletrônico, que permitirá a simplificação da coleta das informações por meio de formulário eletrônico inserido por aplicativo no smartphone corporativo dos agentes de trânsito.</p>

<h6>c.	INFOSIGA</h6>
<p>O INFOSIGA é o sistema de informações gerenciais dos acidentes de trânsito do Estado de São Paulo. É um banco de dados que reúne informações de acidentes de trânsito de diversas fontes, como Polícia Civil, Polícia Militar e Polícia Rodoviária Federal.</p>
<p>Trata-se de uma das principais iniciativas do Movimento Paulista de Segurança no Trânsito, instância do Governo do Estado de São Paulo. As informações são atualizadas mensalmente, todo o dia 19 ou próximo dia útil, e contam com dados sobre perfil das vítimas e das ocorrências fatais nos 645 municípios.</p>
<p>A metodologia é baseada nas fontes de informação da Secretaria de Segurança Pública (SSP) do Estado de São Paulo e da Polícia Rodoviária Federal (PRF). Os dados referentes a óbitos são enviados mensalmente pela Secretaria de Segurança Pública, obtidos por meio de extração do sistema Registro de Ocorrências (RDO) utilizado pela Polícia Civil na elaboração de Boletins de Ocorrência em todo o estado. Esta é a fonte utilizada no INFOSIGA pois todos os óbitos em decorrência de acidente de trânsito devem ser registrados nesta base para possibilitar o enterro da vítima. Isso ajuda a garantir a completude e consistência da base.</p>
<p>A metodologia INFOSIGA usa o critério epidemiológico, onde o acidente é considerada de trânsito se for estabelecido que a causa raiz foi a ocorrência, ou seja, se não houvesse acontecido o acidente de trânsito a vítima não teria falecido. Dessa forma, não são utilizados critérios temporais para a inclusão dos casos na base.</p>
<p>Os boletins de ocorrência são analisados pela equipe do Movimento Paulista de Segurança no Trânsito, selecionando apenas os que foram identificados como sendo relativos a acidentes de trânsito. Estes são então tabulados e, desta forma, são obtidas as variáveis contidas nos relatórios do INFOSIGA-SP. O fluxo de análise e tabulação da base é o seguinte:</p>
<slot name='f23'></slot>
<p>Entre os pontos fortes do sistema, destaca-se a coleta de dados em nível estadual (menor chance de subnotificação), o fluxo de dados online automatizado, a alimentação diária de BOs e o georreferenciamento dos dados. Por outro lado, as principais necessidades de melhoria são Inclusão de ocorrências com vítimas feridas na base e a implantação da recomendação da OMS para consideração de óbitos até 30 dias após o ocorrido.</p>

<h5>3.	Dados específicos de Saúde</h5>
<p>O município de São Paulo conta com cerca de 70 estabelecimentos de saúde que fazem parte do Sistema Único de Saúde, e os dados produzidos nesses estabelecimentos são padronizados e mantidos pelo Ministério da Saúde. Cerca de 55% da população da cidade é coberta exclusivamente pelo SUS, valor abaixo da média nacional de 75%, o que torna os dados menos representativos da população municipal.</p>
<p>Recentemente, foi iniciado um trabalho para integração das bases de dados referentes a acidentes de trânsito das áreas de transporte e saúde, com os objetivos de obter maior abrangência e completude das informações coletadas; qualificação do grau de severidade das lesões; melhor entendimento das tendências temporais; identificação de aglomerações por tipo de ocorrência e de vítima e estimativas dos custos das acidentes de trânsito para o sistema de saúde;</p>
<p>A base-referência para a integração é o sistema SAT da CET, estabelecido a partir de registros policiais. As bases de dados envolvidas nesse trabalho pela parte da saúde são:</p>

<h6>a.	SAMU</h6>
<p>O SAMU possui, dentro do seu cadastramento de ocorrências, uma classificação específica para acidentes de trânsito/transporte, que corresponde a aproximadamente 6% do número total de chamados atendidos. Dentre as informações coletadas estão a classificação de prioridade da ocorrência (um indicador indireto da gravidade do acidente), a localização e o estabelecimento de destino da vítima segundo o Cadastro Nacional de Estabelecimentos de Saúde.</p>

<h6>b.	Sistema de Informações sobre Mortalidade (SIM)</h6>
<p>O Sistema de base nacional dos dados sobre mortalidade, gerido pela Coordenação de Epidemiologia e Informação (CEINFO), onde está inserido o Programa de Aprimoramento das Informações de Mortalidade no Município de São Paulo (PRO-AIM), contém as informações sobre todos os óbitos ocorridos no município de São Paulo, a partir do processamento das Declarações de Óbito (DO). Um dos principais objetivos do sistema é subsidiar a elaboração e condução de políticas públicas em diversas áreas. O sistema utiliza a classificação internacional de doenças CID-10, por meio do qual é possível identificar a causa da morte, por exemplo, “ciclista traumatizado em colisão com um automóvel, “pick up” ou caminhonete, identificando, portanto, as circunstâncias do óbito. A declaração de óbito traz, também, a informação sobre a gravidade da lesão sofrida, tais como, ferimento, fratura, luxação, etc.</p>

<h6>c.	Sistema de Informações Hospitalares do SUS (SIHSUS)</h6>
<p>O Sistema de base nacional dos dados sobre as internações hospitalares, hospital-dia e internação domiciliar realizados pelos estabelecimentos de saúde prestadores de serviço da rede do SUS, reúne as Autorizações de Internação Hospitalar (AIHs) nos estabelecimentos de saúde e prestadores de serviços para o SUS, com o objetivo de obter informações sobre os recursos destinados a cada hospital que integra a rede do SUS, bem como as principais causas de internação e procedimentos realizados. Assim como o sistema SIM, o SIHSUS utiliza a CID-10.</p>

<h6>d.	Sistema de Informações Ambulatoriais do SUS (SIASUS)</h6>
<p>O sistema de base nacional dos dados sobre os atendimentos ambulatoriais realizados pelos estabelecimentos de saúde prestadores de serviço da rede do SUS contém os procedimentos ambulatoriais executados por todos os estabelecimentos de saúde e prestadores de serviços para o SUS no município de São Paulo. O objetivo desse sistema é prover informações sobre capacidade operacional dos prestadores de serviço, orçamento e controle dos repasses dos recursos financeiros, custeio das unidades ambulatoriais e administração das atividades ambulatoriais.</p>

<h6>e.	Sistema de Informação para Vigilância de Violências e Acidentes (SIVVA)</h6>
<p>O Sistema de base municipal dos dados sobre notificação de casos suspeitos ou confirmados de violências e acidentes, gerida pela COVISA, contém todos os casos suspeitos e confirmados de violência e acidentes atendidos e ocorridos no Município de São Paulo, a partir das Fichas de Notificação de Casos Suspeitos ou Confirmados de Violências e Acidentes.</p>

<h5>4.	Inquérito de Saúde – ISA Capital<a title="  ISA Capital. Disponível em http://www.prefeitura.sp.gov.br/cidade/secretarias/upload/saude/arquivos/publicacoes/ISA_2015_AC.pdf. Acesso em 19/06/2018

" href='http://www.prefeitura.sp.gov.br/cidade/secretarias/upload/saude/arquivos/publicacoes/ISA_2015_AC.pdf' style='cursor: help;' target="_blank"><sup>49</sup></a></h5>
<p>O ISA Capital é uma pesquisa de saúde de natureza transversal e de base populacional financiada pela Secretaria Municipal da Saúde de São Paulo (SMS-SP) e desenvolvida por equipe de pesquisadores da Faculdade de Saúde Pública e Faculdade de Medicina da Universidade de São Paulo – FSP e FM/USP, Faculdade de Ciências Médicas da Universidade Estadual de Campinas – FCM/UNICAMP, Instituto da Saúde da Secretaria de Estado da Saúde de São Paulo – IS/SES-SP e técnicos da Secretaria de Saúde do Município de São Paulo.</p>
<p>Seu objetivo é levantar aspectos da saúde não contidos nos sistemas rotineiros de informação do SUS. Sua última versão é de 2015, a qual apresenta estimativas de ocorrência de acidentes de trânsito, quedas e outros tipos de acidentes que aconteceram nos 12 meses, no Município de São Paulo, que antecederam a entrevista, segundo variáveis socioeconômicas e demográficas e região de saúde. A pesquisa analisa as características destes acidentes, suas vítimas e suas consequências à saúde dos envolvidos.</p>

<h5>5.	Dados de planejamento urbano</h5>
<p>Tendo em vista a relação íntima entre planejamento urbano, mobilidade e segurança viária, compete analisar as principais ferramentas e bases de dados disponíveis relacionadas a urbanismo e planejamento urbano.</p>
<p>Na PMSP, a estrutura responsável pela organização e sistematização de grande parte das informações é a Coordenadoria de Produção e Análise de Informação (GEOINFO), que tem como principais atribuições compilar e processar dados cadastrais, demográficos, socioeconômicos e territoriais, oriundos de diversas secretarias municipais e de outras instituições, tais como IBGE, Fundação Seade e Ministério do Trabalho. Esses dados formam um acervo bastante diversificado sobre o município.</p>
<p>O GeoSampa é um portal que reúne informações detalhadas e georreferenciadas da cidade. Dentre o conteúdo disponível, destacam-se os dados sobre a infraestrutura de transporte no município, como a localização da rede cicloviária, das estações e eixos do sistema metroferroviário, além dos pontos, terminais, corredores, faixas exclusivas e linhas do sistema municipal de transporte coletivo sobre pneus (ônibus). Também é possível consultar a localização dos logradouros, das quadras viárias, obras de arte, cruzamentos semaforizados e Zona Azul. Os dados referentes à acidentes de trânsito ainda não integram o Geosampa.</p>
<p>Uma das principais características do GeoSampa são os mecanismos de integração que permitem que os dados disponibilizados em mapa venham diretamente dos sistemas de origem. Dessa forma, é possível garantir a consistência do dado, sua atualização e a fidedignidade em relação à informação original, evitando assim a replicação das bases (o que certamente acaba causando divergência de informações). Todo seu conteúdo está disponível para consulta e download em formato aberto e também pode ser acessado via serviços web.</p>
<p>O Observatório de Indicadores da Cidade de São Paulo (ObservaSampa) reúne mais de 320 indicadores, agrupados em 21 temas, que recobrem áreas de interesse diversos. O portal permite visualizar os indicadores em gráficos e mapas temáticos por distritos ou subprefeituras ou ainda fazer o download de todos os indicadores e variáveis disponíveis no site. O tema da mobilidade urbana apresenta 34 indicadores, incluindo alguns relativos à infraestrutura implantada, qualidade dos serviços prestados, condições gerais e mortalidade no trânsito.</p>
<p>Já o Infocidade coloca à disposição do público, de modo sintético, uma extensa compilação de informações sobre o Município e que podem ser consultadas, sobretudo, na forma de tabelas, mas também no formato de gráficos e mapas. São dezessete assuntos disponíveis, entre eles o transporte. A temática apresenta uma série de dados gerais sobre o trânsito no município, compilados pelas Pesquisas Origem - Destino, desenvolvidas pelo METRÔ, bem como pelos Relatórios de Desempenho do Sistema Viário Principal, produzidos pela CET.</p>
<p>O GEOINFO também coordena os trabalhos de padronização das bases de logradouros do município, integrando as informações viárias de diversos órgãos (CET, SPTRANS, SF, SMUL, etc.) em uma base de dados comum e compartilhada. A dificuldade atual consiste em agrupar as diversas bases de logradouros existentes oriundas de diferentes órgãos, que acabam por gerar retrabalho, além de arquivos incompletos e com muitas divergências. O Grupo de Trabalho sobre logradouros tem como objetivo uniformizar e atualizar a NBL (Nova Base de Logradouros), gerando um arquivo consistente, que atenda aos cidadãos e aos diversos órgãos municipais. Para tanto o grupo criou um fluxo de atualizações, onde os diversos órgãos sugerem modificações na NBL, que são discutidas em grupo e alimentam uma base única.</p>
<p>Por fim, a GEOINFO  desenvolveu também uma metodologia para aferição da largura das calçadas e das vias no município. A partir do uso de ferramentas de geoprocessamento, calculou-se a extensão dos segmentos de logradouros e a área correspondente a cada via e calçada, excluindo-se a área interna das quadras. Com estes dados e o uso de noções de geometria, foi possível aferir a largura média existente nas feições retangulares.</p>

<h5>6.	Dados de fiscalização e segurança urbana</h5>
<p>As bases de dados relacionadas à fiscalização e segurança urbana são:</p>

<h6>a.	Detecta</h6>
<p>É um sistema integrador de informações que realiza, com celeridade, a correlação dessas informações para auxiliar a tomada de decisões das polícias militar, civil e científica. O objetivo é auxiliar o trabalho policial em atividades operacionais e investigativas acessando diversos bancos de dados de diferentes instituições, correlacionando informações e imagens de locais, pessoas e veículos, promovendo ações policiais coordenadas.</p>

<h6>b.	Infocrim</h6>
<p>É um dos principais sistemas de informações criminais da Secretaria de Segurança Pública do Estado de São Paulo (SSP-SP) e sua principal fonte de informação é a base de Boletins de Ocorrência (BO) e Termos Circunstanciados (TC) da Polícia Civil. Sua base de dados é atualizada todos os dias e um Boletim de Ocorrência ou Termo Circunstanciado fica disponível no dia subsequente à data em que foi registrado.</p>

<h6>c.	Base de Dados Equipamentos de Fiscalização Eletrônica</h6>
<p>Os equipamentos de fiscalização eletrônica, para além de servirem à identificação de infrações, coletam um amplo conjunto de dados por meio de sistemas de identificação de placas. Os dados podem gerar informações gerais sobre volumes de tráfego e velocidades, por exemplo, mas ainda não são utilizados para planejamento das políticas públicas de mobilidade e segurança.</p>

<h5>7.	Dados relativos ao STCUP</h5>
<p>A gestão da operação do STCUP é feita pela SPTrans especialmente por meio do Sistema Integrado de Monitoramento (SIM), que utiliza o sistema GPS (Sistema de Posicionamento Global) para localização dos veículos, por meio do equipamento embarcado Automatic Vehicle Location (AVL).</p>
<p>O AVL tem a função de obter informações do sistema GPS, estabelecer uma conexão com o centro de controle da SPTrans e enviar um pacote de dados contendo a localização exata do veículo. Essa transmissão é realizada a cada 40 segundos, sendo coletados aproximadamente 28 milhões de registros por dia, os quais são contabilizados pelo SIM.</p>
<p>O SIM é uma ferramenta de monitoramento e controle eletrônico, que permite o gerenciamento das linhas, da frota de veículos e da infra-estrutura dedicada do Sistema de Transporte, com intervenções em tempo real para correção de problemas operacionais e adequações para o equilíbrio da oferta em relação à demanda de passageiros. Outra de suas funcionalidades é prestar informações aos usuários sobre os horários previstos de saída dos veículos nos Painéis de Mensagens Variáveis – PMV’s, instalados nos corredores e nos terminais inteligentes.</p>
<p>Quando ocorre um acidente envolvendo um ônibus do STCUP, o motorista deve gerar um alerta à central de operações da SPTrans, que designa equipe para acompanhamento da ocorrência em campo. A partir das informações coletadas e analisadas pela central de operações e dos dados de quilometragem apurados por meio do SIM, é elaborado o indicador IAQ (Índice de Acidentes por Quilômetro), que mede o número de acidentes a cada 1.000.000 de quilômetros rodados para cada empresa operadora do sistema.</p>

<h5>8.	Dados sobre a Pessoa com Deficiência</h5>
<p>No que se refere aos dados referentes à pessoa com deficiência, para além das informações contidas no CENSO, promovido pelo IBGE, a PMSP, assim como o Brasil e vários outros países, passa por um momento de transição.</p>
<p>Isso se deve ao fato da Lei Brasileira de Inclusão e da Convenção Internacional dos Direitos da Pessoa com Deficiência trazerem como exigência a transição conceitual do modelo biomédico para o modelo biopsicosocial sobre pessoas com deficiência.</p>
<p>As políticas públicas e respectivas bases de dados da PMSP estão em diferentes estágios nessa transição. Algumas se encontram no que seria a estaca zero, adotando apenas a CID como referência. Outras já estão mais próximas à abordagem da deficiência com resultado da interação com barreiras físicas e sociais. Mas nenhuma segue plenamente o modelo de avaliação e categorização proposto pela CIF  - que seria a ferramenta capaz de traduzir o modelo biopsicosial.</p>
<p>A partir desta situação, a SMPED, por meio da iniciativa de estruturação Observatório Municipal da Pessoa com Deficiência, vêm colocando esforços para alterar esta situação.</p>
<p>O Observatório Municipal da Pessoa com Deficiência tem como missão harmonizar as bases de dados municipais, inserindo o olhar biopsicosocial sobre a avaliação das pessoas com deficiência, além de atuar como repositório de dados, indicadores e informações sobre as pessoas com deficiência e  a rede de serviços municipais voltada ao atendimento deste população.</p>
<p>O principal ponto de fragilidade relativo ao tema é a impossibilidade de cruzar informações sobre as pessoas que adquiriram sequelas permanentes em decorrência de acidentes de trânsito. Espera-se que, com a integração das bases de dados da CET e da área da saúde, exista a possibilidade de essas informações serem gerenciadas.</p>

<h5>9.	Análise de dados como subsídio ao planejamento</h5>
<p>De modo geral, apesar das melhorias necessárias na qualidade, quantidade e integração dos dados existentes sobre segurança viária, o município possui a possibilidade de se utilizar da gama de dados disponível para a identificação dos pontos críticos de acidentes, bem como suas causas, de modo a subsidiar a implementação de ações. Exemplo disso é a intervenção recém ocorrida na Estrada do M’ Boi Mirim.</p>
<p>Diferentes órgãos têm diferentes modos de lidar com as informações disponíveis, bem como diferentes níveis de capacidade de intervenção. Verifica-se que o ponto mais crítico em relação ao uso dos dados para planejamento das ações acaba por recair não no uso dos dados em si, mas na capacidade de implantação de todas adequações necessárias.</p>
<p>Atualmente a CET tem uma principal publicação dedicada à análise de dados de modo a subsidiar o planejamento de políticas públicas e intervenções em segurança viária: o Relatório Anual de Acidentes.</p>
<p>O Relatório Anual tem como base os dados consolidados no Sistema de Acidentes de Trânsito (SAT) e é um documento que realiza as seguintes análises: compara os acidentes de trânsito com outras causas de morte no município, analisa as séries históricas de acidentes por tipo, veículo e severidade (vítimas feridas e fatais), organiza as distribuições temporais e espaciais dos acidentes, traça um perfil das vítimas por idade, gênero e tipo, define grupos de risco e taxas de mortalidade por número de habitantes e de veículos, calcula uma estimativa de custo dos acidentes e elenca pontos críticos na cidade.</p>
<p>Já a SPTrans possui um Programa de Redução de Acidentes de Transporte (PRAT), descrito no diagnóstico do Eixo IV deste plano. O CPTran, por sua vez, realiza mensalmente a chamada Reunião de Análise Crítica (RAC), as quais analisam os acidentes ocorridos no mês anterior, a partir dos dados do INFOSIGA. Desta análise, é elaborado o Relatório de Averiguação de Incidente Administrativo (RAIA), que busca a identificação das causas do acidente. A partir do relatório, o CPTran, ou aciona o órgão competente à resolução do problema, ou altera sua própria atuação, intensificando a fiscalização nos pontos críticos.</p>
	</div>
</template>

<script>
export default {
	name: 'Cap2CEixoXI'
}
</script>
