<template>
	<div class="Cap2CEixoI">
		<h4>1.	Principais atores governamentais relacionados à Segurança Viária</h4>
		<p>A governança sobre a segurança viária no âmbito estatal envolve todos os três níveis federativos brasileiros. Somam-se dezenas de competência distintas, desde a instituição de normas válidas a todo o território nacional, passando por funções fiscalizatórias, de atendimento hospitalar e de gestão do transporte público, competências urbanísticas e de implementação de obras públicas, até a gestão do viário municipal.</p>
		<p>De acordo com o Código de Trânsito Brasileiro (CTB), Lei Federal nº 9.503/1997 e alterações, o Sistema Nacional de Trânsito (SNT) é o conjunto de órgãos e entidades da União, dos estados, do Distrito Federal e dos municípios que tem por finalidade o exercício das atividades de planejamento, administração, normatização, pesquisa, registro e licenciamento de veículos, formação, habilitação e reciclagem de condutores, educação, engenharia, operação do sistema viário, policiamento, fiscalização, julgamento de infrações e de recursos e aplicação de penalidades. O SNT é composto ainda pelo Conselho Nacional de Trânsito (CONTRAN); pelos Conselhos de Trânsito dos Estados e do Distrito Federal; pelos órgãos e entidades executivos de trânsito e rodoviários de todos os entes federativos; pela Polícia Rodoviária Federal; pelas Polícias Militares e pelas Juntas Administrativas de Recursos de Infrações (JARI).</p>
		<p>De acordo com o Art. 1º do CTB, o trânsito, em condições seguras, é um direito de todos e dever dos órgãos e entidades componentes do STN, a estes cabendo adotar as medidas destinadas a assegurar esse direito. Os órgãos do SNT devem dar prioridade em suas ações à defesa da vida, inclusive respondendo por ações e omissões que firam os direitos dos cidadãos ao trânsito seguro.</p>
		<p>Para além dos órgãos integrantes do SNT, a segurança viária é afetada também pela atuação de outros conjuntos de órgãos, tais como aqueles relacionados ao desenvolvimento urbano e implantação de obras viárias, à educação, comunicação e saúde.</p>
		<p>Os principais atores governamentais relativos ao tema são:</p>
		<h5>a.	Estruturas federais:</h5>

		<h6>i.	Departamento Nacional de Trânsito (DENATRAN)</h6>
		<p>A coordenação máxima do Sistema Nacional de Trânsito compete ao Ministério das Cidades, por meio do Departamento Nacional de Trânsito (DENATRAN), órgão máximo executivo de trânsito da União.</p>
		<h6>ii.	Conselho Nacional de Trânsito (CONTRAN)</h6>
		<p>O CONTRAN é responsável por estabelecer as normas regulamentares referidas no CTB e as diretrizes da Política Nacional de Trânsito; coordenar os órgãos do Sistema Nacional de Trânsito, objetivando a integração de suas atividades; zelar pela uniformidade e cumprimento das normas contidas no CTB e nas resoluções complementares e normatizar os procedimentos sobre a aprendizagem, habilitação, expedição de documentos de condutores, e registro e licenciamento de veículos. Vinculado ao DENATRAN, é composto por membros do: Ministério das Cidades; Ministério da Ciência, Tecnologia, Inovações e Comunicações; Ministério da Educação; Ministério da Defesa; Ministério do Meio Ambiente; Ministério dos Transportes, Portos e Aviação Civil; Ministério da Saúde; Ministério da Justiça e Segurança Pública; Agência Nacional de Transportes Terrestres e Ministério da Indústria, Comércio Exterior e Serviços.  </p>

		<h6>i.	Agência Nacional de Transportes Terrestres (ANTT)</h6>

			<p>A ANTT, criada pela Lei Federal nº 10.233/2001, é a agência reguladora responsável por supervisionar e fiscalizar a prestação de serviços e exploração da infraestrutura de transportes, exercidas por terceiros, como a concessão de  ferrovias,  rodovias e o transporte ferroviário associado à exploração de infraestrutura e a permissão do transporte regular de passageiros pelos meios rodoviário e ferroviário não associado à exploração de infraestrutura.</p>

		<h5>b.	Estruturas estaduais:</h5>

		<h6>i.	Comando de Policiamento de Trânsito da Polícia Militar de São Paulo (CPTran): </h6>

		<p>Nos termos da Lei Estadual nº 616/1974, a Polícia Militar do Estado de São Paulo  destina-se à manutenção da ordem pública na área do Estado. A ela compete executar, com exclusividade, o policiamento ostensivo fardado, a fim de assegurar o cumprimento da lei, a manutenção da ordem e o exercício dos poderes constituídos. Dentre suas atividades, encontram-se o policiamento no trânsito e o policiamento nas estradas estaduais e municipais. Pelo Decreto Estadual nº 62.103/2016, o Comando de Policiamento de Trânsito (CPTran) é responsável pelas missões de polícia de trânsito urbano na capital, bem como pela fixação e difusão de doutrina nas questões afetas às atividades de polícia de trânsito urbano.</p>

		<h6>ii.	Corpo de Bombeiros da Polícia Militar de São Paulo:</h6>

		<p>O Corpo de Bombeiros do Estado de São Paulo pertence à estrutura da Polícia Militar, sendo o órgão responsável pelo planejamento, comando, execução, coordenação, fiscalização e controle de todas as atividades de prevenção, extinção de incêndios e de buscas e salvamentos.</p>

		<h6>iii.	Departamento de Estradas de Rodagem do Estado de São Paulo (DER):</h6>

		<p>O DER é responsável principalmente pela organização e revisão periódica do plano geral de viação rodoviária do Estado; bem como por todos os serviços técnicos e administrativos concernentes a especificações, estudos, projetos, orçamentos, locação, construção, reconstrução, conservação, melhoramentos e fiscalização técnica das estradas de rodagem do Estado, inclusive pontes e demais obras de artes que delas forem partes integrantes. No município de São Paulo, o DER é responsável pela gestão da Rodovia Raposo Tavares.</p>

		<h6>iv.	Agência Reguladora de Serviços Públicos Delegados de Transporte do Estado de São Paulo (ARTESP)</h6>

		<p>Nos termos da Lei Estadual Complementar nº 914/2002, a ARTESP, autarquia de regime especial, é responsável por regulamentar e fiscalizar todas as modalidades de serviços públicos de transportes autorizados, permitidos ou concedidos a entidades de direito privado, em especial as rodovias estaduais. Com isso, a entidade é responsável por implementar a política estadual de transportes; preparar os editais e promover as licitações para a contratação de serviços públicos de transporte; celebrar e gerenciar os contratos de prestação de serviços públicos de transportes e intervir na prestação dos serviços públicos de transporte, autorizados, permitidos ou concedidos.</p>

		<h6>v.	Departamento Estadual de Trânsito de São Paulo (Detran.SP)</h6>

		<p>O Detran SP é responsável pelas atividades de trânsito estabelecidas pelo CTB no Estado de São Paulo. São competências do Detran.SP promover educação para o trânsito, planejar, coordenar, executar e controlar ações relacionadas à habilitação de condutores, documentação e serviços para veículos.</p>

		<h6>vi.	Secretaria de Transportes Metropolitanos do Estado de São Paulo (STM)</h6>

		<p>A STM, criada pela Lei Estadual nº 7.450 de 1991, é responsável pela execução da política estadual de transportes urbanos de passageiros para as regiões metropolitanas, o que inclui a Região Metropolitana da Cidade de São Paulo (RMSP), abrangendo os sistemas metroviário, ferroviário, de ônibus e trólebus, e demais divisões modais de interesse metropolitano.</p>

		<h6>vii.	Empresa Metropolitana de Transportes Urbanos de São Paulo (EMTU)</h6>

		<p>A EMTU, vinculada à STM, fiscaliza e regulamenta o transporte metropolitano de baixa e média capacidades (transporte sobre pneus) em todas as Regiões Metropolitanas do Estado, o que inclui a RMSP, com seus 39 municípios. Em 2017, a EMTU transportou, apenas na RMSP, mais de 500 milhões de passageiros em uma frota de aproximadamente 4.500 veículos.</p>

		<h6>viii.	Companhia do Metropolitano de São Paulo (METRÔ)</h6>

		<p>O METRÔ é responsável por contratar, coordenar e superintender os estudos e projetos e promover as medidas necessárias para a implantação de um sistema de transporte rápido de passageiros na cidade de São Paulo. De acordo com dados de abril de 2018, a rede metroviária de São Paulo conta com quase 90 km de extensão de rede e 79 estações, transportando mais de 1 bilhão de passageiros por ano, sendo que novas linhas e estações estão previstas para os próximos anos.</p>

		<h6>ix.	Companhia Paulista de Trens Metropolitanos (CPTM)</h6>

		<p>A CPTM teve sua criação autorizada na Lei Estadual nº 7.861/1992, sob a forma de sociedade de economia mista, com o fim especial de explorar os serviços de transporte de passageiros sobre trilhos ou guiados nas entidades regionais do Estado de São Paulo, compreendendo as regiões metropolitanas, aglomerações urbanas e microrregiões. A CPTM transporta mais de 800 milhões de passageiros ao ano, possui extensão de rede ferroviária de 273 km e 94 estações, sendo que recentemente passou a ofertar transporte inclusive para o Aeroporto Internacional de São Paulo, em Guarulhos.</p>

		<h6>x.	Desenvolvimento Rodoviário (DERSA)</h6>

			<p>A DERSA é uma entidade empresarial do Estado de São Paulo, cuja missão é entregar as melhores soluções em infraestrutura de transportes e logística, com inovação, conhecimento e pioneirismo. A entidade atua como consultora nas áreas de implantação, meio ambiente, desapropriação e reassentamento, projetos, serviços públicos, planejamento e gestão, sistemas e operação e manutenção de grandes obras de infraestrutura viária.</p>

		<h5>c.	Estruturas municipais</h5>

		<h6>i.	Prefeitura Municipal de São Paulo (PMSP)</h6>

			<p>De acordo com artigo 179 da Lei Orgânica do Município de São Paulo, compete ao município, gerido pela Administração Pública Municipal, organizar, promover, controlar e fiscalizar o trânsito no âmbito do seu território. Também é incumbência da administração municipal a promoção da política urbana do município, de modo a assegurar o acesso de todos os seus cidadãos a condições adequadas de transporte público e infra-estrutura viária.</p>

		<h6>ii.	Secretaria Municipal de Mobilidade e Transportes de São Paulo (SMT)</h6>

		<p>A SMT, pasta integrante da PMSP, criada em 1967, é responsável por formular, propor, gerir e avaliar políticas públicas para o desenvolvimento da mobilidade urbana; estudar, planejar, gerir, integrar, fiscalizar e controlar os transportes individuais e coletivos do município; executar os serviços de trânsito da competência do município e estabelecer diretrizes e normas para o uso da rede viária municipal, zelando, no âmbito de sua circuncisão pela segurança viária</p>

		<h6>iii.	Departamento de Operação do Sistema Viário (DSV)</h6>

		<p>O DSV, estrutura subordinada à SMT, tem como atribuições legais propor melhorias e regulamentar o sistema viário do município; estudar e implementar medidas pertinentes à segurança e ao rendimento do sistema viário e emitir autorização de uso de vias públicas para fins de intervenções particulares e obras privadas. A maioria das atribuições pertencentes ao departamento são executadas pela Companhia de Engenharia de Tráfego.</p>

		<h6>iv.	Departamento de Transportes Públicos (DTP)</h6>

			<p>O DTP, também subordinado à SMT, tem por atribuições essenciais a gestão, a regulamentação, o cadastro, a vistoria e a fiscalização dos serviços de transporte realizados por táxis, fretamento escolar e motofrete, além da fiscalização das Operadoras de Tecnologia de Transporte Credenciadas (OTTCs), o que inclui os transportes individuais por aplicativo e os sistemas de bicicletas compartilhadas. A São Paulo Transporte (SPTrans) presta apoio na execução das competências legais do departamento.</p>

		<h6>v.	Companhia de Engenharia de Tráfego (CET)</h6>

		<p>A CET teve sua criação autorizada pela Lei Municipal nº 8.394/1976 como sociedade de economia mista vinculada à SMT. A companhia tem por objetivo planejar e implantar, nas vias e logradouros do município, a operação do sistema viário, com o objetivo de assegurar a segurança, garantindo também a fluidez do trânsito e do tráfego.</p>

		<h6>vi.	São Paulo Transporte (SPTrans)</h6>

		<p>A SPTrans, criada em 1995 após o processo de privatização da Companhia Municipal de Transportes Coletivos (CMTC), é uma sociedade de economia mista vinculada à SMT. Suas funções primordiais são elaborar estudos para o planejamento e o aperfeiçoamento dos serviços compreendidos no Sistema de Transporte Coletivo Urbano de Passageiros de São Paulo (STCUP); gerenciar e fiscalizar a execução dos serviços prestados pelas empresas contratadas, concessionárias ou permissionárias, relativos ao STCUP; e promover as licitações, bem como assinar contratos, outorgar permissões e autorizações referentes aos serviços do STCUP, exercendo seu controle e fiscalização.</p>
		<h6>vii.	Coordenadoria de Vigilância em Saúde (COVISA)</h6>

		<p>A COVISA, integrante do Sistema Nacional de Vigilância Sanitária e pertencente à estrutura da Secretaria Municipal de Saúde, tem como atribuições gerir e coordenar o Sistema Municipal de Vigilância em Saúde; coordenar a programação das ações de vigilância em saúde; e coordenar, monitorar e avaliar as ações de vigilância em saúde.</p>

		<h6>viii.	Departamento de Atenção à Urgência e Emergência e Coordenação de Serviço de Atendimento Móvel de Urgência (SAMU)</h6>

		<p>O Departamento de Atenção à Urgência e Emergência da Secretaria Municipal de Saúde tem as atribuições de definir as políticas de saúde de urgência e emergência do município; operacionalizar o sistema regionalizado e hierarquizado de saúde, no que se refere às urgências; gerir e promover a realização do atendimento médico pré-hospitalar de urgência e promover a integração do Serviço de Atendimento Móvel de Urgência aos serviços de salvamento e resgate atuantes no município.</p>
		<p>O SAMU, também pertencente à Secretaria Municipal de Saúde, tem como atribuições executar a atenção médico pré-hospitalar de urgência e estabelecer protocolos para o funcionamento das bases descentralizadas regionais.</p>

		<h6>ix.	Secretaria Municipal de Urbanismo e Licenciamento (SMUL)</h6>

		<p>A Secretaria Municipal de Urbanismo e Licenciamento (SMUL) foi organizada pelo Decreto Municipal nº 57.576/2017, mediante a  fusão das Secretarias de Desenvolvimento Urbano e de Licenciamento, tendo sido recentemente consolidada pela Lei municipal nº 16.974/2018. A SMUL tem por finalidade coordenar e conduzir ações governamentais voltadas ao planejamento e desenvolvimento urbano, formular e executar a política de licenciamento, bem como controlar o parcelamento urbano, uso e ocupação do solo e executar  atividades compatíveis e correlatas com a sua área de atuação.</p>

		<h6>x.	São Paulo Urbanismo (SP Urbanismo)</h6>

		<p>A criação da SP Urbanismo foi autorizada pela Lei Municipal nº 15.056/2009. A empresa pública tem como objetivo fundamental dar suporte e desenvolver as ações governamentais voltadas ao planejamento urbano e à promoção do desenvolvimento urbano do município, o que inclui a concepção, a estruturação e o acompanhamento da implementação de programas de intervenção físico-territoriais de desenvolvimento urbano; a proposição de normas e diretrizes para implementação de programas de reordenamento da paisagem urbana; a gestão das operações urbanas e o acompanhamento dos projetos básicos e executivos das obras e intervenções.</p>

		<h6>xi.	Secretaria Municipal de Infraestrutura Urbana e Obras (SIURB)  </h6>

		<p>A SIURB tem por atribuições a fiscalização dos contratos para execução de projetos viários, sistemas de drenagem, pavimentação, geotecnia e geometria das vias; fiscalizar os contratos de obras de construção e recuperação da infraestrutura da cidade; projetar, programar, executar e fiscalizar a construção de edifícios públicos; examinar o planejamento de obras e serviços que venham a se desenvolver nas vias e logradouros públicos e executar obras de recuperação estrutural e construção de pontes e viadutos.</p>

		<h6>xii.	São Paulo Obras (SP Obras)</h6>

		<p>A SP Obras é uma empresa pública, cuja autorização para criação foi dada pela Lei Municipal nº 15.056/2009. Tem por objetivo executar programas, projetos e obras com recursos advindos do orçamento municipal, dos financiamentos públicos e das operações urbanas. A SP Obras elabora também licitações para outros órgãos da Administração Municipal e executa obras definidas pela SIURB nas áreas de abrangência das Operações Urbanas. Por fim, destaca-se sua atribuição de gestão da concessão de mobiliário urbano, o que inclui a instalação de abrigos em pontos de ônibus e indicativos de parada de ônibus.</p>

		<h6>xiii.	Secretaria Municipal de Segurança Urbana (SMSU) e Guarda Civil Metropolitana (GCM)</h6>

		<p>Por meio da Lei Municipal nº 13.396/2002, criou-se a SMSU, que tem como uma de suas atribuições estabelecer, em conjunto com a SMT, mediante convênio firmado com os órgãos de segurança estaduais, as diretrizes, o gerenciamento e as prioridades de policiamento, controle e fiscalização do trânsito, além de ser responsável também por planejar, fixar diretrizes, coordenar e executar a fiscalização e o policiamento de trânsito de competência do município. A GCM, subordinada à SMSU, é o principal órgão de execução da política municipal de segurança urbana.</p>

		<h6>xiv.	Secretaria Municipal da Pessoa com Deficiência (SMPED)</h6>

		<p>Pioneira no Brasil, a SMPED iniciou suas atividades em 2005, sendo oficializada com a aprovação da Lei Municipal nº 14.659/2007. A SMPED tem a missão de conduzir e executar ações governamentais voltadas à implementação de políticas para as pessoas com deficiência nos diferentes órgãos municipais. A Secretaria objetiva promover a transformação social necessária à inclusão das pessoas com deficiência. Assim, compete a ela conduzir, executar e articular as ações governamentais entre os órgãos e entidades da PMSP e os diversos setores da sociedade, visando à implementação da política municipal para as pessoas com deficiência.</p>

		<h6>xv.	Secretaria Municipal das Subprefeituras (SMSUB)</h6>

		<p>A SMSUB tem como objetivo realizar o acompanhamento gerencial das metas e atividades das Subprefeituras e avaliar o cumprimento das diretrizes gerais e setoriais na gestão regional exercida pelas Subprefeituras. Cada uma das 32 Subprefeituras do município tem como atribuição manter a representação do poder público municipal na área geográfica sob sua jurisdição; fiscalizar o cumprimento das leis, regulamentos, normas e posturas municipais; conservar as áreas públicas ajardinadas (praças e canteiros); executar ou contratar pequenas obras e serviços públicos de manutenção de logradouros; acompanhar e fiscalizar os serviços de zeladoria e acompanhar os serviços relacionados ao pavimento viário (ações de tapa-buraco e recapeamento).</p>

		<h6>xvi.	Secretaria Municipal de Educação (SME)</h6>

			<p>A Secretaria Municipal de Educação (SME) tem por finalidade formular, coordenar,
				implementar e avaliar políticas e estratégias educacionais para o Sistema Municipal de Ensino;
				promover articulações com os conselhos e fundos relacionados e estabelecer normas e
				diretrizes para a Rede Municipal de Ensino.</p>
		<h4>2.	Comitê Permanente de Segurança Viária do Município de São Paulo (CPSV)</h4>

			<p>Instituído pelas portarias 001/SMT/2018, 004/SMT/2018 e 013/SMT/2018, o CPSV é a instância vinculada ao gabinete da SMT responsável pelas políticas públicas de segurança viária do município. Suas competências são propor as diretrizes da política de segurança viária da cidade; desenvolver e planejar ações, programas, campanhas educativas e demais providências necessárias à redução das ocorrências de trânsito com e sem vítima e da violência no trânsito; propor medidas voltadas à intensificação da fiscalização e da educação no trânsito; definir ações práticas para a execução das diretrizes e metas da política de segurança viária do município e acompanhar e fiscalizar a execução das ações e o alcance das metas estabelecidas.</p>
		<p>O comitê é composto pelos seguintes órgãos: Secretaria Municipal de Mobilidade e Transportes (SMT); Departamento de Operação do Sistema Viário (DSV), Departamento de Transportes Públicos (DTP), Companhia de Engenharia de Tráfego (CET), São Paulo Transportes (SPTrans); Secretaria Municipal de Segurança Urbana (SMSU), Guarda Civil Metropolitana (GCM); Serviço de Atendimento Móvel de Urgência (SAMU); Coordenadoria de Vigilância em Saúde (COVISA); Secretaria Municipal de Infraestrutura Urbana e Obras (SIURB); São Paulo Obras (SP OBRAS); Secretaria Municipal de Urbanismo e Licenciamento (SMUL); São Paulo Urbanismo (SP Urbanismo); Secretaria Municipal da Pessoa com Deficiência (SMPED); Secretaria Municipal do Trabalho e Empreendedorismo (SMTE); Secretaria Municipal de Educação (SME); Secretaria Municipal das Subprefeituras (SMSUB); Departamento Estadual de Trânsito de São Paulo (DETRAN SP);  Comando de Policiamento de Trânsito da Polícia Militar de São Paulo (CPTRAN); Agência Reguladora de Serviços Públicos Delegados de Transporte do Estado de São Paulo (Artesp) e  Departamento de Estradas de Rodagem do Estado de São Paulo (DER). A elaboração deste Plano de Segurança Viária é a primeira ação concreta do comitê que, pelo seu caráter ainda recente, requer tempo de maturação, divulgação e consolidação.</p>

		<h4>3.	Plano de Mobilidade de São Paulo  (PlanMob)</h4>

		<p>O Plano de Mobilidade de São Paulo foi instituído pelo Decreto Municipal nº 56.834/2016 e constitui-se em instrumento de planejamento e gestão da mobilidade municipal. Sua promulgação decorre de obrigação prevista na Lei Federal nº 12.587 (Política Nacional de Mobilidade Urbana - PNMU).</p>
		<p>O PlanMob traz uma série de metas e ações a serem empreendidas pelo poder público municipal para o período entre 2016 e 2030. As propostas abordam os temas pedestres; bicicletas; transporte coletivo público; transporte coletivo privado; transporte escolar; transporte de carga; segurança viária, estacionamento; transporte individual, táxi e gestão ambiental. Apesar de ser documento relevante para a política pública municipal, verifica-se que o documento precisa ser melhor difundido pelos corpos técnicos da PMSP e suas ações e metas requerem monitoramento ativo.</p>
		<p>O plano tem entre seus princípios a acessibilidade universal e segurança nos deslocamentos. Já alguns de seus objetivos são implementar ambiente adequado ao deslocamento dos modos ativos, consolidar a gestão democrática no aprimoramento da mobilidade urbana; reduzir o número de acidentes e mortes no trânsito;  reduzir o tempo médio das viagens e ampliar o uso do coletivo na matriz de transporte da cidade. O PlanMob reitera o que já está consagrado na Política Nacional de Mobilidade Urbana: a promoção de uma cidade sustentável, acessível, orientada ao transporte público e com prioridade à mobilidade ativa.</p>
		<p>Especificamente em relação à segurança viária, o decreto institui como objetivos a prioridade aos pedestres e aos modos ativos; a mitigação dos custos ambientais e sociais; a redução do número de acidentes e mortes no trânsito e a implementação de ambiente seguro ao deslocamento dos modos ativos.</p>
		<p>Para cumprimento dessas finalidades, o PlanMob traça uma série de metas específicas. Para os anos de 2015 e 2016, prevê-se a implantação das Áreas 40 e dos bolsões para motocicletas em cruzamentos (Frente segura); a redução da velocidade máxima para 50 km/h nas vias arteriais de tipo 1 (vias com cruzamentos semaforizados, uma ou duas pistas, predominância de tráfego de passagem e ligação entre regiões distantes da cidade); a adequação dos cronogramas de implantação de radares de fiscalização eletrônica de velocidade e a avaliação das implantações das Áreas 40, de modo a replicá-las em novas regiões.  </p>
		<p>Para 2017, a meta é a realização de “auditorias de segurança em vias da rede estrutural”, que em resumo consiste na análise das vias com mais acidentes, identificação de causas e elaboração de projetos de intervenção. A implantação destes projetos constitui-se como a meta de 2018.</p>
		<p>Já para 2021, prevê-se que a SMT avalie os resultados das ações durante a década anterior e defina novas metas e novas estratégias para redução de vítimas. Neste sentido, a elaboração deste Plano de Segurança Viária constitui-se no próprio cumprimento desta meta.</p>
		<p>Ademais, são definidas como atividades permanentes de segurança, a instituição de “projetos de segurança rotineiros e de curto prazo (...) e implantação de soluções para problemas de segurança e redução de vítimas como ampliação de passeios, revisão e realocação de faixas de travessia, encurtamento de distâncias de travessia e projetos de geometria para diminuição de velocidade”.</p>
		<p>Por fim, para além destas metas específicas, o PlanMob institui como meta geral o atingimento da marca de 3 mortes a cada 100 mil habitantes até o fim de 2028, corroborada como meta deste plano.</p>

		<h4>4.	Governança sobre as calçadas</h4>

		<p>Segundo estudo realizado pela SP Urbanismo, de todas as calçadas da cidade, a manutenção e execução cabe ao poder público para apenas 16% delas (em área = 8,3 milhões m²) . Aos 84% restantes (43,7 milhões m²), a execução e manutenção cabem ao proprietário do lote lindeiro, apesar de todas elas serem consideradas espaços públicos.</p>
		<slot name='m8'></slot>
		<p>Segundo a lei municipal 15.442 de 2011, “os responsáveis por imóveis, edificados ou não, lindeiros a vias ou logradouros públicos dotados de guias e sarjetas, são obrigados a executar, manter e conservar os respectivos passeios na extensão correspondente à sua testada”, sendo a prefeitura responsável pela execução das calçadas lindeiras aos próprios municipais.</p>
		<p>Além das obrigações definidas por esta lei de 2011, o poder público municipal também é responsável pela padronização das calçadas que compõem as rotas emergenciais, segundo a Lei Municipal 14.675/2008 que institui o Plano Emergencial de Calçadas -(PEC) ilustrado na imagem abaixo. </p>
		<slot name='m9'></slot>
		<p>As rotas priorizam padronizar as calçadas dos centros de cada subprefeitura, que são as vias onde há maior concentração de locais de prestação de serviços públicos e privados, pontos comerciais e do sistema transporte público coletivo. A atualização da relação de calçadas que compõem as rotas e a consequente execução dessa padronização é fundamental para garantir acessibilidade universal aos equipamentos da cidade. </p>
		<p>dentro dessa lógica se concentra a produção da maior parte das calçadas do município: construídas e mantidas por proprietários dos lotes contíguos e fiscalizada pela Prefeitura.</p>
			<p>Tal divisão administrativa acabou por transformar as calçadas em espaços residuais, sem detalhamento ou exigências de infraestrutura, e com fiscalização altamente complexa e custosa. Somado a isso, dezenas de órgãos têm algum tipo de atribuição que implica em intervenção sobre a calçada, tais como a instalação de postes de fiação, de luz, de radares, semáforos, árvores, bancos, rampas de acessibilidade, lixeiras, telefones públicos, bancas de jornal, etc..</p>
		<p>Em atendimento a uma das diretrizes do PlanMob, e considerando a importância de padronizar as calçadas e passeios para a melhoria da mobilidade e da qualidade de vida dos munícipes, com vistas a permitir o deslocamento de qualquer pessoa, bem como favorecer as interações sociais e valorizar o ambiente urbano, foi instituída, através do Decreto Municipal 57.627/2017, a Comissão Permanente de Calçadas (CPC), modificada pelo Decreto 58.194/2018, tendo como umas das suas atribuições propor normas, definir o padrão arquitetônico que deverá ser seguido, participar do planejamento e da execução do Plano Emergencial de Calçadas (PEC). A CPC é uma das poucas comissões vinculadas diretamente ao Gabinete do Prefeito e é composta por um representante permanente dos seguintes órgãos e entidades: Secretaria Municipal das Subprefeituras (SMSUB), Secretaria Municipal da Pessoa com Deficiência (SMPED), Secretaria Municipal de Serviços e Obras (SMSO), Secretaria Municipal de Urbanismo e Licenciamento (SMUL),  Secretaria Municipal do Verde e do Meio Ambiente (SVMA),  Secretaria Municipal de Mobilidade e Transportes (SMT), Companhia de Engenharia de Tráfego (CET), Comissão Permanente de Acessibilidade (CPA), São Paulo Urbanismo (SP Urbanismo), São Paulo Obras (SP Obras), Departamento de Iluminação Pública (ILUME), e Empresa Metropolitana de Planejamento da Grande São Paulo S/A (EMPLASA), além de um representante do Gabinete do Prefeito.</p>
		<p>A CPC é responsável pela orientação à realização das obras necessárias à reforma ou construção de passeios que não atendam as normas previstas na legislação municipal pertinente, inclusive no tocante à acessibilidade e à circulação de pedestres com segurança.</p>
		<p>Parte das regras atuais atinentes às calçadas encontram-se na Lei Municipal 15.442/2011, que dispõe sobre a construção e manutenção dos passeios, na Lei Municipal 13.293/2002, que trata das calçadas verdes, e no Estatuto do Pedestre (Lei Municipal 16.673/2018). Outras regras estavam espalhadas em diversas regulamentações, motivo pelo qual um novo Decreto das Calçadas está sendo elaborado pela CPC, de modo a consolidá-las em um único documento, dando critérios para a padronização das calçadas, regulamentando os incisos VII e VIII do “caput” do artigo 240 do PDE, o Capítulo III da Lei Municipal n° 15.442/2011 e a Lei Municipal  n° 13.293/2002. O novo decreto está de acordo com as diretrizes previstas no artigo 233 do PDE, de acordo com o qual a execução, manutenção e conservação das calçadas, bem como a instalação de mobiliário urbano, equipamentos de infraestrutura urbana, sinalização, vegetação, entre outras interferências permitidas por lei, deverão seguir os princípios da acessibilidade e desenho universal.</p>
		<p>Porém, apesar das legislações que parametrizam o como as calçadas devem ser construídas, o processo de concessão do Habite-se não avalia a adequação da calçada implantada. Outro ponto de atenção é o de que o processo de manutenção e revitalização de calçadas foi historicamente disparado por demanda, sem uma lógica pré-determinada e claramente delimitada quando da escolha de quais calçadas revitalizar. A CPC tem buscado reverter essa lógica, por meio do planejamento das requalificações.</p>

		<h4>5.	Responsabilidades e fluxo de procedimentos no desenvolvimento de projetos e na implantação de obras viárias</h4>

		<p>Diante da realidade da urbanização historicamente voltada ao veículo automotor, a cidade de São Paulo está passando por uma mudança de paradigma cultural, ainda que em fase embrionária, da redescoberta dos modos ativos de mobilidade. Essa mudança tem começado a afetar os projetos viários, o que traz por consequência a priorização das infraestruturas voltadas ao pedestre, ciclista e transporte coletivo.</p>
		<p>Tendo em vista o histórico e a realidade da cidade já construída ao longo de décadas, o maior ponto de dificuldade para implantar os projetos viários necessários ao município é a vasta necessidade de desapropriações, as quais são muito custosas.</p>
		<p>A articulação interorganizacional dos órgãos da PMSP na elaboração de projetos e implementação de obras viárias também é um dos pontos críticos relativos às políticas de segurança viária do município. Uma obra viária afeta substancialmente o território sob diversos pontos de vista (mobilidade, meio ambiente, habitação, etc.). Logo, o processo de elaboração dos projetos requer a interlocução e análise de diferentes órgãos municipais, o que complexifica seu processo de construção. Soma-se a isso os ainda mais complexos processos orçamentários, de licitação e de desapropriação, cujas dezenas de procedimentos devem ser meticulosamente bem articulados para que todas as fases, desde a concepção, definição de diretrizes, planejamento e efetivação de desapropriações, contratação das diversas fases de projeto e de implantação da obra corram sem atrasos e de modo a garantir intervenções capazes de melhorar a infraestrutura urbana e garantir a segurança viária.</p>
		<p>Tal complexidade implica, muitas vezes, em procedimentos não lineares e que resultam em intervenções que, a depender do como se deu o processo de elaboração, terão maior ou menor nível de adequação. A falta de alinhamento entre os diferentes órgãos desde o início implica em excessivas modificações em alguns projetos, e, a depender da etapa de projeto, passa a não mais ser possível a realização de ajustes necessários.</p>
		<p>Outro fator é a necessidade de coletar e disseminar dados pós-implantação, com o objetivo de avaliar o impacto dos projetos implantados. Tais informações podem retroalimentar a elaboração dos novos projetos, visando a tomada de decisões baseada em evidência.</p>
		<p>Especificamente em relação à segurança viária, a auditoria de segurança viária em projetos ainda não é uma prática adotada pela PMSP.</p>

		<h4>6.	Acessibilidade: governança e transversalidade</h4>

		<p>De acordo com o Censo 2010, no município de São Paulo, 2.759.004 milhões de pessoas  (24,5% da população) declararam possuir algum tipo de deficiência e, entre estes, 810 mil afirmaram ter grande dificuldade ou não conseguir realizar atividades cotidianas. Aproximadamente 345 mil pessoas são cegas ou possuem grande dificuldade para enxergar, cerca de 120 mil possuem deficiência auditiva severa, 216 mil têm deficiência motora grave e 127 mil, deficiência mental/intelectual que afeta significativamente a vida cotidiana.</p>
		<p>Este quadro explicita a relevância da missão e das políticas públicas promovidas pela SMPED. Porém, tendo vista ser a acessibilidade um tema necessariamente transversal, a governança sobre o tema não recai apenas sobre a secretaria, mas também sobre uma série de comissões, grupos e comitês dos quais o órgão faz parte. Entre eles, destaca-se a Comissão Permanente de Acessibilidade (CPA), órgão colegiado da PMSP, vinculado à SMPED e composto por representantes de diversas secretarias, órgãos municipais e sociedade civil. Foi instituída originalmente pelo Decreto 36.072/1996 e teve recente alteração pelo Decreto Municipal nº 58.031/2017. A CPA tem papel consultivo e deliberativo nos assuntos que envolvem acessibilidade em edificações, logradouros, transporte, mobiliário e equipamentos urbanos, comunicação, sinalizações, bem como nos meios de divulgação de informações, inclusive digitais.</p>
		<p>Entre as competência da CPA, destacam-se as atribuições para deliberar sobre: propostas de intervenção nos equipamentos e serviços públicos municipais e de uso coletivo; projetos de edificação, de transportes coletivos e de obras em espaços públicos; propostas de adaptação da frota de transporte público e acessibilidade digital no âmbito da PMSP. Ademais, a CPA exerce o controle da acessibilidade, por meio do exame de irregularidades em diversos locais e acionamento dos órgãos competentes para aplicação de penalização.</p>
		<p>Do ponto de vista da segurança viária, a CPA cumpre o papel de proteção ao direito de mobilidade da pessoa com deficiência, bem como de sua segurança e, à medida que ela exerce o poder de veto sobre obras públicas não acessíveis, consequentemente acaba por garantir melhores condições de segurança não só às pessoas com deficiência, mas a todos os pedestres das mais diversas idades e habilidades.</p>

		<h4>7.	Instâncias de participação social</h4>

		<h5>a.	CMTT</h5>

		<p>O Conselho Municipal de Transporte e Trânsito (CMTT) é a instância municipal que propicia a participação e o controle social sobre as políticas públicas de mobilidade na cidade.</p>
		<p>Foi criado pelo Decreto 54.058/2013, modificado pelos Decretos 55.180/2014 e 56.995/2016, e é formado por três bancadas: poder público, operadores dos serviços de transporte e usuários. Tem composição tripartite e paritária, composto por 63 membros, sendo 21 titulares e 21 suplentes para cada segmento. As duas primeiras bancadas são constituídas respectivamente a partir de indicação dos órgãos públicos e das entidades representativas dos setores. Já a dos usuários é oriunda de eleição a cada dois anos.</p>
		<p>Pela bancada dos usuários, das 21 cadeiras, dez representam geograficamente a cidade, sendo dois membros por região (norte, sul, leste, oeste e centro) e onze representam os temas ligados ao trânsito e transporte: meio ambiente e saúde, juventude, sindicato dos trabalhadores, organizações não governamentais (ONGs), ciclistas, pessoas com deficiência, idosos, movimento estudantil secundarista, movimento estudantil universitário, movimentos sociais e mobilidade a pé.</p>
		<p>O CMTT tem regimento próprio e agenda mensal com reuniões presididas pelo Secretário Municipal de Mobilidade e Transporte. As pautas são decididas pela Executiva do Conselho, composta por dois membros de cada bancada em uma reunião sempre duas semanas antes da reunião ordinária do Conselho.</p>
		<p>O Plano Municipal de Mobilidade Urbana (PlanMob), instituído pelo Decreto 56.834/2016, aponta em seu 18º artigo que o CMTT é a instância onde será exercida a participação popular, reforçando a importância do conselho.</p>
		<p>Apesar da consistência legal e lastro institucional que o CMTT possui, este é um dos mais jovens conselhos da administração municipal. Por ser uma instância muito recente, está em constante processo de consolidação e aprimoramento. Seu caráter consultivo se apresenta como termômetro para o tomador de decisão, que pode encontrar nas contribuições de seus conselheiros subsídios para encaminhar ou desestimular um determinado projeto. Os assuntos tratados são as pautas consideradas pertinentes no momento da realização da reunião ordinária.</p>
		<p>As pautas propostas são importantes à qualidade de vida dos paulistanos, razão pela qual é fundamental reforçar a necessidade do comparecimento e participação de todos os conselheiros nas reuniões ordinárias do conselho, tanto quanto nas suas respectivas Câmaras Temáticas, pois o CMTT é um fórum bastante rico e diverso, que se propõe a contemplar a complexidade das pautas e agentes envolvidos no ecossistema da mobilidade urbana paulistana</p>

		<h6>i.	Câmaras Temáticas: Mobilidade a Pé, Bicicleta, Transporte Escolar Táxi e Moto</h6>

		<p>Vinculadas ao CMTT, as câmaras temáticas são fóruns criados para tratar especificamente sobre determinado setor ou serviço da mobilidade paulistana.</p>
		<p>Atualmente o CMTT possui cinco câmaras temáticas: bicicleta, mobilidade a pé, transporte escolar, táxi e moto. Cada uma delas possui regimento interno e agenda próprios, que variam de acordo com as demandas de seus membros. O intuito das câmaras temáticas é propiciar um diálogo aprofundado entre os técnicos da SMT e o segmento interessado, proporcionando a troca de visões sobre um mesmo tema.</p>
		<p>As câmaras temáticas mais atuantes são as ligadas à mobilidade ativa - bicicleta e mobilidade a pé - cujas reuniões são mensais e seus membros bastante engajados. Delas saíram muitos projetos e discussões para o desenvolvimento do caminhar e do pedalar na cidade.</p>
		<p>A Câmara Temática do Transporte Escolar é bimensal e busca, juntamente com o apoio da SME e do DTP, aprimorar as questões referentes aos deslocamentos dos alunos, tanto da rede pública quanto particular da cidade.</p>
		<p>A Câmara Temática do Serviço de Táxi também é bimensal e busca majoritariamente aprimorar o serviço que foi impactado com a chegada dos aplicativos.</p>
		<p>A mais nova Câmara Temática vinculada ao CMTT é a de motocicletas que ainda está em fase de consolidação, tendo sido sua criação aprovada em maio de 2018.</p>

		<h5>b.	Conselho Municipal da Pessoa Com Deficiência (CPD)</h5>

		<p>O Conselho Municipal da Pessoa com Deficiência (CMPD) é o órgão de representação da sociedade civil perante à PMSP. Por ser de caráter consultivo, sua função é elaborar, encaminhar e acompanhar a implementação de políticas públicas de interesse da pessoa com deficiência nas áreas da saúde, educação, trabalho, habitação, transporte, cultura, lazer, esportes e acessibilidade nos espaços públicos. Por meio de plenárias mensais abertas ao público, grupos de trabalho e fóruns regionais, todas as pessoas com deficiência residentes em São Paulo podem se cadastrar no conselho e participar de suas atividades com direito a voz e voto.</p>

		<h5>c.	Conselhos de Segurança - CONSEGs</h5>

		<p>Os Conselhos de Segurança (CONSEGs) foram criados através do Decreto Estadual nº 23.455/1985 e regulamentado pela Resolução SSP-37/1985. Cada Conselho é uma entidade de apoio à Polícia Estadual nas relações comunitárias, e se vinculam, por adesão, às diretrizes da Secretaria de Segurança Pública, por intermédio do Coordenador Estadual dos Conselhos Comunitários de Segurança.</p>
		<p>Atualmente são 84 CONSEGs na capital. As reuniões ordinárias de cada conselho são mensais, realizadas normalmente no período noturno, em imóveis de uso comunitário, segundo uma agenda definida por período anual. A Secretaria de Segurança Pública tem como representantes em cada CONSEG o Comandante da Polícia Militar da área e o Delegado de Polícia Titular do correspondente Distrito Policial.</p>
		<p>Nos CONSEGs, pessoas do mesmo bairro se reúnem para discutir e analisar, planejar e acompanhar a solução de seus problemas comunitários de segurança, desenvolver campanhas educativas e estreitar laços de entendimento e cooperação entre as várias lideranças locais. Dentre os elementos de segurança viária demandados pelos CONSEGs, destacam-se lombadas e sinalização.</p>
		<p>Diagnostica-se a necessidade de melhor utilização dos CONSEGs para divulgação e discussão da segurança viária junto às comunidades locais.</p>

		<h4>8.	Normatização relativa aos Sistemas de Gestão de Segurança Viária (ISO 39.001)</h4>

		<p>No contexto de conscientização global sobre o problema da segurança viária, os organismos internacionais de normalização publicaram a norma ISO 39.001 (Sistemas de Gestão Segurança Viária), cujo objetivo é especificar os requisitos para um sistema de gestão de segurança viária que permita a uma organização que interage com o sistema viário reduzir mortes e ferimentos graves em acidentes de trânsito. A norma trata da criação de um sistema de gestão de segurança viária pela organização, incluindo o planejamento, exercício de liderança e a instauração de uma política de segurança.</p>
		<p>Apesar da ISO 39.0001 ser de 2012, são raras as empresas que têm instaurados os procedimentos da norma, situação que se observa também no setor público. No âmbito municipal, CET e SPTrans iniciaram seus processos de implementação da ISO 39001, porém seus avanços ainda encontram-se em estágio inicial.</p>
		<p>A relevância da implementação da norma nas empresas pode ser percebida pelo número de acidentes de trabalho relativos aos transportes. De acordo com dados do Observatório Digital de Saúde e Segurança do Trabalho<a title="  Disponível em https://observatoriosst.mpt.mp.br/. Acesso em 31/07/2018." href='https://observatoriosst.mpt.mp.br/' style='cursor: help;' target="_blank"><sup>22</sup></a>, a motocicleta foi o principal agente causador de acidentes de trabalho entre 2012 e 2017, representando 7% do total de no período. Já o veículo rodoviário motorizado foi a terceira causa, correspondendo a 5% do total. Já de acordo com o Ministério da Saúde, “o número de notificações de acidentes de transporte relacionados ao trabalho aumentou quase seis vezes, passando de 2.798 em 2007 para 18.706 em 2016” (...) Na contramão deste aumento, os óbitos, neste caso, caíram 28% no mesmo período, saindo de 1.447 para 1.393, em 2016 <a title="  Disponível em http://portalms.saude.gov.br/noticias/agencia-saude/43893-motociclistas-e-caminhoneiros-sofrem-mais-acidentes-de-transito-no-trabalho-2. Acesso em 31/07/2018" href='http://portalms.saude.gov.br/noticias/agencia-saude/43893-motociclistas-e-caminhoneiros-sofrem-mais-acidentes-de-transito-no-trabalho-2' style='cursor: help;' target="_blank"><sup>23</sup></a>.</p>
		<h4>9.	Fontes de Recurso e Fundos Municipais</h4>

		<p>Assim como em qualquer política pública, o orçamento público e alocação de recursos são indispensáveis para a implementação das ações e programas. No âmbito municipal, a segurança viária está presente em três programas do Plano Plurianual (PPA): Ações e serviços de saúde, Direitos da pessoa com deficiência e Melhoria da mobilidade urbana universal. Na tabela abaixo, estão apresentados os programas e respectivas ações orçamentárias relacionadas ao tema, bem como os valores previstos para cada uma delas <a title="  Disponível em http://transparencia.prefeitura.sp.gov.br/contas/Paginas/PlanoPlurianual.aspx. Acesso em 22/06/2018." href='http://transparencia.prefeitura.sp.gov.br/contas/Paginas/PlanoPlurianual.aspx' style='cursor: help;' target="_blank"><sup>24</sup></a>.</p>
		<slot name="tabela9"></slot>
		<p>No que se refere às fontes de recursos, para além do tesouro municipal, existem três fundos por meio dos quais ações voltadas à segurança viária podem ser viabilizadas. Importante explicitar que, em acordo com o Art. 1º do Decreto Municipal 57.380/2016, 30% das receitas correntes dos fundos administrados pelo poder executivo municipal passaram a estar desvinculadas, podendo ser utilizadas para quaisquer finalidades.</p>
		<p>O primeiro é o Fundo Municipal de Desenvolvimento de Trânsito (FMDT), instituído pela Lei Municipal 14.488/2007 e regulado pelos Decretos Municipais 49.399/2008 e 51.877/2010. Para além das normas acima, a aplicações das receitas devem ainda seguir o estipulado na Resolução CONTRAN 638/16. O fundo é gerido pela SMT e, de acordo com a lei, seus recursos devem ser aplicados exclusivamente no desenvolvimento do trânsito, visando desenvolver as atividades de (i) sinalização; (ii) engenharia de tráfego e de campo; (iii) policiamento e fiscalização e (iv) educação de trânsito. Já as suas receitas são majoritariamente a arrecadação das multas previstas na legislação de trânsito e transferências ou repasses financeiros oriundos de convênios destinados à execução de planos e programas de interesse comum no âmbito do trânsito e do tráfego da cidade.</p>
		<p>O segundo é o Fundo de Desenvolvimento Urbano (FUNDURB), previsto no Plano Diretor Estratégico (PDE) do município e regulamento pelo Decreto 57.547/2016. Seus recursos devem ser aplicados em programas e projetos urbanísticos e ambientais integrantes ou decorrentes do PDE e tendo como referência o previsto no Programa de Metas do município. A lei cria seis prioridades na utilização dos recursos, sendo uma delas  os sistemas de transporte coletivo público, cicloviário e de circulação de pedestres. No mínimo 30% dos recursos do fundo devem ser aplicados nestes sistemas. Quanto às receitas, são três as principais: (i) as decorrentes de outorga onerosa e transferência de potencial construtivo; (ii) a contribuição de melhoria decorrente de obras públicas e (iii) as provenientes de concessão urbanística.</p>
		<p>Por fim, o Fundo Especial de Meio Ambiente e Desenvolvimento Sustentável (FEMA) foi criado pela Lei Municipal nº 13.155/2001 com nova disciplina pela Lei  Municipal nº 14.887/2009, vinculado à Secretaria Municipal do Verde e do Meio Ambiente (SVMA). É regulamentado pelos Decretos 52.153/2001 e 52.388/2001. Seus principais recursos provêm de multas impostas por infrações à legislação ambiental, de Termos de Compromisso Ambiental (TCA), de Termos de Ajustamento de Conduta (TAC) e de receitas advindas de créditos de carbono. Já entre a destinação dos valores, encontra-se o apoio ao desenvolvimento de planos, programas e projetos de manutenção, melhoria e/ou recuperação da qualidade ambiental. Deste modo, o FEMA pode ser utilizado à infraestrutura cicloviária, com vistas à diminuição do uso de veículos automotores e da consequente redução de emissão de poluentes atmosféricos.</p>
		<p>Para além dos fundos, existem outras fontes de recurso para as ações de segurança viária, com destaque às parcerias e doações pela iniciativa privada, em especial nas datas relacionadas ao tema, como durante o mês de maio, no Maio Amarelo, e na Semana da Mobilidade, em setembro. Também é possível destacar os valores oriundos de Operações Urbanas Consorciadas advindos da compra pelos particulares do direito de construir acima do coeficiente básico de construção de um lote. Vale ressaltar que esses recursos são atrelados ao território e aos projetos urbanos e melhoramentos viários propostos pela própria operação. Para melhoria da segurança viária, os investimentos devem ser prioritariamente voltados à infraestrutura de suporte à mobilidade ativa e transporte coletivo.</p>

	</div>
</template>

<script>
export default {
	name: 'Cap2CEixoI'
}
</script>
