<template>
	<div class="Cap2CEixoVII">
<h5>1.	Introdução: abordagem sobre as ações educacionais e de comunicação, de acordo visão zero e sistemas seguros</h5>
<p>Apesar de a educação sobre segurança viária ser importante à segurança viária, são necessários alguns cuidados ao abordar o tema, especialmente no que se refere ao pensamento de que o comportamento dos indivíduos no trânsito é fruto exclusivo da educação pessoal do sujeito. A educação tem um importante potencial de transformação da cultura no longo prazo e a sociedade reconhece isso. No entanto, a abordagem baseada no foco excessivo sobre o indivíduo, ignorando que o modo de agir das pessoas no trânsito é fruto de um conjunto de determinantes que criam estímulos e desestímulos aos comportamentos pode levar a ações educacionais infrutíferas e não condizentes com os princípios da visão zero e sistemas seguros.</p>

<h5>2.	Ressignificação do termo “acidente”</h5>
<p>As ações de comunicação relacionadas à segurança viária passam pela própria discussão do termo “acidente de trânsito” e o que o caracteriza. De acordo com a NBR 10697 de 06/1989<a title="  ABNT (Associação Brasileira de Normas e Técnicas) " style='cursor: help;'><sup>46</sup></a>, um acidente de trânsito, por definição, configura-se como "todo evento não premeditado de que resulte dano em veículo ou na sua carga e/ou lesões em pessoas e/ou animais, em que pelo menos uma das partes está em movimento nas vias terrestres ou áreas abertas ao público". No âmbito internacional, a OMS (Organização Mundial da Saúde) <a title="  World Health Day: Road safety is no accident!. Disponível em http://www.who.int/mediacentre/news/releases/2004/pr24/en/. Acesso em 19/06/2018 " href='http://www.who.int/mediacentre/news/releases/2004/pr24/en/' style='cursor: help;' target="_blank"><sup>47</sup></a> e seus parceiros passaram a promover o conceito de que a palavra "acidente" não se aplica quando se refere ao trânsito, pois parte do princípio de que se trata de algo que aconteceu devido a um infortúnio, quando em realidade poderia ter sido evitado. Por isso, o termo road crash tem sido adotado em inglês. No Brasil, o debate em torno do tema ainda é pouco explorado, requerendo ainda a definição e divulgação de um novo termo.</p>

<h5>3.	Campanhas de massa</h5>
<p>Campanhas de mídia de massa (OMS, 2016) podem desempenhar um papel importante nos programas de segurança no trânsito quando efetivamente combinadas com a legislação específica e fiscalização. Melhorar o comportamento dos usuários nas vias é fundamental para reduzir o número de mortos e feridos no trânsito e é, inclusive, um dos pilares do plano global para a Década de Ação pela Segurança no Trânsito 2011–2020 da ONU.</p>
<p>Os casos de sucesso internacionais sugerem um ciclo de desenvolvimento para as campanhas organizado em quatro fases: desenho do projeto e pesquisa, produção, disseminação e avaliação. De acordo com a própria recomendação da ONU, as campanhas sozinhas não mudam comportamentos se forem produzidas isoladamente ou disseminadas de forma descontínua. Portanto, é importante desenvolvê-las em associação com outras medidas de prevenção e monitoramento rigoroso. Tal metodologia ainda não foi aplicada pela cidade de São Paulo.</p>

<h5>4.	O olhar sobre os agentes de trânsito e a “indústria da multa”</h5>
<p>Os agentes de fiscalização de trânsito cumprem papel essencial na proteção à vida, tendo em vista a inibição que geram sobre comportamentos arriscados. Porém, apesar da importante função, eles são vistos de forma negativa pela população em geral, por serem agentes autuadores de multas de trânsito. Exemplo claro deste quadro é a utilização cotidiana de termos pejorativos aos agentes da CET, como “marronzinho”, ou a ocorrência de agressões a estes agentes públicos. Tais situações apontam para a necessidade de difusão da importância da fiscalização para a segurança viária e para a redução do número de mortes. Dentro desta perspectiva, verifica-se a importância de os órgãos de fiscalização de trânsito analisarem e ressignificarem sua atuação, revendo suas marcas enquanto empresa e fortalecendo o foco de sua atuação.</p>
<p>No mesmo sentido, é necessário esclarecer junto à população o papel da autuação das infrações de trânsito por meio dos equipamentos eletrônicos de fiscalização, comumente associados a uma “indústria da multa” utilizada pelas administrações públicas para arrecadação junto ao contribuinte.</p>

<h5>5.	Cultura do álcool</h5>

<p>O consumo de bebidas alcoólicas na cultura ocidental é constantemente glamourizado, alimentado principalmente pela própria indústria. Segundo a OMS (OMS, 2017), o nível mundial de consumo em 2016 foi 6,4 litros de álcool puro por pessoa com 15 anos ou mais. No Brasil, a estimativa per capita foi de 8,9 litros no mesmo período. Os dados disponíveis indicam que a cobertura de tratamento para o álcool e transtornos por uso de drogas é inadequada, embora mais trabalho seja necessário para melhorar a medição dessa cobertura. Ainda assim, é clara a associação feita entre o ato de beber e dirigir e as consequências negativas que esse tipo de comportamento traz para a saúde pública.</p>
<p>Internacionalmente, o uso de campanhas de comunicação de massa baseadas em evidências, assim como a divulgação dos malefícios do consumo exagerado de álcool por meio da imprensa, têm se mostrado bastante eficazes nas políticas públicas de redução de danos.</p>

<h5>6.	Desconhecimento sobre os serviços de emergência</h5>
<p>Outro ponto relevante relevante em relação à comunicação é o desconhecimento de parte da população paulistana em relação aos serviços de emergência prestados pelo SAMU. Destacam-se dois pontos principais: o desconhecimento e confusão em relação ao número da central de emergência 192 com as demais centrais (por exemplo, 190 da Polícia Militar); e o desconhecimento sobre a relevância e benefícios que o questionário de triagem inicial trazem à prestação dos serviços.</p>
<p>Além disso, por uma sensação de desconfiança da população em relação aos serviços públicos, muitas vezes a idoneidade do serviço do SAMU é questionada. Por exemplo, quando uma ambulância está a caminho do acidente, ou seja, ainda sem o paciente, é comum surgir a reclamação: "Vocês andam com a sirene ligada sem ninguém dentro".</p>
<p>A sirene é utilizada em duas situações básicas: a primeira é a caminho da ocorrência, como forma de abrir rota com segurança em relação aos demais veículos automotores, para chegar ao local rapidamente e iniciar o atendimento. E, também, para realizar o transporte rápido do paciente atendido, caso haja necessidade de intervenção hospitalar imediata.</p>
<p>Por conta dessas questões, é necessário que campanhas continuadas sobre os serviços prestados pelo SAMU sejam realizadas junto à população.</p>

<h5>7.	Principais ações de comunicação</h5>
<p>No âmbito nacional, o CTB estabelece em seu Art. 75 os temas e os cronogramas das campanhas que deverão ser promovidas por todos os órgãos ou entidades do Sistema Nacional de Trânsito, em especial nos períodos referentes a férias escolares, feriados prolongados e a Semana Nacional de Trânsito.</p>
<p>A Secretaria de Mobilidade e Transportes do município de São Paulo concentra suas ações de comunicação para segurança no trânsito em dois principais períodos no ano: a campanha relacionada ao Movimento Maio Amarelo, no primeiro semestre, e a Semana da Mobilidade, que ocorre durante a Semana Nacional de Trânsito, entre 18 e 25 de setembro. Em ambos os casos, o objetivo é promover ações de educação e conscientização para a segurança no trânsito. Além disso, outras atividades de comunicação para divulgar o tema podem ser adotadas, de forma pontual, ao longo do calendário anual.  </p>

<h5>8.	Comunicação e utilização dos instrumentos de transparência</h5>
<p>Um recurso de comunicação que ajuda a fomentar uma gestão mais transparente e aberta à sociedade é a abertura de dados governamentais, via web, pelo poder público. Além de ser benéfica para a própria administração, esse tipo de medida ajuda a fomentar<a title=" Iniciativas de Governo Aberto da Secretaria Municipal de Educação. Disponível em  http://patiodigital.prefeitura.sp.gov.br/project/dados-abertos-da-educacao/. Acesso em 19/06/2018." href='http://patiodigital.prefeitura.sp.gov.br/project/dados-abertos-da-educacao/' style='cursor: help;' target="_blank"><sup>48</sup></a> a pesquisa acadêmica, a inovação tecnológica e a geração de novos negócios.</p>
<p>Os dados abertos de mobilidade urbana disponibilizados pela Prefeitura de São Paulo podem ser vistos em diferentes páginas, como na do MobiLab (Laboratório de Inovação em Mobilidade da Prefeitura de São Paulo): <a href="http://mobilab.prefeitura.sp.gov.br/dadosabertos/">http://mobilab.prefeitura.sp.gov.br/dadosabertos/</a>; no portal da transparência da Prefeitura (<a href="http://transparencia.prefeitura.sp.gov.br/Paginas/home.aspx">http://transparencia.prefeitura.sp.gov.br/Paginas/home.aspx</a>) ou no Geosampa (<a href="http://geosampa.prefeitura.sp.gov.br/PaginasPublicas/_SBC.aspx">http://geosampa.prefeitura.sp.gov.br/PaginasPublicas/_SBC.aspx</a>). Porém, apesar de importantes, tais portais são pouco conhecidos pela população em geral.</p>
<p>Para além da divulgação, faz-se necessária ainda a expansão da abertura de dados sobre segurança viária e mobilidade nos próximos anos. Nesse sentido, em 2018 foi elaborada a plataforma de dados abertos do Vida Segura, que, até então, contém dados dos acidentes em 2015, 2016 e 2017  (<a href="https://vidasegura.prefeitura.sp.gov.br/plataforma/#!/login">https://vidasegura.prefeitura.sp.gov.br/plataforma/#!/login</a>).</p>

<h5>9.	A Educação de trânsito no CTB</h5>
<p>Apesar do Código de Trânsito Brasileiro (Art. 76) prever a promoção da educação no trânsito na pré escola, no ensino fundamental e no ensino médio, instituindo que os órgãos do Sistema Nacional de Trânsito e de Educação adotem currículos interdisciplinares e conteúdo programático sobre segurança no trânsito, o tema não é detalhado no CTB, tampouco em normas decorrentes. Consequentemente, há grande discricionariedade no que se refere à presença da educação de trânsito nas escolas. A base curricular do município não contempla a educação para segurança viária.</p>

<h5>10.	Ações de educação de trânsito</h5>
<p>De acordo com o Art. 74, § 1º, do CTB, “é obrigatória a existência de coordenação educacional em cada órgão ou entidade componente do Sistema Nacional de Trânsito. No município, as principais ações de educação promovidas são as descritas abaixo:</p>
<h6>a.	Ações Educacionais promovidas pelo Centro de Treinamento e Educação de Trânsito da CET (CETET)</h6>
<u>i.	Introdução</u>
<p>A CET, por meio do Centro de Treinamento e Educação de Trânsito (CETET), fundado em 1980, desenvolve ações educativas para públicos diversos (estudantes do ensino infantil à universidade, professores, condutores, terceira idade, pessoas com deficiência e público em geral), por meio de metodologias apropriadas para cada segmento e voltadas ao estímulo à reflexão e à adoção de atitudes e comportamentos seguros e éticos. É priorizada a mobilidade dos mais frágeis e a qualidade de vida dos cidadãos, entendendo que a mobilidade urbana integra os conceitos de cidadania, inclusão social, acessibilidade, segurança, meio ambiente e saúde pública. Em seus múltiplos trabalhos, o CETET busca desenvolver suas ações para todos os tipos de público, com a utilização de recursos lúdicos, como a realização de jogos e peças de teatro.</p>
<p>De modo geral, apesar das inúmeras atividades empreendidas, verifica-se a necessidade de fortalecimento das ações de educação de trânsito, expandindo a capacidade operacional e fortalecendo o engajamento das comunidades, por meio de ações educativas conjuntas às intervenções físicas realizadas nos bairros. Ademais, percebe-se também a necessidade de promoção de reciclagem das equipes promotoras das atividades, capacitando-as nas novas tecnologias disponíveis e nos novos conceitos de segurança viária alicerçados na visão zero e sistema seguro.</p>
<u>ii.	Cursos Empreendidos pelo CETET</u>
<p><strong>Capacitação de condutores:</strong> palestras, cursos e treinamentos voltados ao público adulto habilitado (como motoristas, taxistas, motociclistas, motofretistas e ciclistas), com destaque à formação de motofretistas. Isto pois o CETET é habilitado pelo DETRAN para ministrar esse curso no município de São Paulo, o qual é gratuito e obrigatório aos que desejam exercer profissionalmente esta atividade, em acordo com a Lei Federal 12.009/2009. Compete também destacar que, apesar da existência do curso, existem motofretistas que operam clandestinamente no município, o que exige atenção e permanente fiscalização por parte do poder público. Em 2017 o CETET capacitou 2.300 condutores, sendo 661 motofretistas, 896 motoristas, 653 motociclistas e 90 ciclistas.</p>
<p><strong>Educação à distância:</strong> a educação à distância promovida pelo CETET treinou em 2017  7.718 pessoas, com destaque aos cursos oferecidos a professores-multiplicadores da rede de ensino pública e particular, que atingiram 6.814 educadores. Os cursos voltados aos professores possuem carga horária de 20 horas, são homologados pela Secretaria Municipal de Educação (SME) e são voltados especialmente aos três níveis do ensino básico: educação infantil, fundamental I e II. Tais cursos objetivam preparar o professor para tornar-se um multiplicador na unidade escolar em que atua e na comunidade do entorno, em relação aos conceitos de mobilidade segura, cidadania, meio ambiente e demais assuntos correlatos à educação para a mobilidade segura e para o convívio em meio social urbano. Em relação a educação a distância, são dois os principais pontos de gargalo: as dificuldades de continuidade e renovação das plataformas digitais por meio das quais os cursos são ofertados e a necessidade de atualização das equipes técnicas.</p>
<p><strong>Atividades presenciais para público escolar:</strong> o CETET oferece também as vivências de educação de trânsito, dezenas de diferentes tipos de atividades que são agendadas e realizadas diretamente nas unidades escolares. Em 2017, foram atendidas 44.489 crianças e adolescentes no total.</p>
<p><strong>Espaço Vivencial de Trânsito Unidade Fixa Caio Graco da Silva Prado (Barra Funda):</strong> o espaço possui uma equipe de educadores especializados que promovem atividades dirigidas ao público escolar, a partir dos 6 anos até 16 anos. O espaço conta com auditório, sala digital, pista sinalizada, e conta ainda com o uso de bicicletas e carrinhos elétricos. As atividades priorizam o pedestre e a conscientização para possíveis futuros motoristas. Em 2017, o espaço recebeu 7.271 pessoas, sendo 6.958 crianças e adolescentes e 313 idosos e pessoas com deficiência.</p>
<p><strong>Ações de educação de trânsito em projetos especiais:</strong> trata-se da promoção de ações junto à comunidade do entorno de intervenções realizadas pela CET, como implantação de sinalização, alterações no viário, etc. Em 2017, foram realizadas atividades em áreas como M’Boi Segura e dentro de outras ações da CET.</p>

<h6>b.	Cursos Empreendidos pelo CPtran</h6>
<p><strong>Programa Bem-te-vi:</strong> O Clube do Bem-Te-Vi, criado em 1990, é um programa educativo de trânsito coordenado e desenvolvido por Policiais Militares do Comando de Policiamento de Trânsito, em parceria com o DETRAN SP, que tem a finalidade pedagógica de educar para o trânsito crianças que se encontram matriculadas nos estabelecimentos de ensino fundamental localizados no Estado de São Paulo, em atendimento às solicitações das prefeituras municipais ou das próprias instituições de ensino. Desde a sua criação, 4.141 escolas já foram visitadas, 47.291 professores e 1.495.899 crianças foram atendidas pelo programa.</p>
<p><strong>Projeto Teatro de Fantoches - educando para o trânsito de uma maneira divertida:</strong> trata-se de um projeto socioeducativo, criado em 2010, direcionado para crianças matriculadas nas escolas das redes pública e privada de educação infantil e dos primeiros anos do ensino fundamental, com uma faixa etária entre 4 e 10 anos de idade. Tem por objetivo transmitir, de uma forma lúdica, através de um cenário de fantasia e com personagens caricatos, noções de como se comportar no trânsito para torná-lo mais seguro. Desde a sua criação, 905 escolas foram visitadas e 248.562 crianças atendidas.</p>
<p><strong>Operação Direção Segura Educativa:</strong> Ação iniciada em 2017, com o objetivo de percorrer bares e restaurantes da capital paulista visando conscientizar e alertar os motoristas acerca dos riscos e das consequências de se misturar álcool e direção, por meio de uma abordagem educativa, que conta também com a distribuição de etilômetros descartáveis. Desde a sua criação, 243 estabelecimentos já foram visitados e mais de 7.000 motoristas já foram conscientizados.</p>
<p><strong>Ação Educativa Motociclista Seguro:</strong> ação iniciada em maio de 2018, por meio de uma parceria entre o CPTran e a CET, com o objetivo de conscientizar motociclistas sobre os riscos de se conduzir este tipo de veículo nas Marginais dos rios Tietê e Pinheiros, consideradas as maiores e mais movimentadas vias urbanas do país, bem como da importância de se respeitar as leis de trânsito, em especial não misturar álcool e direção, não ultrapassar os limites de velocidade e manter uma distância segura em relação aos demais veículos. Desde o início da ação, 126 motociclistas já foram conscientizados pela ação.</p>
<p><strong>Moto Check Up:</strong> evento institucional desenvolvido pela ABRACICLO (Associação Brasileira dos Fabricantes de Motocicletas, Ciclomotores, Motonetas, Bicicletas e Similares), em parceria com o CPTran e CET, direcionado à segurança, educação, avaliação e conscientização dos motociclistas acerca da importância da manutenção da sua motocicleta O evento avalia gratuitamente as condições mecânicas de 21 itens das motocicletas e mostra, na prática, como deve ser a pilotagem segura e defensiva. Distribui brindes aos motociclistas participantes e entrega vales que possibilitam a troca completa de óleo de suas motocicletas em concessionárias locais.</p>

<h6>c.	Amigos do SAMU</h6>
<p>Para minimizar o impacto dos trotes aplicados sobre a central 192, foi implementado o “Programa Amigos do SAMU” com o objetivo de sensibilizar as crianças e a comunidade escolar sobre a importância e os objetivos do SAMU, sua forma correta de utilização e os riscos do trote.   </p>
<p>Este programa foi colocado em prática pelo Núcleo de Educação em Urgência do SAMU 192 de São Paulo, através de seu corpo de instrutores e funcionários do próprio serviço. A atividade se inicia com uma conversa e tem como abordagem principal a realização de uma simulação de um atendimento feito pelo SAMU, feita no ambiente da própria escola e com a presença de uma ambulância real. Após a vivência, o instrutor fala sobre a importância do serviço, os riscos do trote e as consequências para todos, serviço e comunidade. De abril de 2008 até maio de 2018, foram atendidas aproximadamente 120.000 crianças em escolas públicas e privadas.</p>
<p>Os pontos fortes do projeto são a proximidade com a comunidade escolar, levando de forma lúdica as informações sobre a importância do SAMU e o risco do trote; a orientação adequada do acionamento do serviço por parte das crianças; a formação da criança como agente multiplicador das informações; a boa aceitação do programa por parte das crianças e dos educadores; e a consequente redução significativa do índice de trote de crianças ao SAMU desde a implantação do projeto. Por outro lado, o programa carece de disponibilidade de materiais de apoio, bem como sua abrangência é limitada a apenas uma atividade por semana.</p>

<h5>11.	Capacitação profissional aos agentes públicos promotores da segurança viária na cidade</h5>
<p>A visão historicamente construída e predominante em São Paulo é a da prevalência do fluxo dos veículos automotores, em detrimento à segurança viária, paradigma que precisa ser revertido. Para isso, a promoção de capacitações específicas em segurança viária condizentes com os princípio da Visão Zero e Sistemas Seguros requerem fortalecimento, em especial as voltadas aos agentes públicos que trabalham cotidianamente na rua, tais como os agentes da CET, SPTrans, EMTU, CPTran e GCM, bem como os direcionados aos servidores que elaboram, aprovam e implementam projetos e obras viárias, de modo a garantir que estes sejam implementados em pleno acordo com as boas práticas de segurança viária.</p>
<p>Como ponto de destaque positivo, compete mencionar o amplo conhecimento técnico a respeito da legislação de trânsito pelos agentes da CET, CPTran e GCM, bem como a alta especialização funcional destes corpos no que se refere às atividades de fiscalização ostensiva.</p>
<p>Especificamente em relação às capacitações atualmente oferecidas aos principais servidores relacionados à segurança viária destacam-se:</p>

<h6>a.	Agentes da CET</h6>
<p>O processo de formação inicial dos agentes de trânsito da CET é composto por diversos módulos distribuídos em mais de 300 horas de treinamento. Esses módulos têm por objetivo preparar o agente para o exercício do seu papel profissional.</p>
<slot name='tabela23'></slot>
<slot name='tabela24'></slot>
<p>Para além do treinamento básico, em 2011 a CET desenvolveu um treinamento específico, que contou com participação de todos os agentes de trânsito e que teve por objetivo criar uma cultura de respeito e proteção ao pedestre, as maiores vítimas do trânsito. Em 2016, foi desenvolvido o treinamento “Fundamentos da Segurança Viária”, com carga horária de 6 horas e com o objetivo de aperfeiçoar e direcionar os agentes para uma atuação com foco na redução de mortos e feridos nas ruas da cidade.</p>

<h6>b.	Técnicos de serviço de transporte da SPTrans</h6>
<p>Uma vez que dirigir faz parte do escopo do trabalho dos técnicos da SPTrans, todos recebem treinamento de direção defensiva. Ademais, em 2017, 100% destes servidores passaram por treinamento específico sobre a identificação de causas de acidentes de trânsito, bem como sobre como realizar a orientação e segregamento do ambiente, de modo a evitar uma nova ocorrência. Além disso, o conteúdo dos treinamentos oferecidos aos motoristas e cobradores do STCUP são também transmitidos aos técnicos da SPTrans, de modo que estes possam melhor exercer as atividades de fiscalização sobre as empresas.</p>

<h6>c.	GCMs</h6>
<p>É ofertado aos agentes da Guarda Civil Metropolitana formação específica como agente de trânsito, para atender as competências inseridas na lei 13.022 de 8 de agosto de 21014. Atualmente, cerca de 85% são formados como agentes de trânsito. Nesse tocante a fiscalização de trânsito está sendo implementado o curso de formação básico inicial da carreira, à qual todos os novos Guardas Civis serão submetidos ao curso de agente de trânsito quando do ingresso, fazendo parte da grade curricular o curso de agente de trânsito como meta a ser alcançada.</p>

<h6>d.	Policiais Militares do CPTran</h6>
<p>É ofertado curso de especialização em trânsito urbano aos agentes da Polícia Militar. O curso tem o objetivo de capacitar o Policial Militar a desempenhar com proficiência as funções específicas de policiamento ostensivo de trânsito urbano, de acordo com os parâmetros legais e as modernas técnicas de policiamento e fiscalização de trânsito. Com uma carga horária de 188 horas-aulas, o curso aborda os seguintes temas em sua grade curricular: legislação de trânsito; segurança de trânsito; engenharia e operação de trânsito; técnica de policiamento de trânsito urbano; legislação e fiscalização do transporte rodoviário de produtos perigosos; além de estágio supervisionado.</p>

<h6>e.	Capacitação dos motoristas do STCUP</h6>
<p>De acordo com a Pesquisa Satisfação dos Usuários com os Serviços de Transporte por Ônibus na Cidade de São Paulo de 2017, realizada pela SPTrans, os usuários do sistema de ônibus municipal atribuíram, em uma escala de 0 a 5, nota 3,4 ao quesito segurança na viagem (condução e velocidade), nota 3,5 para o quesito preparo dos cobradores e nota 3,4 para o quesito respeito para com idosos e pessoas com deficiência. Ademais, do  total de 35.428 reclamações recebidas pela SPTrans em 2017, 19.986, ou 56,41%, referiram-se à tripulação, ou seja, motoristas ou cobradores.</p>
<p>Tais números revelam que, se por um lado os usuários não parecem muito insatisfeitos com a condução e postura dos motoristas e cobradores de ônibus, por outro não as consideram adequadas.</p>
<p>  	Diversas frentes são necessárias para a melhoria do quadro, começando pelos processos de seleção e de desenvolvimento da carreira dos motoristas. Quanto à seleção, os requisitos mínimos para que o profissional possa dirigir um ônibus do sistema público é a obtenção de CNH categoria D ou E (de acordo com o tipo de veículo) e mínimo de seis meses de experiência comprovada, porém não são incluídas exigências tais como se o perfil do profissional (características de personalidade, habilidades e outras competências) são compatíveis com as exigências do cargo (equilíbrio emocional, resistência à frustração, habilidade interpessoal para lidar com diferentes públicos, entre outras). Ao mesmo tempo, verifica-se a tendência de que os motoristas mais bem capacitados sejam cooptados por outras empresas de transporte, pela conjunção de oferecimento de melhores salários e menores responsabilidades, o que aponta a fragilidade da carreira no sistema público de ônibus. Nesse sentido, apesar dos limites de intervenção do poder público municipal na carreira dos motoristas, uma vez que estes são funcionários privados das empresas operadoras, políticas de incentivo positivo a bons motoristas podem ser instituídas.</p>
<p>  	Ademais, faz-se necessário implantar a visão de que ser motorista de ônibus não se trata apenas de conduzir um veículo, mas de um conjunto de responsabilidades, como atendimento ao público e uso da tecnologia embarcada.</p>
<p>A ausência desta visão, bem como outros problemas associados, é mais presente nos condutores do subsistema local de ônibus (as linhas menores, mais periféricas e que fazem a ligação interna dos bairros aos grandes eixos). No subsistema local, verifica-se que a cultura da direção defensiva é mais frágil, bem como as estruturas de recursos humanos (RHs), o que aponta para a necessidade de melhoria da gestão das empresas na implantação da cultura de segurança viária e necessidade de fortalecimento das estruturas de RH.</p>
<p>Frente a estes desafios, o plano de ação do Vida Segura prevê um conjunto de ações para melhoria da capacitação e comportamento dos motoristas.</p>
	</div>
</template>

<script>
export default {
	name: 'Cap2CEixoVII'
}
</script>
