<template>
	<div class="Cap2CEixoIII">
		<h5>1.	Introdução</h5>
		<p>A promoção de uma urbanização sustentável e orientada ao transporte público pode contribuir à segurança viária pelos seus estímulos aos modos ativos de mobilidade e ao transporte público e aos desestímulos aos usos de veículos motorizados individuais. Quanto mais compacta e com usos mistos do solo for a cidade, e quanto melhor o acesso e a qualidade do transporte público, menor a necessidade de locomoção por automóvel individual, o que reduz a exposição das pessoas ao risco de acidente e ainda contribui para a redução de emissão de poluentes (OBELHEIRO, et al, 2017, p 18).</p>
		<p>Pesquisas globais mostram que cidades com maiores proporções de uso de transporte público coletivo possuem menores taxas de mortes no trânsito (OBELHEIRO, et al, 2017, p 18). De acordo com os dados da última pesquisa de mobilidade da Região Metropolitana de São Paulo (RMSP), 69,3% das viagens realizadas no município de São Paulo foram por modos motorizados e 30,7% por modos não motorizados (bicicleta e à pé). Entre os motorizados, 56,2% foram por modos coletivos (metrô, trem, ônibus, fretado e escolar) e 43,8% por modos individuais (automóvel, táxi e motocicleta). Tais percentuais revelam que o município ainda tem espaço para ampliação da participação relativa das viagens coletivas entre as motorizadas, bem como para a participação da mobilidade ativa, não motorizada.</p>
		<p>Ao se comparar o risco relativo entre cada modo de transporte, explicita-se ainda mais a importância dos estímulos ao transporte coletivo. Isto pois as viagens por ônibus destacam-se por serem as mais seguras. De acordo com estudo promovido pela WRI Brasil, ao se relacionar o número de vítimas fatais para cada modo de transporte e o número de viagens, verifica-se que viajar de ônibus é 11 vezes mais seguro que de veículo automotor individual e 365 vezes mais seguro andar de motocicleta.</p>
		<p>Como se pode perceber, as viagens por motocicleta são as mais arriscadas, sendo que houve exponencial aumento das viagens por este modo, que registrou crescimento de 600% entre 1999 e 2012. Tal expansão pode ser explicada em parte pelos incentivos fiscais oferecidos a estes veículos ao longo dos últimos anos, por meio de reduções de alíquotas do imposto sobre produtos industrializados (IPI), bem como pelo fato de as viagens por motocicleta serem as que levam menos tempo, especialmente quando há congestionamento, se comparadas aos demais modos. Este cenário acentua a necessária melhoria de condições do transporte coletivo e dos modos ativos, de modo a provocar a migração do uso de motocicleta para outras alternativas.</p>

		<h5>2.	Mobilidade ativa</h5>
		<p>Mobilidade ativa refere-se aos modos de deslocamento por propulsão humana, ou seja, os modos não motorizados. Destacam-se a mobilidade a pé e a por bicicleta, para além de outros modos de transporte, tais como patins, skate, patinetes, etc. O PlanMob estabelece em seus princípios, diretrizes e objetivos a promoção de uma cidade sustentável, acessível, orientada ao transporte público e com prioridade à mobilidade ativa - sendo que em primeiro lugar está o pedestre, seguido do ciclista.</p>
		<h6>a.	Pedestres</h6>
		<p>O Plano Nacional de Mobilidade Urbana estabelece que os pedestres têm prioridade sobre os demais modos de deslocamento, uma vez que são os usuários mais vulneráveis da via. Contudo, os pedestres representam 41,5% dos mortos no trânsito da cidade de São Paulo, ou seja, 331 mortes, constituindo-se como o grupo que mais morre em acidentes de trânsito na cidade de São Paulo. Excluindo-se as vítimas fatais, o número de pessoas atropeladas é dez vezes maior: 3.611 (SAT, 2017).</p>
		<p>Ao analisar o percentual de vítimas fatais por idade e modo de deslocamento, nota-se que crianças (menores de 10 anos) e pessoas idosas (com mais de 70 anos) são majoritariamente pedestres. Ou seja, dentre todas as crianças que morrem no trânsito, 73% foram atropeladas. Dentre os idosos esse número corresponde a 84%.</p>
		<p>É importante ressaltar que dentre os pedestres, as pessoas com mais de 50 anos realizam menos de 20% das viagens a pé, mas respondem por mais de 50% das fatalidades. Logo, os grupos etários com menos de 10 anos e mais de 50 anos são grupos de risco quando se trata de deslocamentos a pé. Os dados tornam-se ainda mais preocupantes ao se considerar que os dados de acidente de trânsito não incluem vítimas por queda em calçada e demais componentes da infraestrutura para pedestre. Dados da pesquisa ISA CAPITAL 2015, da Secretaria Municipal de Saúde, mostram que 3,25% da população sofreu alguma queda na rua durante o período de 12 meses prévios à realização das entrevistas, o que representa aproximadamente 300 mil pessoas.</p>
		<p>A infraestrutura da mobilidade a pé constitui-se das “vias terrestres nos termos do Código de Trânsito Brasileiro, que incluem as calçadas, a pista de rolamento, os canteiros centrais e logradouros públicos, bem como aquela que permite a conexão delas munidas de facilidade e segurança na realização das travessias de ruas da cidade” (Estatuto do Pedestre).</p>
		<p>Vias que colocam os pedestres em primeiro lugar são aquelas adequadas a pessoas de todas as idades e habilidades e que abrigam as mais diversas atividades como andar, sentar e descansar. Em comparação com os demais usuários da via, pedestres se deslocam devagar e experienciam a rua com maior intensidade, pois isso a importância de criar ambientes construídos atraentes (seguras, acessíveis e confortáveis) para essa forma sustentável e de deslocamento.</p>
		<h6>b.	Ciclistas</h6>
		<p>Em 2017, os ciclistas representaram 4,7% dos mortos no trânsito na cidade de São Paulo, apesar de representarem uma pequena parcela nos modos de deslocamento – menos de 1% do total de viagens. De acordo com pesquisas mais recentes, a quantidade de viagens por bicicleta atingiu 2% do total (Torres Freire et. al, 2018), o que demonstra um crescimento estimulado pelo aumento da infraestrutura cicloviária nos últimos anos.</p>
		<slot name='g28'></slot>
		<p>De acordo com estudos do CEBRAP sobre o potencial ciclável da cidade, 35% das das viagens realizadas no município são facilmente pedaláveis, isto é, são trajetos de até 5 km, realizadas entre 6h e 20h, por pessoas com até 50 anos; enquanto que outros 7% são pedaláveis (viagens de até 8 km, realizadas entre 6h e 20h, por pessoas com até 50 anos) e 58% não são pedaláveis.</p>
		<p>Também de acordo com o CEBRAP, os ciclistas atuais diminuem em 3% a emissão de CO2 dos deslocamentos da cidade, sendo que, ao atingir o potencial ciclável, haveria uma redução de até 18% da emissão de CO2 oriunda dos transportes na cidade de São Paulo. A instituição também aponta que, se o perfil de atividade física da população da cidade espelhasse o dos ciclistas, haveria uma redução de 13% do total em gastos no SUS (R$ 35 milhões) com internações em virtude de doenças do aparelho circulatório e diabetes, bem como que os ciclistas apresentam 75% menos estresse e irritação em seus deslocamentos.</p>
		<p>Para além das melhorias necessárias à infraestrutura cicloviária tratada no Eixo III, em 2018, os ciclistas demonstraram insatisfação com o respeito dos motoristas e pedestres às ciclovias: dois terços sentem-se insatisfeitos. Isto revela a necessidade de realização de campanhas, fomento à cultura da bicicleta e aumento da fiscalização que incentive comportamentos seguros.</p>
		<p>O uso da rede cicloviária se potencializa ao complementar a rede de transporte público coletivo e áreas prioritárias para pedestres – como os calçadões. Somam-se aos componentes do sistema cicloviário as bicicletas compartilhadas reguladas pelo Comitê Municipal de Uso do Viário (CMUV), tema abordado mais adiante neste eixo.</p>
		<p>Esse conjunto de políticas pode, inclusive, estimular o comércio local. Após a construção de uma ciclovia protegida na 9ª Avenida, em Nova York, o comércio local viu um aumento de 49% nas vendas. Em outras ruas do mesmo distrito, a média de aumento foi de apenas 3% (NYC-DOT, 2012).</p>

		<h5>3.	Transporte Coletivo Público de Passageiros</h5>
		<h6>a.	Sistema de Transporte Coletivo Urbano de Passageiros de São Paulo (STCUP)</h6>
		<p>O Sistema de Transporte Coletivo Urbano de Passageiros de São Paulo (STCUP) é um dos maiores sistemas de transporte público sobre pneus do mundo, com uma frota de mais de 14.000 ônibus, que transportam mais de 10 milhões de passageiros ao dia pelo município de São Paulo.</p>
		<p>No que tange à qualidade dos serviços, de acordo com a Pesquisa Satisfação dos Usuários com os Serviços de Transporte Público por Ônibus na Cidade de São Paulo, realizada anualmente pela SPTrans, nos últimos anos a avaliação tem apontado tendência de melhora. Atualmente, 62,3% dos usuários consideram o serviço de transporte municipal por ônibus “regular”, 31% “bom” ou “ótimo” e 6,7% “ruim” ou “péssimo”.</p>
		<p>Embora a pesquisa aponte pequena proporção de usuários que consideram o serviço “ruim” ou “péssimo”, expressiva maioria o considera apenas “regular”, o que aponta a necessidade de melhoria dos serviços. Para isso, a ferramenta fundamental da PMSP é a nova licitação do STCUP, que culminará em novas contratações, em substituição às atuais, e cujas melhorias previstas serão tratadas no Plano de Ação.</p>
		<h6>b.	Acessibilidade do sistema de ônibus</h6>
		<p>O transporte público é fundamental para o acesso das pessoas com deficiência a todos os recursos e serviços que a cidade dispõe. Por isso, a Lei Brasileira de Inclusão, ou LBI, (Lei Federal nº 13.146/15) determina  alguns avanços importantes quanto à acessibilidade inerente ao transporte e à mobilidade.</p>
		<p>Segundo dados da SPTrans, 93% da frota é acessível, sendo que alguns dos veículos possuem piso baixo e outros, elevadores de acesso. No entanto, ainda verifica-se a circulação de ônibus com elevadores inoperantes e com necessidade de melhoria das condições de uso. Quando é verificado o tráfego de veículo com elevador inoperante, a operadora é autuada e o ônibus retirado de circulação até que o equipamento seja consertado.</p>
		<p>Os veículos devem preferencialmente apresentar piso baixo, porém ainda existem impedimentos técnicos em veículos de menor porte (modelos mini e midi) em adotar esta configuração. Vale ressaltar que, no início de 2018, foi lançada uma nova linha de ônibus ligando o terminal/metrô Jabaquara ao Centro de Treinamento Paralímpico Brasileiro, com veículos tipo micro-ônibus com piso baixo, 8,9 metros de comprimento, motor traseiro, ar-condicionado, tomadas USB para carregamento de equipamentos eletrônicos e capacidade total para 36 passageiros, incluindo quatro cadeirantes e acesso (embarque/desembarque) por meio de rampa. Essa configuração é a que melhor atende a ausência de veículos acessíveis nas periferias.</p>
		<p>Além disso, uma das maiores dificuldades, em especial das pessoas com deficiência visual, é a ausência de sinalização sonora nos veículos e paradas.</p>
		<p>Em relação ao comportamento dos passageiros, nota-se pouco respeito aos espaços para as pessoas com deficiência nos ônibus. Quando o motorista precisa parar para que ela embarque no ônibus, há pressão dos demais pelo maior tempo de espera na parada, em detrimento das pessoas com deficiência.</p>
		<h6>c.	Programa de Redução de Acidentes em Transportes (PRAT)</h6>
		<p>O PRAT é o principal programa empreendido pela SPTrans relacionado à segurança viária. Suas atividades se iniciam quando o Centro de Operações da empresa (COP) é notificado de um acidente com vítima envolvendo ônibus do STCUP e aciona a equipe técnica de campo, que se dirige até o local da ocorrência para levantamento de informações que permitam compreender a dinâmica do acidente (condições da via, fotos do local e veículo(s) envolvido(s), marcas de frenagem, número do Boletim de Ocorrência, se houver, relato de testemunhas, etc.). É, então, elaborado o Relatório Preliminar de Acidente (RPA), o qual contém, além dos dados coletados, um diagrama de cena (croqui). Posteriormente, a área administrativa do COP reúne esse material para que o Grupo Executivo do PRAT possa proceder à análise.</p>
		<p>Quando apontada responsabilidade do condutor, ele é bloqueado no sistema, devendo ser afastado de suas atividades e passar por um processo de reciclagem, com o objetivo de aperfeiçoar seu desempenho e melhorar sua forma de atuação. O operador somente é desbloqueado após a apresentação de documentos que comprovem que ele está apto a retornar às suas atividades, a saber: atestado de sanidade física e mental, exame psicotécnico e certificado do curso de direção defensiva, com data posterior ao ocorrido. Todos os referidos documentos são analisados quanto a sua autenticidade e se os profissionais emitentes são cadastrados junto aos órgãos competentes (DETRAN e Conselhos Regionais).</p>
		<p>O número de acidentes com responsabilidade do condutor é considerado na avaliação de desempenho dos serviços prestados pelas operadoras, sendo um dos parâmetros do Índice de Qualidade de Transporte (IQT), e por isso, constitui-se em fator de atenção para as empresas.</p>
		<p>Por fim, inclui-se também nos objetivos do PRAT analisar os locais com maior incidência de ocorrências e os fatores de risco, propondo planos de ação que auxiliem na prevenção, tais como: alterações no viário, utilização de grades de proteção e isolamento, implantação de sinalização, palestras com os operadores afastados, etc. Para tanto, é preciso contar com uma equipe especializada, investindo sempre no aprimoramento e capacitação dos técnicos.</p>
		<h6>d.	Serviço ATENDE</h6>
		O Serviço de Atendimento Especial (ATENDE), criado pelo Decreto Municipal nº 36.071/1996 e atualmente regido pela Lei Municipal 16.337/2015, é um transporte do tipo porta a porta destinado às pessoas que não apresentarem condições de mobilidade e acessibilidade autônoma pelos meios de transportes convencionais ou que manifestem grandes restrições ao acesso e uso de equipamentos urbanos, com: deficiência física, temporária ou permanente; transtorno do espectro autista; ou surdocegueira.
		<p>O Serviço é referência nacional e seu modelo inspira a implantação de atividades e operação muito parecidas em dezenas de cidades brasileiras. Em agosto de 2012, A SPTrans encomendou junto ao Instituto IBOPE pesquisa de satisfação com os usuários do serviço, no transporte executado por vans, e obteve aprovação de 97% da população pesquisada. Em 2016, a empresa CONTEXTO realizou nova pesquisa e a aprovação foi de 99,3% da população pesquisada.</p>
		<p>Atualmente, o serviço conta com 440 veículos tipo van, além de 100 táxis acessíveis cadastrados para complementação. Em maio de 2018, foram transportadas 5.250 pessoas com deficiência e 3.965 acompanhantes, o que gerou mais de 83.000 viagens.</p>
		<p>Dentro do processo de constante atualização do ATENDE, está sendo desenvolvido um site para o usuário solicitar serviços e consultar suas programações de viagens. Também estão sendo desenvolvidos aplicativos para usuários e motoristas, que darão condições de acesso a informações dinâmicas e operacionais, trazendo maior agilidade nos processos e facilidades aos usuários.</p>
		<p>Já quanto às dificuldades, o ponto crítico do serviço é a existência de demanda reprimida. No novo edital de licitação do STCUP, há a previsão de ampliação da frota para que a demanda existente seja mais bem absorvida.</p>

		<h5>4.	Transporte Escolar</h5>
		<p>O serviço de transporte escolar no município de São Paulo é regido pela Lei Municipal 10.154/1986 e regulamentado pela portaria 226/DTP-GAB/2012. O serviço conta com frota de aproximadamente 18.000 veículos e 13.800 condutores, atendendo a aproximadamente 10.000 escolas.  </p>
		<p>Em que se pese a inexistência de dados sistematizados sobre fatalidades e acidentes de trânsito específicas sobre esse modo de transporte, pode-se inferir que ocorrências envolvendo esse tipo de veículo não são comuns.</p>
		<p>Um dos pontos fortes do transporte escolar é o exercício fiscalizatório sobre a prestação dos serviços pelos próprios clientes-usuários, os pais das crianças transportadas. Pela própria natureza do serviço, o controle da qualidade tende a ser mais rígido que em relação a outros modos de transporte, uma vez que pais e escolas têm alto interesse na prestação de transporte escolar rigidamente seguro aos seus filhos e alunos. De modo a fortalecer a capacidade de fiscalização dos usuários, o DTP tem trabalhado na orientação às escolas, promovendo a divulgação dos canais de reclamação e reforçando a importância de se contratar apenas serviços autorizados pelo órgão.</p>
		<p>Todo transportador escolar passa por curso no DETRAN, sem o qual não é possível a obtenção da autorização para exercício da atividade. Os transportadores passam também por curso obrigatório a cada 5 anos sobre o transporte de pessoas com deficiência, obrigação prevista e cujos cursos são objeto de análise e autorização do DTP.</p>
		<p>São três os tipos de veículos permitidos a prestar o serviço de transporte escolar: as kombis e assemelhados, cuja idade máxima permitida é 10 anos; as vans e micro-ônibus, cuja idade máxima permitida é 15 anos; e os ônibus, cuja idade máxima permitida é 25 anos. Sobre o tema, compete explicitar a existência de vans, cujos certificado de registro e licenciamento de veículo constam como ônibus, mas que não possuem os parâmetros impostos pelas resoluções 316, 416 e 445 do CONTRAN para se enquadrarem como tal.</p>
		<p>Todos os veículos do transporte escolar passam por 3 inspeções veiculares anuais, entre as estaduais e municipais. Uma das exigências mais recentes, imposta pela resolução CONTRAN 154, é a de que todos veículos tenham câmera frontal e traseira, bem como monitor interno.</p>
		<p>Em 2017, o DTP realizou 4.367 vistorias, tendo sido geradas 1.048 reprovações (24%), índice relativamente alto. Foram constatadas, no total, 5.299 irregularidades, dentre as quais 1.719 (32,4%) referiram-se a itens relacionados à segurança (por exemplo: pneus, freio e câmbio). A idade média atual da frota de kombis e assemelhados é 7,5 anos, a de vans e micro-ônibus, 7,2 e a de ônibus, 10,4.</p>
		<p>Em 2017, o serviço recebeu poucas reclamações frente ao tamanho da frota, apenas 538 (índice de 0,03 reclamação por veículo). 81,22% das reclamações concentraram-se em 6 tipos, conforme tabela abaixo. Merecem destaque as denúncias relativas a veículos clandestinos, direção perigosa e superlotação (juntas, são 43% do total de reclamações), as quais requerem constante fiscalização e punição por parte do poder público.</p>
		<slot name='tabela15'></slot>
		<p>Por fim, compete mencionar a necessidade de fortalecimento do uso do cinto de segurança obrigatório pelas crianças, tendo em vista o alto risco decorrente da não utilização do dispositivo.</p>

		<h5>5.	Transporte Coletivo Privado de Passageiros (Fretamento)</h5>
		<p>O transporte coletivo privado de passageiros na modalidade fretamento no município de São Paulo é regido pela Lei Municipal nº 16.311/2015 e conta com uma frota de aproximadamente 14.500 veículos e 3.700 condutores. A modalidade somente pode ser desempenhada no município por pessoas jurídicas e que possuam Termo de Autorização expedido pela SMT.</p>
		<p>Para cada veículo que for desempenhar a atividade, as operadoras devem requerer o Certificado de Vínculo ao Serviço (CVS), obtido a partir de entrega de documentos e vistoria no DTP para comprovar as características exigidas na legislação. Os veículos devem estar adequados às regras de acessibilidade.</p>
		<p>Apesar de a idade máxima dos veículos ser de 10 (dez) anos, para veículos mistos e micro-ônibus, e de 15 (quinze) anos para ônibus, a idade média da frota de fretados cadastrados no município é de pouco mais de 5 anos e o total de reclamações referentes ao serviço é extremamente baixa, apenas 37 em 2017. Quatro tipos de reclamação concentram 70% do total: 9 reclamações para veículo clandestino/ carro frio (24,3%); 7 por efetuar transporte em modalidade não autorizada (18,9%); 5 para inobservância ao ponto de parada (13,5%); e 5 para direção perigosa (13,5%). Destacam-se a predominância de denúncias relativas ao transporte clandestino e à direção perigosa.</p>
		<p>Do total de 3.103 vistorias realizadas pelo DTP em 2017, 717 (23,1%) geraram reprovações, índice relativamente alto. Foram constatadas 1.257 irregularidades, dentre as quais 384 (30,5%) referentes a itens de segurança (por exemplo, pneus, freio e câmbio).</p>
		<p>O município não possui, de modo sistematizado, dados relativos a ocorrências envolvendo ônibus de fretamento.</p>
		<p>O Município apresenta uma área de restrição denominada Zona de Máxima Restrição de Fretamento – ZMRF. O veículo na atividade de fretamento que necessitar acessar a ZMRF deve solicitar Autorização Especial de Trânsito no site da PMSP e comprovar a necessidade de acesso.</p>
		<p>O “Plano de Operação” é um documento que contém informações prestadas pelas operadoras no sistema de cadastramento e de solicitação de Autorização Especial referentes aos horários, itinerários, considerando o início e o término do percurso, locais de embarque/desembarque intermediários com a caracterização da prestação do serviço pelos veículos que necessitem utilizar vias em áreas restritas.</p>
		<p>Pode ser realizado o embarque/desembarque do veículo de fretamento devidamente autorizado e cadastrado junto à Prefeitura, nos locais previstos no Plano de Operação e respeitando a sinalização existente na via.</p>
		<p>Fora da área ZMRF, o embarque e desembarque não podem ser realizados em pontos de parada, estações de transferência ou terminais do serviço de transporte coletivo público de passageiros.</p>
		<p>Ademais, todos os condutores necessitam ser autorizados como motorista profissional pelo DETRAN, constando em sua Carteira Nacional de Habilitação a inscrição EAR indicando que “Exerce Atividade Remunerada”.</p>
		<p>Esta atividade tem sido regulamentada no Município a partir de debates na Comissão de  Acompanhamento da Regulamentação do Fretamento (CAREF), que foi criada em 2009 e mantida como canal entre o Poder Público e as entidades representativas vinculadas à atividade de fretamento e população usuária deste modo de transporte. Atualmente, a Comissão está regulamentada pela Lei nº 16.311/15 e Decreto nº 56.963/16. Possui caráter consultivo, está vinculada à Secretaria Municipal de Mobilidade e Transportes e tem atribuição de acompanhar o desenvolvimento da atividade de fretamento, apreciar e emitir parecer sobre solicitações de entidades e usuários vinculados ao serviço, bem como exercer outras atribuições correlatas, de forma a garantir a segurança dos usuários de seu sistema e dos usuários da via.</p>

		<h5>6.	Transporte de Cargas</h5>
		<p>Os principais tipos de acidentes fatais com envolvimento de caminhão entre 2015 e 2017 foram as colisões e atropelamentos, sendo que, entre as colisões, mais da metade foram com motociclista.</p>
		<slot name='g29'></slot>
		<p>A relação entre caminhão e motociclista é especialmente arriscada pela existência de ponto cego do motorista de caminhão.  A Resolução 323 do CONTRAN obriga que todos os caminhões fabricados a partir de 2011 tenham proteção lateral com o objetivo de impedir que, quando da ocorrência, o motociclista não deslize por baixo do caminhão. Porém, como a exigência trata apenas dos modelos pós 2011, ainda há muitos caminhões sem esse dispositivo.</p>
		<p>Para além dessa proteção, é necessário que a legislação avance na imposição gradativa da renovação da frota com a inclusão de outros dispositivos de segurança, tais como o bloqueio de aceleração ou o controle de estabilidade. Em Nova Iorque, por exemplo, já existem instalados espelhos retrovisores adicionais no para-lama e para-choque do caminhão, de modo a eliminar o ponto cego.</p>
		<p>É possível dividir o fluxo do transporte de cargas em São Paulo em três  tipos, o que promove o abastecimento e escoamento da produção, o da distribuição urbana e o de passagem que apenas atravessa seu território. Um dos pontos críticos atuais é a ausência de inteligência tecnológica que permita mapeamento preciso dos volumes e percentuais de cada tipo que subsidie o planejamento sobre o transporte de cargas, inclusive no que tange à segurança viária. Uma das possibilidades é a utilização dos dados gerados pelos equipamentos de fiscalização eletrônica da SMT/CET, o que não é realizado.</p>
		<p>Entre os tipos de carga, destaca-se o transporte de carga excedente. Trata-se de espécie a qual requer autorização especial de trânsito (AET) e cujos veículos possuem uma característica específica e são controlados através da AET. Os parâmetros para que um caminhão seja enquadrado como excedente estão previstos na Resolução 210/08 do CONTRAN. O principal ponto de risco em relação a esses parâmetros é a altura dos caminhões, em comparação à altura das obras de arte. Atualmente, o CONTRAN estabelece as dimensões máximas para que caminhões de 4,6 metros de altura circulem sem autorização especial, porém muitas das obras de arte têm 4,4 metros, o que aumenta do risco de choques de caminhões em pontes e viadutos. Em 2016, foram registrados 264 incidentes com caminhões com altura excedente e em 2017 foram 327, indicando a necessidade de medidas preventivas para coibir essas ocorrências e seus impactos na mobilidade.</p>
		<p>Quanto aos horários dos acidentes com envolvimento de caminhões, há quatro faixas horárias com maior número de acidentes fatais: entre meia noite e 1 hora; entre 8 e 11 horas, entre 12 e 17 horas e entre 18 e 19 horas, com destaque ao período da tarde, entre 14 e 17 horas.</p>
		<slot name='tabela16'></slot>
		<p>O alto índice de acidentes entre meia noite e uma hora possivelmente se deve ao aumento da velocidade imprimida pelos condutores, cujo motivo principal pode ser questão de segurança pública, estar próximo ao horário de encerramento do recebimento da carga, o cansaço do condutor, entre outros.</p>
		<p>As regulamentações municipais existentes têm como um dos principais objetivos minimizar os conflitos entre os caminhões e os demais modos de transporte. Isto é feito especialmente por meio de restrições ao trânsito de caminhões entre 5 e 21 horas na Zona de Máxima Restrição de Circulação (ZMRC) e algumas outras vias estruturais, bem como pela restrição do trânsito de caminhões na Marginal Tietê e vias adjacentes nos horários de pico, entre 5 e 9 e entre 17 e 21 horas. Apesar de serem restrições gerais, existem algumas flexibilizações específicas a depender do veículo e da finalidade, com horários de liberação diferenciados, de acordo com as características de cada atividade. Algumas dessas condições podem estar associadas aos picos de acidentes em alguns horários. Por exemplo, muitas das excepcionalidades são liberadas até às 16h e a proximidade do início do horário da restrição pode gerar no condutor um comportamento de preocupação ou de ansiedade implicando aumento da velocidade.</p>
		<p>Dentre outras faixas horárias com maior número de acidentes fatais, estão os horários de pico, que são os que apresentam maior conflito com outros veículos.</p>
		<p>Há ainda o transporte irregular de carga, em especial por veículos cujas restrições são menores, os quais são utilizados para transportar cargas diferentes daquelas para as quais estão autorizados. Por exemplo, veículos com equipamento de socorro mecânico de emergência, os guinchos, que são liberados por período integral e se tornam irregulares ao transportar máquinas, equipamentos ou veículos que não estão em situação de emergência.</p>
		<p>Outro tópico relevante são as idades máximas dos caminhões. A legislação atual impõe como idade máxima para cadastramento e efetivação da autorização de acesso aos locais restritos para caminhões do tipo VUC<a title="  VUC – Veículo Urbano de Carga: Definido no Decreto Municipal 56.920/16 como caminhão de pequeno porte, com dimensões e características adequadas à distribuição de mercadorias e abastecimento no meio urbano, propiciando redução no conflito com pedestres, outros veículos não motorizados, de transporte coletivo e demais veículos, e que devem observar condições adequadas quanto à emissão de poluentes." style='cursor: help;'><sup>41</sup></a> e de concretagem-bomba, de 15 anos, e para os caminhões de concretagem, 10 anos.</p>
		<p>Quanto aos volumes máximos de carga permitidos, destaca-se a nova regulamentação de “caminhões basculantes terra-entulho”, que limita a 12 metros cúbicos o volume de carga a ser transportado. Há caminhões que trafegam acima do limite, gerando maior risco, pois interfere na capacidade de frenagem, motivo pelo qual esses caminhões são objeto de fiscalização intensiva pela CET.</p>
		<p>Outro tipo de transporte de carga é o transporte de produtos perigosos, em especial os de produtos químicos. Em 2017, ocorreram apenas 5 acidentes envolvendo esse tipo de transporte. Apesar do número baixo, no mesmo ano, foram constatadas, nas frequentes fiscalizações, 70% de irregularidades nos veículos que transportam produtos perigosos, motivo pelo qual tem se intensificado a fiscalização. A legislação municipal exige que, para receber autorização da administração pública, as transportadoras de produtos perigosos tenham aprovado o Plano de Atendimento a Emergências junto à Secretaria Municipal do Verde e Meio Ambiente, o que diminui o tempo de atendimento e o risco de consequências mais graves, tais como reações químicas que gerem explosões ou emissão de gases, quando da ocorrência de um acidente. Porém, assim como para os demais tipos de transporte de carga, a cidade carece de inteligência tecnológica que faça o mapeamento e permita a definição de rotas específicas para os produtos perigosos, de modo a aumentar a previsibilidade da localização dos caminhões e diminuição de risco.</p>

		<h5>7.	Transporte Individual Remunerado de Passageiros</h5>
		<h6>a.	Táxi</h6>
		<p>O serviço de táxi no município de São Paulo, regido pela Lei Municipal nº 7.329/1969, alterada pela Lei Municipal nº 10.308/1987, possui frota de quase 38.000 veículos, aproximadamente 75.000 condutores e 2.500 pontos. Do mesmo modo que o transporte escolar e fretamento, o município não possui dados sistematizados a respeito do envolvimento de acidentes de trânsito por táxis, porém é possível inferir que a participação dessa modalidade na acidentalidade de São Paulo não é expressiva.</p>
		<p>O serviço conta com uma frota nova, com idade média de pouco mais de 3 anos. O total de reclamações recebidas pelo DTP referente ao serviço foi 2.198 em 2017, valor pouco expressivo frente ao tamanho da frota (0,1 reclamação por veículo). 80% das reclamações estão concentradas em 8 tipos, entre as quais destaca-se a direção perigosa, com 184 reclamações (8,4%).</p>
		<slot name='tabela17'></slot>
		O índice de reprovação dos veículos vistoriados pelo DTP também foi baixo, 8,5%. Do total de 14.869 vistorias realizadas, 1.270 foram reprovadas, e do total de 8.313 irregularidades constatadas, 1.775 (21,3%) referiram-se a itens que afetam a segurança (por exemplo, pneus, freio e câmbio).
		<h6>b.	Gestão do uso do viário</h6>
		<p>A regulamentação sobre a exploração econômica do viário merece destaque por ser a ferramenta governamental de direcionamento sobre novos modos de prestação de serviços de transporte, que têm afetado as opções e escolhas da população.  </p>
		<p>O Decreto Municipal 56.981/2016, e alterações, é a principal norma regulamentadora do tema, tendo criado o Comitê Municipal de Uso do Viário (CMUV) e instituído as regras para os serviços de:</p>
		<ul>
			<li>(i) transporte individual remunerado de passageiros de utilidade pública;</li>
			<li>(ii) carona solidária e</li>
			<li>(iii) compartilhamento de veículos sem condutor. Destaca-se no cenário atual, pelo volume de passageiros, o primeiro, prestado pelas operadoras de tecnologia de transporte individual de passageiros (OTTCs).</li>
		</ul>
		<p>Compete inicialmente destacar a relevância da própria criação do CMUV, instância capaz de dinamicamente instituir e alterar as políticas públicas regulatórias de criação de incentivos e desincentivos dos referidos serviços. Além disso, dentre os dispositivos já implementados, destacam-se:</p>
		<ul>
			<li>(i) a política de cobrança de preço público variável sobre as OTTCs, a depender do horário, dia, região geográfica, nível de poluição gerada pelo veículo, quantidade de quilômetros e quantidade de pessoas simultaneamente transportadas;</li>
			<li>(ii) definição de critérios mínimos de credenciamento dos condutores, incluindo obrigatoriedade de capacitação e</li>
			<li>(iii) a definição de tempo máximo de fabricação dos veículos. Tais normas cumprem o papel de dar maior segurança aos usuários.</li>
		</ul>
		<p>Ainda no que se refere ao transporte individual prestado pelas OTTCs, são necessários estudos para se entender com maior profundidade quais são as consequências da entrada e expansão deste serviço ao sistema viário e quais devem ser os direcionamentos futuros. Neste sentido, o CMUV exige das prestadoras uma série de dados operacionais, de modo que seja possível fazer a análise dos dados e o melhor planejamento dos novos dispositivos regulamentadores. Os dados são utilizados para fins de tributação e devem ser mais bem explorados para fins de gestão.</p>
		<p>O CMUV é responsável também pelo sistema de compartilhamento de bicicletas em vias e logradouros do município, regido pelo Decreto Municipal nº 57.889/2017. Este serviço consiste na disponibilização de bicicletas para locação por operadoras de tecnologia de bicicletas compartilhadas, seja por meio de estações em locais físicos definidos; seja sem estações, com sistema de autotravamento e georreferenciamento das bicicletas.</p>
		<p>O sistema ainda está sendo prestado de modo incipiente pelas operadoras, mas tem o potencial de ser uma das mais relevantes políticas públicas municipais de incentivo à mobilidade ativa. O decreto regulamentador, complementado pela resolução CMUV/17/2017, cumpre importante função de instituir as regras básicas de prestação do serviço, trazendo a segurança jurídica necessária às operadoras de bicicletas compartilhadas. Ademais, as normas buscam incentivar a massiva expansão do serviço, especialmente por meio da desoneração progressiva sobre a OTTC, à medida que esta aumente a quantidade de bicicletas disponibilizadas. As regras buscam também o incentivo à integração com os transportes públicos, incluindo a previsão de utilização do Bilhete Único para destravamento dos veículos.</p>

		<h5>8.	Mobilidade e poluição atmosférica</h5>
		<p>Os dados referentes à emissão dos principais poluentes atmosféricos atestam a relevância das políticas públicas municipais de mobilidade urbana para o meio ambiente e para a saúde da população e corroboram com a necessidade de o poder público municipal focar políticas públicas que reduzam a necessidade de viagens motorizadas e a migração para modos ativos e de transporte público coletivo.</p>
		<p>O relatório Qualidade do Ar no Estado de São Paulo, elaborado pela Companhia Ambiental do Estado de São Paulo (CETESB) revela que, na RMSP, as fontes móveis (veículos) são responsáveis por 40% das emissões de material particulado (MP), 76% das de hidrocarbonetos; 97% das emissões de monóxido de carbono (CO)  e 67% das dos óxidos de nitrogênio.</p>
		<p>Já de acordo o Inventário de Emissões Atmosféricas do Transporte Rodoviário de Passageiros no Município de São Paulo, elaborado pelo Instituto de Energia e Meio Ambiente (IEMA)<a title="   Inventário de Emissões Atmosféricas do Transporte Rodoviário de Passageiros no Município de São Paulo. Disponível em http://emissoes.energiaeambiente.org.br/graficos. Acesso em 07/06/2018." href='http://emissoes.energiaeambiente.org.br/graficos' style='cursor: help;' target="_blank"><sup>42</sup></a>, de 2017, verifica-se que, entre os diferentes tipos de veículo, o automóvel individual é o principal poluidor.</p>
		<p>O inventário mostra que o automóvel é responsável por 71% das emissões totais de material particulado (MP), 76,7% das dos hidrocarbonetos não metanos (NMHC); 71,3% das de monóxido de carbono (CO) e 72,6% das emissões dos Gases de Efeito Estufa (GEE); enquanto que as emissões dos ônibus correspondem a 23,9% do total de MP; 7% de NMHC; 7,4% de CO e 23,8% de GGE. Os ônibus superam os automóveis apenas na emissão de NOx, 77,8% contra 19%.</p>
		<p>Já no cálculo de emissão por Passageiro-Quilômetro, que “corresponde às emissões do transporte de um passageiro percorrendo a distância de um quilômetro” (IEMA, 2017), um passageiro de automóvel emite aproximadamente 3,8 vezes mais MP que um passageiro de ônibus; 13,6 vezes mais NMHC; 12,1 vezes mais CO e 3,8 vezes mais GGE. Essa relação se inverte apenas para o NOx, para o qual um passageiro de ônibus emite 3,2 mais.</p>
		<h6>a.	Frota de ônibus limpa</h6>
		<p>Um dos mais recentes avanços na promoção do desenvolvimento sustentável da cidade é a promulgação da Lei Municipal 16.802, publicada em janeiro de 2018. A norma impõe a redução progressiva de emissões de dióxido de carbono (CO2) oriundas de combustíveis fósseis, e de poluentes tóxicos decorrentes das frotas integrantes do (i) serviço de transporte coletivo de ônibus e (ii) do serviço de coleta de resíduos sólidos urbanos e hospitalares (lixo) no município.</p><p>De acordo com a lei, no prazo máximo de dez anos, deverá haver uma redução mínima de 50% nas emissões totais de CO2 de origem fóssil, 90% nas de material particulado (MP) e 80% nas dos óxidos de nitrogênio (NOx), em relação às emissões totais de 2016. Já para o prazo de 20 anos, a redução deve ser de 100% nas emissões de CO2 e de 95%, tanto nas de material particulado, quanto nas dos óxidos de nitrogênio (NOx).</p>
		<p>Tais obrigações se aplicam também às (i) prestadoras de serviço do Programa de Transporte Escolar Municipal Gratuito (TEG); (ii) aos proprietários de ônibus fretados e que realizam o transporte de passageiros no município; (iii) à frota de veículos de carga que abasteçam a Companhia de Entrepostos e Armazéns Gerais de São Paulo (CEAGESP) e (iv) à frota de veículos de transporte intermunicipal de passageiros que adentrem no Município.</p>
	</div>
</template>

<script>
export default {
	name: 'Cap2CEixoIII'
}
</script>
