<template>
	<div class="Cap2A">
		<h4>1.	Panorama</h4>
		<p>São Paulo é a mais populosa cidade do país, com 12.176.866 habitantes distribuídos numa área de aproximadamente 1.521 quilômetros quadrados, correspondendo a uma densidade de 7.398,26 hab/km², décima maior do país segundo o IBGE <a title="  Disponível em cidades.ibge.gov.br. Acesso em 11/09/2018" href='https://cidades.ibge.gov.br/brasil/sp/sao-paulo/panorama' style='cursor: help;' target="_blank"><sup>8</sup></a>. Sua frota registrada de 8.603.239 veículos<a title="  ]Fonte: DETRAN/SP, Dez/2017" style='cursor: help;'><sup>9</sup></a> apresentou um crescimento de 35% nos últimos 10 anos (2008-2017), sendo o crescimento da frota de motocicletas no período o dobro do observado para os automóveis, e a taxa de motorização resultante de 1,41 hab./veículo.</p>
		<slot name="g1"></slot>
		<p>A malha viária da cidade tem cerca de 17.000 km de extensão, nas quais estão instalados 468 km de ciclovias, 160 km de corredores de ônibus e 647 km de faixas exclusivas de ônibus à direita da via. Além disso, a capital paulista conta com 52 milhões de metros quadrados de calçada, dos quais 84% são de responsabilidade do proprietário do lote, e 16% de responsabilidade da prefeitura.</p>
		<p>Em 2016, as ocorrências de trânsito figuraram em terceiro lugar<a title="  O gráfico 2 mostra os acidentes de trânsito como quarta causa, porém o terceiro lugar corresponde os “demais acidentes”." style='cursor: help;'><sup>10</sup></a> entre as causas externas de mortalidade em São Paulo e em quarto entre as causas gerais pelo indicador de anos potenciais de vida perdidos<a title=" ]O indicador Anos Potenciais de Vida Perdidos quantifica o número de anos de vida não vividos quando a morte ocorre em determinada idade abaixo da qual se considera a morte prematura. Para cada morte ocorrida se contabiliza a quantidade de APVP subtraindo da idade limite (aqui fixada em 70 anos) a idade em que a morte ocorreu. Assim, uma pessoa que morreu com 30 anos perdeu 40 Anos Potenciais de Vida. " style='cursor: help;'><sup>1</sup></a>.</p>
		<slot name='g2'></slot>
		<slot name='g3'></slot>
		<p>Foram registrados pela CET 13.483 acidentes de trânsito em 2017, sendo 762 com vítimas fatais e 12.721 com vítimas não fatais. Quanto ao total de vítimas, esses acidentes geraram 15.455 vítimas feridas e 797 vítimas fatais. Os números revelam que São Paulo teve: 37 acidentes, 44 vítimas, 2,1 acidentes fatais e 2,2 óbitos por dia, bem como uma morte a cada 17 acidentes registrados.</p>
		<p>Segundo dados da CET de 2017, o acidente mais frequente é a colisão<a title="   Colisão: batida entre veículos em movimento." style='cursor: help;'><sup>12</sup></a> (57,2%), seguida por atropelamentos<a title="   Atropelamento: quando veículo atinge um pedestre." style='cursor: help;'><sup>13</sup></a> (24%).</p>		
		<slot name='g4'></slot>
		<p>A taxa de mortalidade resultante dos acidentes de trânsito em 2017 foi de 6,56 mortes por 100 mil habitantes, uma redução de 7,2% em relação ao ano anterior. Quando comparada à taxa do início da Década de Ação para Segurança Viária da ONU (2011), a redução é de 45,3%, apontando um risco de morte significativamente menor para a população como um todo, e bastante próximo à meta estipulada de redução em 50%.<a title="  Segundo recomendações da ABNT e da OMS, os dados da CET tratados neste plano passaram a adotar, a partir de 2016, como critério para considerar óbitos por ocorrência de trânsito os que ocorreram em até trinta dias após o acidente. As séries históricas de anos anteriores continuam com dados de mortes até um ano após a data do acidente. Para melhor compreensão da evolução histórica dos dados de mortes e ocorrências, consultar nota técnica disponível em https://www.prefeitura.sp.gov.br/cidade/secretarias/upload/chamadas/bancodadosocorrenciastransitocet_1540922024.pdf." href='https://www.prefeitura.sp.gov.br/cidade/secretarias/upload/chamadas/bancodadosocorrenciastransitocet_1540922024.pdf' style='cursor: help;' target="_blank"><sup>14</sup></a></p>
		<slot name='g5'></slot>
		<slot name='g6'></slot>
		<p>Apesar da redução geral no número vítimas fatais e não fatais, entre 2013 e 2017, o número de vítimas não fatais caiu de forma mais acentuada (48%) em relação à queda do número de vítimas fatais (30%). Isso revela que os acidentes mais graves não estão sendo reduzidas da mesma forma que as menos graves, sugerindo que os fatores de risco que implicam na alta severidade, como altas velocidades e condução sob efeito de álcool, precisam continuar sendo combatidos.</p>
		<p>Melhorar a segurança demanda reduzir a velocidade dos veículos e reduzir conflitos. Velocidade veiculares baixas reduzem drasticamente o risco de morte (Rosen e Sander, 2009)<a title="  Rosen, E., and U. Sander. 2009. “Pedestrian Fatality Risk as a Function of Car Impact Speed.” accident Analysis and Prevention 41: 536–542." style='cursor: help;'><sup>15</sup></a>. O risco de mortalidade de pedestres, quando os veículos trafegam a 50 km/h, é o dobro do risco a 40 km/h e mais de 5 vezes maior do que a 30 km/h. (Bunn et al., 2003)<a title="  Bunn, F., T. Collier, C. Frost, K. Ker, I. Roberts, and R. Wentz. 2003. “Traffic calming for the prevention of road traffic injuries: systematic review and meta-analysis.” Injury Prevention 9: 200–204." style='cursor: help;'><sup>1</sup></a>.</p>
		<p>A parcela de pedestres envolvidos em acidentes fatais (41,5%) em 2017 é praticamente o dobro em relação a pedestres feridos em acidentes (22,2%). Essa disparidade entre o número de pedestres mortos e feridos ressalta a grande vulnerabilidade deste grupo de usuários.</p>
		<slot name='g7'></slot>
		<slot name='g8'></slot>
		<p>Em 2017, os usuários mais vulneráveis da via (pedestres, ciclistas e motociclistas) corresponderam a 85,2% das fatalidades e 74,5% das vítimas feridas, sendo 49,7% dos feridos somente motociclistas. A participação majoritária desses grupos de usuários vulneráveis em qualquer tipo de acidente com vítimas evidencia a necessidade de estabelecê-los como prioridade ao adotar esforços para melhorar as condições de segurança viária.</p>
		<p>Distribuídas ao longo de 2017, o mês com mais ocorrências fatais foi março (79), e o dia da semana, domingo (162).</p>
		<slot name='g9'></slot>
		<p>A faixa horária que teve mais acidentes fatais foi o período da tarde (entre 12:00 e 17:59), com 241 acidentes fatais, seguida da madrugada (entre 00:00 e 05:59), com 210. No período vespertino, há distribuição relativamente linear entre os dias da semana, com maior incidência no sábado e domingo. Já nas madrugadas, apesar de para todas as faixas horárias haver maior participação dos sábados e domingos, a participação relativa do final de semana é ainda maior. Os acidentes fatais ocorridos nas primeiras horas de sábado e domingo correspondem a 50% do total dessa faixa horária, bem como 13% do total de acidentes fatais. Tais números indicam a provável associação dos acidentes com a condução embriagada.</p>
		<slot name='t1'></slot>
		<p>Os gráfico X e Y analisam a relação entre a quantidade de viagens em um dia típico, de acordo com os dados da pesquisa de mobilidade da Região Metropolitana de São Paulo realizada em 2012, e a proporção de vítimas fatais por hora do dia. Esta relação indica que a faixa de horário com maior risco (probabilidade de morrer em um acidente de trânsito por cada viagem realizada) é durante a madrugada, especialmente entre 00:00 e 04:00.</p>
		<slot name='g10'></slot>
		<slot name='g11'></slot>
		<p>O gráfico 12 revela que os acidentes ocorridos entre 19:00 e 06:00, especialmente entre 23:00 e 04:00, são mais severos, já que o percentual de vítimas fatais nesses horários supera o de vítimas feridas (Gráfico 8). Esses horários coincidem com os períodos em que são realizadas menos viagens e, consequentemente, os motoristas e motociclistas conseguem desenvolver maiores velocidades nas vias descongestionadas. Há evidências de que os volumes de tráfego afetam a frequência de acidentes, enquanto as velocidades impactam a severidade destes.<a title=" EWING, R.; DUMBAUGH, E. The Built Environment and Traffic Safety A Review of Empirical Evidence. Journal of Planning Literature, v. 23, n. 4, p. 347–367, 2009." style='cursor: help;'><sup>17</sup></a></p>
		<slot name='g12'></slot>
		<p>As maiores reduções no número de vítimas fatais, entre 2013 e 2017, foram registradas entre ocupantes de automóveis. Essa queda está provavelmente ligada ao avanço das tecnologias de segurança, como freio ABS e airbag que passaram a equipar os veículos (2014, com 100% dos veículos novos). Houve queda também ligada com a redução nas velocidades máximas em muitas vias da cidade. Os usuários mais vulneráveis foram os que tiveram as menores reduções no número de fatalidades. A queda no número de mortos dentre os usuários de motocicletas foi a menor, atingindo pouco mais de 20%. Ao contrário dos demais usuários, o grupo de ciclistas foi o único com aumento no número de mortes. Isso pode estar associado ao aumento no número de viagens realizadas com esse modo e à insuficiência de infraestrutura.</p>
		<slot name='g13'></slot>
		<p>Ao cruzar as informações referentes ao número de vítimas por modo de transporte entre os anos de 2013 e 2017 e o número de viagens realizadas por cada modo (pesquisa de mobilidade de 2012), é possível definir o risco dos usuários de cada modo de transporte. A probabilidade de morrer em uma viagem de motocicleta é 356 vezes maior do que realizar a mesma viagem utilizando um ônibus. Há 10 vezes mais chances de morrer em uma motocicleta do que a pé. Também é 2 vezes mais provável morrer em uma viagem de motocicleta do que em uma bicicleta (gráfico 10). O resultado enfatiza a necessidade de direcionar esforços para melhorar a segurança viária dos grupos mais vulneráveis.</p>
		<p>Em relação aos ônibus, importante destacar que a alta segurança apontada sãos apenas para os usuários dentro do ônibus, pois esse tipo de veículo é responsável por grande parte dos atropelamentos fatais ocorridos na cidade.</p>
		<slot name='g14'></slot>
		<p>No que se refere ao número de veículos de cada tipo com envolvimento nos acidentes fatais, entre os anos de 2013 e 2017, os automóveis tiveram participação de 37%, seguidos das motocicletas (33%) e dos ônibus (13%). Destacam-se neste caso as motocicletas, cuja participação nos acidentes fatais é o dobro da sua participação no trânsito de São Paulo (15%), e os caminhões, cuja participação nos acidentes fatais (8%) é 5 vezes maior que no trânsito (1,6%).</p>
		<slot name='g15'></slot>
		<slot name='g16'></slot>
		<p>A participação dos automóveis nos atropelamentos fatais (37%) também é a maior entre os diferentes tipos de veículos, seguida da dos ônibus (20%) e das motocicletas (19%). Destaca-se neste caso o grande envolvimento dos ônibus nos atropelamentos fatais, que superam os das motocicletas e é 6 vezes maior que sua participação no trânsito da cidade (2,88%).</p>
		<slot name='g17'></slot>
		<p>Os usuários de motocicletas e os pedestres mortos em acidentes fatais apresentam perfis diferentes em relação à faixa etária. Dentre os motociclistas mortos no trânsito em 2017, 16% possuem idade entre 10 e 19 anos, 44% entre 20 e 29 anos e 22% entre 30 e 39 anos. Os pedestres possuem uma distribuição mais constante ao longo dos grupos etários, contudo, os com mais de 50 anos correspondem a mais de 50% dos mortos para esse modo, sugerindo que são os usuários mais vulneráveis dentre os pedestres e que o sistema viário da cidade ainda precisa se transformar para proteger esse público (tempos semafóricos, larguras de travessia, etc.).</p>
		<slot name='g18'></slot>
		<p>Em relação ao total de pessoas mortas e feridas, as pessoas entre 20 e 39 anos correspondem à maior parcela. Essa faixa etária contém 45% das vítimas fatais e 55% das feridas.</p>
		<slot name='g19'></slot>
		<slot name='t2'></slot>
		<slot name='t3'></slot>
		<p>No período analisado (2013-2017), o número de vítimas fatais caiu para todos os grupos etários, com variações entre os diferentes grupos. Crianças até 9 anos (-54%), jovens menores de 19 anos (-42%) e idosos com mais de 70 anos (-34%) foram os que apresentaram maiores reduções nas fatalidades. A população com idade entre 30 e 59 anos registrou quedas moderadas com uma média de -23%, enquanto entre os jovens de 20 a 29 anos a baixa foi de apenas 14%.</p>
		<slot name='g20'></slot><a title="  A classificação das faixas etárias utilizada nesse gráfico é diferente da classificação utilizada nas demais análises em decorrência da diferença entre as bases de dados usadas. As faixas etárias usadas pelo SEADE não possuem dados desagregados para a população entre 70 e 79 anos, possuindo somente uma categoria para pessoas acima de 70 anos." style='cursor: help;'><sup>18</sup></a>
		<p>A variação no número de fatalidades é diferente da variação populacional dos diversos grupos no período em análise. Houve uma redução da população mais jovem, de até 29 anos, e um aumento entre da população nas faixas etárias mais elevadas, especialmente acima dos 50 anos. Isso decorre do envelhecimento populacional, o que reforça a necessidade de melhorar o sistema de mobilidade para acomodar os idosos com mais segurança.</p>
		<p>O grupo de 20 a 29 anos teve decréscimo populacional e, mesmo assim, foi o que apresentou uma das menores reduções no índice de vítimas fatais. Uma possível interpretação é a relação entre esse grupo etário e o aumento do uso de motocicletas (crescimento de 20%<a title="  [1] DETRAN/SP – Frota de veículos na capital por tipo de veículos (Jan/2013-Dez/2017)" style='cursor: help;'><sup>19</sup></a> da frota entre 2013 e 2017) por jovens, considerando que é o modo de transporte mais envolvido em acidentes fatais nessa faixa etária.</p>
		<p>Além disso, esse grupo etário apresentou o segundo maior índice de fatalidade em 2013 e em 2017 (13,3 e 12,1 mortos/100 mil habitantes, respectivamente), assim como a menor redução entre todos os grupos etários (-9%). Idosos com mais de 70 anos tiveram uma das maiores quedas no número de mortos e entre as fatalidades, porém, ainda apresentam o maior índice de fatalidade entre todos grupos etários (12,3 mortos/100 mil habitantes).</p>
		<slot name='t4'></slot>
		<p>Similarmente, ao analisar o percentual de vítimas fatais por grupos de idade e modo de transporte (Gráfico 14), é possível observar que mortes de 10-39 anos são na maioria motociclistas, enquanto que para grupos acima dos 50 anos e abaixo dos 10 anos as vítimas são majoritariamente pedestres. Pedestres crianças – com até 9 anos – correspondem a 73% das vítimas fatais dessa faixa etária. Para idosos acima dos 70 anos, o percentual de morte de pedestres é ainda mais expressivo, chegando à parcela de 84% das fatalidades no trânsito para essa faixa etária.</p>
		<slot name='g21'></slot>
		<p>No Gráfico 15 é possível ver a proporção de viagens e mortes por faixa etária e modo de transporte em 2017. O grupo de 20 a 29 anos apresenta alta proporção de mortes na maioria dos modos de transporte (45% na motocicleta, 34% no carro e 24% na bicicleta) em comparação com as outras faixas etárias.</p>
		<p>No caso específico da motocicleta, a distribuição de viagens para pessoas com menos de 30 anos corresponde a pouco mais de 40%, no entanto, mais de 60% das fatalidades acontecem nesse grupo de pessoas. Da mesma forma, dentre os pedestres, as pessoas com mais de 50 anos realizam menos de 20% das viagens a pé, mas respondem por mais de 50% das fatalidades.</p>
		<slot name='g22'></slot>
		<slot name='g23'></slot>
		<slot name='g24'></slot>
		<slot name='g25'></slot>
		<p>	Os principais pontos críticos de acidentes com mortes de crianças, adolescentes e jovens menores de 18 anos podem ser relacionados com a proximidade de escolas, sobretudo nas zonas periféricas, onde há maior densidade de fatalidades entre 2013 e 2017. Ao analisar o mapa 1 envolvendo a concentração de escolas com a densidade de acidentes com jovens vítimas fatais, percebe-se algumas áreas de sobreposição destas variáveis. As escolas são equipamentos basicamente frequentados por esse grupo etário e, geralmente, implicam dinâmica de concentração de muitos estudantes nas ruas próximas, nos horários de chegada e saída das aulas. Portanto, a sobreposição desses pontos críticos com a concentração desses equipamentos pode ser um indicativo para promoção da redução de velocidade e fortalecimento de elementos de segurança viária. Algumas dessas regiões apresentam grande sobreposição – acidentes e escolas -, como a região do Campo Limpo, na Zona Sul, Brasilândia, na Zona Norte, e São Miguel Paulista, Guaianazes e Cidade São Mateus, na Zona Leste.</p>
		<slot name='m1'></slot>
		<p>O gráfico 17 indica a proporção de viagens e vítimas fatais por modo de transporte de acordo com o gênero para o ano de 2017<a title="  O modo ônibus foi removido devido ao baixo número de mortes, 8, no comparativo com o número de viagens" style='cursor: help;'><sup>20</sup></a>. Para todos os modos, os homens apresentam maior porcentagem de fatalidades relativamente à quantidade de viagens que fazem. Isso indica que os homens são mais propensos a morrer no trânsito em comparação com as mulheres, independentemente do modo de transporte escolhido. Diversas fontes de estudo associam riscos mais elevados, como dirigir em maiores velocidades, ao gênero masculino (Redshaw, 2006; Vick, 2003).</p>
		<p>Observando a barra final, em que os valores são consolidados para todos os modos, podemos ver que a distribuição de viagens para homens e mulheres é muito semelhante. No entanto, a maioria das fatalidades são de homens, com uma proporção de quase 4 para 1.</p>
		<slot name='g26'></slot>
		<p>De acordo com levantamento promovido a partir de dados da CET, 87,4% dos acidentes fatais ocorreram em meio de quadra e apenas 12,6% em cruzamentos.</p>
		<slot name='t5'></slot>
		<p>No que se refere às vias mais perigosas, de acordo com a  CET (Tabela 6), as 20 vias com maior número de acidentes fatais ao longo do ano concentraram um total de 163 acidentes, com 173 mortos, o que representa aproximadamente 22% do total de mortes no trânsito em 2017. De acordo com o relatório, as Subprefeituras com maior número de acidentes fatais foram Sé (43); Capela do Socorro (42); Campo Limpo (41) e M’Boi Mirim (37), que somaram 21% do total de acidentes fatais ocorridos no ano (762).</p>
		<slot name='t6'></slot>
		<p>Esta lista expõem o número de acidentes, em números absolutos, nas principais vias da cidade. Embora válidos, existem outras maneiras de determinações de vias críticas, com a inclusão de pesos aos diferentes tipos de ocorrência e ponderações por extensão da via e volume de tráfego. Seguindo recomendações do DNIT, é possível calcular A Unidade Padrão de Severidade, que considera: </p>
		<ul>
			<li>UPS = DM + 4VF + 6PF + 13FAT</li>
			<li>DM: acidentes com danos materiais</li>
			<li>VF = acidentes com vítimas feridas</li>
			<li>PF =  acidentes com pedestre feridos</li>
			<li>FAT = acidente com vítima fatal</li>
		</ul>
		<p>Aplicando o UPS para as vias críticas de São Paulo, ponderado pela sua extensão, chega-se a uma nova lista, que mede a UPS por Km:</p>
		<slot name='t7'></slot>
		<p>Os atropelamentos fatais apresentam grande concentração no centro de São Paulo, local de intensa circulação de pedestres e alta atividade comercial. Além dessa região, ao analisar o mapa 2 é possível localizar outros focos de grande concentração de atropelamentos fatais. Na Zona Sul, há altas densidades de atropelamentos fatais nas proximidades da estação Adolfo Pinheiro e Praça do Campo Limpo. Nas zonas Norte e Oeste da cidade, Barra Funda, Santana e a Marginal Tietê reúnem os principais focos. Na Zona Leste, os atropelamentos fatais se concentram ao redor da Av. Jacu-Pêssego, centro de São Miguel Paulista e Av. Marechal Tito/Itaim Paulista.</p>
		<slot name='m2'></slot>
		<p>Atropelamentos envolvendo ônibus também ocorrem mais no centro da cidade e em locais semelhantes aos dos atropelamentos fatais, como mostra o mapa 3. Regiões como Lapa, Santana e Santo Amaro possuem alto índice de atropelamentos por ônibus, principalmente próximo a centros comerciais e estações de ônibus e metrô. Ainda, outras regiões se destacam próximo ao centro da cidade. A Av. Celso Garcia, que teve faixas dedicadas de ônibus no contrafluxo, possui alta concentração de atropelamentos por ônibus (Mapa 3) praticamente ao longo de toda sua extensão.</p>
		<p>A Av. Paulista apresenta grande incidência desse tipo de acidente nas proximidades da interseção com a Av. da Consolação, onde há um corredor de ônibus e também está localizada a Estação Paulista do Metrô. Corredores de ônibus são tradicionalmente implementados nas principais avenidas de uma cidade e costumam apresentar diversos tipos de conflitos devido à grande presença de pessoas e alto fluxo de veículos.</p>
		<slot name='m3'></slot>
		<p>
			Assim como acontece com os demais acidentes, há uma concentração de acidentes com ciclistas no centro da cidade. Ao contrário dos perfis de vítimas analisados anteriormente, para o usuário de bicicleta, a Zona Sul da cidade praticamente não apresenta focos de acidentes, enquanto a Zona Norte possui diversos, principalmente nas regiões mais periféricas. Ao Norte, Vila Maria, Jardim Brasil, Jaçanã, Brasilândia e Parque Tietê são os principais locais de acidentes com ciclistas. No Leste, isso ocorre em toda a extensão da Av. Marechal Tito, ligando São Miguel Paulista ao Itaim Paulista.
		</p>
		<slot name='m4'></slot>
		<p>O mapa 5 mostra que a rede cicloviária de São Paulo possui pontos onde o traçado e a falta de conectividade podem estar gerando problemas de segurança viária.</p>
		<slot name='m5'></slot>
		<p>Motociclistas correspondem a 50% do total de vítimas feridas no trânsito de São Paulo. O Mapa 6 mostra como os acidentes com vítimas estão distribuídos por grande parte da cidade. Porém, alguns corredores viários específicos possuem grau de concentração maior. Tanto a Av. Rebouças como a Rua da Consolação possuem alta concentração de acidentes com vítimas ao longo de quase toda sua extensão. Na Zona Norte, a Av. Cruzeiro do Sul, Av. Tiradentes e a região de Santana reúnem também alto número dessas vítimas. Na Zona Leste, a Av. Radial Leste concentra os acidentes desde as proximidades da Estação Brás do Metrô até a Estação Guilhermina-Esperança. Na Zona Sul, há uma concentração na Estrada de Itapecerica, que se estende das proximidades da Estação Capão Redondo da CPTM até os limites da Estação Giovanni Gronchi, próxima ao Rio Pinheiros. Ainda nessa zona, em trecho mais ao sul do tecido urbano, há também alto índice de acidentes com motocicletas principalmente ao longo da Av. Dona Belmira Marin até a Estação Terminal Grajaú da CPTM.</p>
		<slot name='m6'></slot>
		<p>Ao contrário dos demais tipos de acidentes em análise, os acidentes fatais envolvendo motocicletas não estão tão concentrados na zona central da cidade (Mapa 8). Diversos focos de altas densidade de acidentes fatais com esses usuários são localizados em áreas mais periféricas. Na Zona Norte, a Marginal Tietê concentra 7 focos de acidentes envolvendo motociclistas mortos, enquanto na Zona Leste os locais estão em São Miguel Paulista, nos arredores da Av. Águia de Haia e proximidade da Estação Artur Alvim, e Itaquera. Na Zona Sul, a Av. Guido Caloi e Av. M’Boi Mirim concentram acidentes fatais com motociclistas ao longo de boa parte de suas extensões, bem como a Estrada de Itapecerica, desde o limite com o município de Itapecerica até a Av. João Dias, nas proximidades do Rio Pinheiros.</p>
		<slot name='m7'></slot>
		<p>A diferença entre a distribuição espacial do total de acidentes envolvendo motociclistas com vítimas dos fatais pode estar ligada a várias causas. As avenidas periféricas são eixos de ligação entre as regiões e o centro, concentram grande volume de cidadãos que utilizam motocicletas ao se deslocarem a caminho do trabalho ou para outros locais. Durante o dia, com as pistas mais ocupadas, os acidentes causam mais vítimas feridas do que mortas. À noite, com as pistas mais livres e maior desenvolvimento de velocidades, diminui o número de acidentes, mas eleva-se a sua gravidade. Ainda, a maior dificuldade na fiscalização de motocicletas nas periferias pode ser um fator de maior gravidade.</p>
	</div>
</template>

<script>
export default {
	name: 'Cap2A'
}
</script>
