<template>
	<div class="Cap3EixoI">
		<h5>a.	Objetivos</h5>
<p>●	Promover ações sempre coordenadas e bem articuladas entre os diferentes órgãos governamentais e entre poder público e sociedade civil;</p>
<p>●	Desenvolver projetos viários e implantar obras viárias com alinhamento conceitual (priorização da segurança viária) entre os diferentes órgãos e com base nos mesmos parâmetros;</p>
<p>●	Prover as ações voltadas à segurança viária garantindo recursos financeiros suficientes às implantações necessárias.</p>

<h5>b.	Diretrizes e Estratégias de Atuação</h5>
<u>i.	Fortalecimento institucional das instâncias de deliberação conjunta</u>
<p>A primeira estratégia de atuação deste plano é a maturação e consolidação das instâncias de deliberação conjunta da PMSP, iniciando-se com a do próprio Comitê Permanente de Segurança Viária como instância responsável pela articulação e promoção das políticas públicas voltadas à segurança viária. Com a manutenção mensal de reuniões, a instância deve ser fortalecida como local de planejamento e operacionalização das ações conjuntas, tais como as requalificações integradas em corredores de transporte, segurança em rotas escolares, entre outros.</p>
<p>Adicionalmente, prevê-se a instituição de uma instância de coordenação interna à CET, onde sejam discutidas as prioridades, encaminhadas as demandas entre diferentes níveis de poder, avaliados os projetos, debatidas as campanhas, sincronizadas as atividades, etc. A composição desta instância deve contemplar a representação de todas as diretorias da empresa, podendo se articular junto à presidência, a fim de ter ascendência sobre a estrutura da CET.</p>
<p>Propõe-se também a criação da câmara temática de motocicleta como instância de interlocução entre o poder público e as diversas organizações de motociclistas, para que se estreite o diálogo entre Estado e esse expressivo grupo de usuários.</p>
<p>Propõe-se também a criação de instância de deliberação e aprovação de projetos relativos a obras viárias, com o objetivo de gerar melhor articulação, dar maior agilidade e fortalecer a responsividade sobre os resultados dos projetos e obras. Sugere-se que a nova instância seja criada à semelhança das instituídas pelo Decreto Municipal 58.028/2017 voltadas à aprovação de projetos privados, chamadas Grupo Intersecretarial de Análise de Projetos Específicos no Município (GRAPROEM) e Comitê Gestor do Aprova Rápido. A instância pode também ser criada à semelhança da Comissão Permanente de Acessibilidade (CPA), com integrantes de todos os órgãos necessários, treinados e especializados em segurança viária.</p>
<p>Para além do fortalecimento das instâncias de deliberação conjunta, a PMSP deve buscar novos modelos de governança sobre o sistema viário possíveis de serem implantados no município. No momento, ainda não se sabe qual modelo deve ser seguido, motivo pelo qual serão engendrados esforços para promover  o debate acerca do tema e se construir uma proposta para São Paulo.</p>

<u>ii.	Governança sobre as calçadas</u>
<p>Para além das instâncias citadas no item anterior, este plano reitera a importância e relevância da Comissão Permanente de Calçadas (CPC), que, recém criada, tem cumprido papel essencial na articulação e condução das políticas públicas relacionadas às calçadas. A solidificação de sua institucionalização é essencial à segurança viária do município.</p>
<p>Quanto à divisão de responsabilidade sobre as calçadas entre o proprietário do lote adjacente e a PMSP, a atualização da relação de calçadas que compõem as rotas do plano emergencial de calçadas e a consequente execução da padronização é fundamental para garantir acessibilidade universal aos equipamentos da cidade. Deste modo, a estratégia definida é a gradual expansão das responsabilidades da Prefeitura sobre as calçadas. Será efetivada a revisão do PEC, expandindo a responsabilidade do município.</p>

<u>iii.	Atuação junto à região metropolitana</u>
<p>Apesar de não estar sob governabilidade da PMSP, propõe-se que esta, em especial por meio da SMT, atue para a criação da Câmara Temática Metropolitana Intergovernamental, proposta contida no “Caderno Final de Propostas” do Plano de Desenvolvimento Integrado da Região Metropolitana de São Paulo (PDUI).</p>
<p>Além disso, tendo em vista o papel protagonista do município de São Paulo, por ser a maior metrópole brasileira, propõe-se que a cidade atue como disseminadora dos conceitos de Visão Zero e Sistemas Seguros junto aos demais municípios de sua região metropolitana.</p>

<u>iv.	Gestão orçamentária</u>
<p>O diagnóstico deste plano objetivou levantar as diferentes fontes de financiamento à ações de segurança viária, e também explicitou o caráter transversal da pauta, de modo que qualquer nova infraestrutura ou requalificação deva priorizar a segurança viária. Deste modo, Institui-se como diretriz de atuação a priorização dos recursos financeiros, em especial os do FMDT, à ações afetas à segurança viária. As ações do fundo devem ser pautadas levanto em conta a segurança viária. Faz-se necessário ainda aprofundar o entendimento sobre o como o Comitê Permanente de Segurança pode atuar junto ao conselho do fundo para pautar as ações de segurança viária.</p>

<u>v.	Expansão do número de agentes de trânsito.</u>
<p>A segurança viária depende em grande medida da capacidade de fiscalização ostensiva do município. A presença do Estado na rua amplia a sensação de fiscalização, incentivando o cumprimento das regras de trânsito. Por isso, propõe-se como estratégia de atuação a expansão do número de agentes de trânsito.</p>

<h5>c.	Produtos</h5>
<table class="headed-table"><tr><th> Ação 2019-2020 </th><th> Indicador </th><th> 2019 </th><th> 2020 </th></tr><tr><td><br>  Instituir o Comitê Permanente de Segurança Viária via decreto municipal<br>  </td><td> Decreto publicado </td><td> x </td><td>   </td></tr><tr><td><br>  Instituir instância interna à CET de coordenação das ações de segurança viária<br>  </td><td> Instância instituída </td><td> x </td><td>   </td></tr><tr><td><br>  Realizar estudo de benchmarking sobre a governança sobre o sistema viário, que culmine em proposta de reforma administrativa da PMSP<br>  </td><td> Estudo publicado </td><td>   </td><td> x </td></tr><tr><td><br>  Revisar o Plano Emergencial de Calçadas (PEC), expandindo a quantidade de passeios sob responsabilidade da PMSP  </td><td> Nova PEC publicada </td><td> x </td><td>   </td></tr><tr><td><br>  Operacionalizar a Câmara Técnica de Motocicleta<br>  </td><td> câmara em operação com a realização das reuniões </td><td> x </td><td>   </td></tr><tr><td><br>  Implantar a ISO 39.001 na CET<br>  </td><td> Certificação obtida </td><td>   </td><td> x </td></tr><tr><td><br>  Implantar a ISO 39.001 na SPTrans<br>  </td><td> Certificação obtida </td><td>   </td><td> x </td></tr><tr><td><br>  Criar instância de deliberação e aprovação de projetos relativos a obras viárias (GRAPROEM das obras viárias)<br>  </td><td> Decreto de criação  publicado </td><td>   </td><td> x </td></tr><tr><td> Criar ação orçamentária (“rubrica”) específica para implantação de áreas de acalmamento de tráfego e outras intervenções de segurança viária </td><td> Ação orçamentária incluída na peça orçamentária </td><td> x </td><td>   </td></tr><tr><td> Implementar metodologia de custeio de ações </td><td> Metodologia publicada </td><td> x </td><td>   </td></tr><tr><td> Propor alteração da legislação do FMDT para que se crie vinculação de parte dos recursos do fundo a ações específicas de segurança viária. </td><td> Proposta enviada à câmara dos vereadores </td><td>   </td><td> x </td></tr><tr><td> Propor a criação de carreira de gestor dos espaços públicos, selecionado entre aqueles que são formados em arquitetura e urbanismo e engenharia, e que nas secretarias e subprefeituras, tenham como missão coordenar as atividades de implantação de projetos relacionados ao manual de projetos e obras dos espaços públicos de circulação, bem como monitorar a manutenção dos mesmos. </td><td> Proposta de criação enviada à câmara dos vereadores </td><td>   </td><td> x </td></tr><tr><td> Contratar agentes de trânsito </td><td> Nº de agentes contratados </td><td>   </td><td> <strong>500</strong> </td></tr></table>
	</div>
</template>

<script>
export default {
	name: 'Cap3EixoI'
}
</script>
