<template>
	<div class="Cap3EixoIII">
<h5>a.	Objetivos</h5>
<p>●	Oferecer opções sustentáveis, seguras e saudáveis de transporte, por meio da ampliação do conforto e qualidade dos serviços prestados e qualificação e ampliação da infraestrutura da mobilidade ativa e do transporte coletivo; </p>
<p>●	Incentivar soluções inovadoras de mobilidade que façam uso eficiente do espaço público.</p>

<h5>b.	Estratégias e Diretrizes de Atuação</h5>
<h6>i.	Incentivos e proteção dos modos ativos</h6>
<p>Os meios de transporte sustentáveis devem ser incentivados pelos seus efeitos positivos na saúde pública e no meio ambiente, além de serem formas eficientes de deslocamento devido ao espaço que ocupam no espaço público em relação à capacidade.  Entretanto, o risco relativo de pedestres e ciclistas serem vítimas fatais no trânsito é de respectivamente 179 e 33 vezes em comparação com o usuário do ônibus. Sendo assim, é de suma importância para a saúde pública que os investimentos sejam destinados às formas sustentáveis, saudáveis e seguras de deslocamento. </p>

<h6>ii.	Mobilidade e tecnologia</h6>
<p>Os novos meios de transporte decorrentes do avanço da tecnologia exigem que o poder público atue forma ágil para garantir a segurança de todos os usuários da via. As novas formas de mobilidade, como veículos autônomos, bicicletas compartilhadas, patinetes elétricos, representam uma revolução para a qual a Prefeitura deve estar preparada, prevendo a infraestrutura adequada e normatizando o seu uso. </p>
<p>Propõe-se que seja elaborado estudo que englobe as diversas opções de mobilidade inovadoras, para subsidiar a legislação, a infraestrutura e a política de dados pertinentes. </p>

<h6>iii.	Melhorias do STCUP</h6>
<p>O edital para concessão do serviço municipal de transporte público sobre pneus, publicado em 24 de abril de 2018, prevê inúmeras mudanças nos parâmetros da contratação, visando significativas melhorias para o serviço. Em síntese, prevê-se a modernização da frota, melhor distribuição das linhas de ônibus, redução das sobreposições de itinerários, aumento da oferta de lugares e maior capilarização da rede pelo território da cidade.</p>
<p>No que se refere à cobertura da rede, planeja-se um aumento de 9%, passando de 4.680 km para 5.100 km, facilitando o acesso ao serviço. Pretende-se que a oferta de lugares seja incrementada em 10%, o que representa 105.656 novos lugares. Tal melhoria é obtida por meio da substituição de veículos menores por veículos com maior capacidade. Ademais, são previstas outras melhorias tecnológicas tratadas no Eixo VI - Normas e Tecnologia de Veículos.</p>

<h6>iv.	Nova forma de remuneração das empresas operadoras do STCUP</h6>
<p>Espera-se que as alterações no sistema de remuneração das empresas operadoras do STCUP previstas no edital de licitação induzam melhorias para os passageiros. O pagamento deixa de ser por passageiro transportado e passa a ser feito por meio de uma combinação de fatores, que inclui a qualidade do serviço (avaliada pelo Índice de Qualidade do Transporte) e o custo operacional.</p>
<p>Pelo novo edital, os operadores serão remunerados pelos serviços efetivamente disponibilizados e medidos, ou seja, serão medidos os quantitativos de horas, quilômetros e veículos disponibilizados. Tais quantitativos, multiplicados pelos preços específicos de referência, resultarão na remuneração bruta do operador. Sobre essa remuneração, o operador sofrerá desconto se o Índice de Qualidade do Transportes (IQT) tiver nota de regular para baixo.</p>
<p>O IQT será composto por 11 indicadores, sendo 1 deles o índice de quilômetro por acidente (IQA) , cuja meta é zero acidente de responsabilidade do operador por 1.000.000 de quilômetros percorridos. Assim, volumes maiores de acidentes geram piora no IQA, que consequentemente gera redução do IQT, que, por sua vez, impacta na remuneração da empresa, podendo provocar descontos no valor a ser pago.</p>
<p>O novo sistema de remuneração desestimula também a manutenção de ônibus que circulam com superlotação, já que a remuneração não mais é baseada no número de passageiros. Além disso, cabe ressaltar que as empresas que proporcionarem economia aos cofres da PMSP, por meio de uma operação mais eficiente, serão premiadas por meio da repartição de metade da economia gerada.</p>
<p>Por fim, destaca-se ainda que com os novos contratos as empresas operadoras terão a obrigação de implantar a ISO 39.001.</p>

<h6>v.	Frota de ônibus limpa</h6>
<p>A nova licitação de concessão do STCUP impõe às operadoras a redução de emissões de poluentes, sob pena de aplicação de sanções, em acordo com as determinações da lei. Os editais estabelecem metas mais arrojadas que as previstas em lei e determinam que, em até 20 anos após a assinatura dos contratos, deverá haver uma redução integral das emissões desses três componentes, de forma a se obter uma frota de ônibus limpos na cidade de São Paulo. Ademais, passa a ser vedada a qualquer tempo a prestação de serviços por veículo, cujo ano ou modelo do chassi seja superior a 10 anos. Além disso, a frota deverá ter idade média de, no máximo, cinco anos.</p>

<h6>vi.	Terminais de Ônibus</h6>
<p>A mobilidade universal fomenta o acesso amplo e democrático aos espaços públicos e privados através de políticas integradas de mobilidade e desenvolvimento urbano, visando a justiça e a inclusão social. É necessário romper as barreiras impostas à acessibilidade das pessoas com deficiência, que são numerosas e integram o cotidiano das pessoas com deficiência na maioria das cidades brasileiras e a cidade de São Paulo não foge à regra.</p>
<p>Reconhecendo essa dívida histórica para com as pessoas com deficiência,a SPTrans  tem feito aplicar a normatização técnica de acessibilidade na construção, operação e manutenção dos Terminais Urbanos de Passageiros na Cidade de São Paulo em sintonia com a acessibilidade da frota de ônibus municipal.</p>
<p>Em consonância com o Plano Diretor da Cidade de São Paulo, as medidas para a requalificação urbana preveem acessibilidade universal num raio de 600 metros no entorno dos Terminais Urbanos de Passageiros propiciando ainda mais e melhores condições de conforto, segurança e acessibilidade para todas as pessoas e em particular para as pessoas com deficiência e mobilidade reduzida.</p>
<p>O primeiro Edital de Concessão de terminais urbanos de passageiros da cidade de São Paulo é o do Terminal Princesa Isabel localizado no Bairro de Campos Elísios. A concessão desse terminal, que pretende ser modelo para concessões futuras, apresenta uma série de condicionantes ligados à acessibilidade do próprio terminal e de seu entorno.</p>
<p>Nesse sentido, destacamos os itens que seguem encontrados no ANEXO III – CADERNO DE ENCARGOS DA CONCESSIONÁRIA - CONCORRÊNCIA INTERNACIONAL N° 002/SMT/2018 Secretaria Municipal de Mobilidade e Transporte e Secretaria Municipal de Desestatização e Parcerias:</p>

<p class="quotation">
	É única e exclusiva responsabilidade da CONCESSIONÁRIA as obras necessárias para que o TERMINAL, os EMPREENDIMENTOS ASSOCIADOS e as obras de melhoria do PERÍMETRO DE ABRANGÊNCIA respeitem estritamente as especificações estabelecidas neste documento, nas normas técnicas de regência e na legislação aplicável, em especial a Lei Municipal nº 16.050/2014 (Plano Diretor Estratégico do Município de São Paulo), Lei Municipal nº 16.402/2016 (Lei de Parcelamento, Uso e Ocupação do Solo), Lei Municipal nº 16.642/2017 (Código de Obras e Edificações do Município de São Paulo), Decreto Municipal nº 56.834/2016 (Plano Municipal de Mobilidade Urbana), Decreto Municipal nº 57.776/2017 Decreto Municipal 56.901/2016 e Decreto Municipal 58.368/2018 (Projeto de Intervenção Urbana do Terminal Princesa Isabel).
</p>

<h6>vii.	Entrega noturna</h6>
<p>O município tem trabalhado em ações para reestruturação da logística urbana, em especial por meio do estímulo à promoção da entrega noturna programada. O objetivo é manter e fortalecer essa política, com o intuito de diminuir os conflitos existentes entre os caminhões e os demais modos de transporte, em especial pedestres e motociclistas. Tendo em vista que a maioria das ocorrências envolvendo caminhões ocorre durante à tarde, mesmo com as já existentes restrições de fluxo para grande parte dos caminhões, estima-se que o estímulo à entrega noturna diminuirá ainda mais o número de caminhões que trafegam pela cidade durante esse período, diminuindo os conflitos e o número de mortes e feridos. Ao mesmo tempo, pela existência de pico entre meia noite e 1 da manhã, faz-se necessário que a expansão do transporte de carga noturna seja realizada junto a medidas de aumento da segurança viária, com destaque à possibilidade de regulamentação que imponha limites mais rígidos à velocidade de circulação dos caminhões no espaço urbano, assim como já existe para os ônibus. Deste modo, propõe-se a elaboração de estudos que investiguem os impactos da entrega noturna para a segurança e proponha soluções de mitigação, com especial atenção para as velocidades dos caminhões.</p>
<p>Além disso, propõe-se também a criação de mini terminais logísticos pela cidade, de modo que a entrega na última milha possa ser realizada por outros tipos de veículos, como utilitários, VUC ou cargo-triciclo. Tais ações visam a redução de ocorrências pela substituição do caminhão por veículos menores e pela redução das distâncias percorridas.</p>

<h6>viii.	Gestão da modalidade carga-frete</h6>
<p>Em que se pese a existência de mecanismos de regulação sobre o tráfego de caminhões na cidade, o município carece, ainda, da implantação de mecanismos de gestão pública sobre essa modalidade de transporte pelo DTP, assim como se dá com os demais modos de transportes diferenciados, como transporte escolar ou táxi. A PMSP atuará no aprimoramento dos mecanismos de gestão da modalidade, partindo da análise e proposição normativa sobre o tema e chegando à operacionalização da fiscalização.</p>

<h5>c.	Produtos 2019-2020</h5>
<table class="headed-table"><tr><th> Produto </th><th>   </th><th> 2019 </th><th> 2020 </th></tr><tr><td> Implantar novo sistema de compartilhamento de bicicletas, caracterizando uma efetiva integração com capilaridade e alcance pleno do território da cidade </td><td> Número de bicicletas em operação   </td><td>   </td><td> 20 mil </td></tr><tr><td> Implementar ferramenta tecnológica para provimento de informações e avaliação em tempo real pelos usuários do STCUP </td><td> Ferramenta implantada </td><td>   </td><td> x </td></tr><tr><td> Implementar ferramenta tecnológica para avaliação consecutiva, pelos condutores, das condições do trajeto percorrido e de elementos da operação no STCUP </td><td> Ferramenta implantada </td><td>   </td><td> x </td></tr><tr><td> Revisar o manual de fiscalização do transporte escolar para fortalecimento da fiscalização sobre os principais fatores de risco, em especial uso de cinto de segurança e uso de celular </td><td> Novo manual publicado </td><td> x </td><td>   </td></tr><tr><td> Revisar o manual de fiscalização do transporte via fretamento para fortalecimento da fiscalização sobre os principais fatores de risco </td><td> Novo manual publicado </td><td> x </td><td>   </td></tr><tr><td> Revisar o manual de fiscalização do transporte via táxi para fortalecimento da fiscalização sobre os principais fatores de risco </td><td> Novo manual publicado </td><td> x </td><td>   </td></tr><tr><td> Instituir manual de fiscalização do transporte via aplicativos (OTTCs) </td><td> Manual publicado </td><td> x </td><td>   </td></tr></table>

	</div>
</template>

<script>
export default {
	name: 'Cap3EixoIII'
}
</script>
